QT += network

HEADERS += \
# Models
    $${PWD}/OAIA2CDateTime.h \
    $${PWD}/OAIAccountCartAdd.h \
    $${PWD}/OAIAccountCartAdd_200_response.h \
    $${PWD}/OAIAccountCartAdd_200_response_result.h \
    $${PWD}/OAIAccountCartAdd_hybris_websites_inner.h \
    $${PWD}/OAIAccountCartList_200_response.h \
    $${PWD}/OAIAccountCartList_200_response_result.h \
    $${PWD}/OAIAccountCartList_200_response_result_carts_inner.h \
    $${PWD}/OAIAccountConfigUpdate_200_response.h \
    $${PWD}/OAIAccountConfigUpdate_200_response_result.h \
    $${PWD}/OAIAccountFailedWebhooks_200_response.h \
    $${PWD}/OAIAccountFailedWebhooks_200_response_result.h \
    $${PWD}/OAIAccountFailedWebhooks_200_response_result_webhook_inner.h \
    $${PWD}/OAIAccountSupportedPlatforms_200_response.h \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result.h \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result_supported_platforms_inner.h \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result_supported_platforms_inner_params.h \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result_supported_platforms_inner_params_required_inner_inner.h \
    $${PWD}/OAIAttributeAdd_200_response.h \
    $${PWD}/OAIAttributeAdd_200_response_result.h \
    $${PWD}/OAIAttributeAssignGroup_200_response.h \
    $${PWD}/OAIAttributeAssignGroup_200_response_result.h \
    $${PWD}/OAIAttributeCount_200_response.h \
    $${PWD}/OAIAttributeCount_200_response_result.h \
    $${PWD}/OAIAttributeDelete_200_response.h \
    $${PWD}/OAIAttributeDelete_200_response_result.h \
    $${PWD}/OAIAttributeInfo_200_response.h \
    $${PWD}/OAIAttributeTypeList_200_response.h \
    $${PWD}/OAIAttributeTypeList_200_response_result.h \
    $${PWD}/OAIAttributeUnassignGroup_200_response.h \
    $${PWD}/OAIAttributeUnassignGroup_200_response_result.h \
    $${PWD}/OAIAttributeUpdate_200_response.h \
    $${PWD}/OAIAttributeUpdate_200_response_result.h \
    $${PWD}/OAIAttributeValueDelete_200_response.h \
    $${PWD}/OAIAttributeValueDelete_200_response_result.h \
    $${PWD}/OAIBaseCustomer.h \
    $${PWD}/OAIBasket.h \
    $${PWD}/OAIBasketInfo_200_response.h \
    $${PWD}/OAIBasketItemAdd_200_response.h \
    $${PWD}/OAIBasketItemAdd_200_response_result.h \
    $${PWD}/OAIBasketLiveShippingServiceCreate_200_response.h \
    $${PWD}/OAIBasketLiveShippingServiceCreate_200_response_result.h \
    $${PWD}/OAIBasketLiveShippingServiceDelete_200_response.h \
    $${PWD}/OAIBasketLiveShippingServiceDelete_200_response_result.h \
    $${PWD}/OAIBasketLiveShippingServiceList_200_response.h \
    $${PWD}/OAIBasketLiveShippingServiceList_200_response_result.h \
    $${PWD}/OAIBasket_Item.h \
    $${PWD}/OAIBasket_Item_Option.h \
    $${PWD}/OAIBasket_LiveShippingService.h \
    $${PWD}/OAIBatch_Job.h \
    $${PWD}/OAIBatch_Job_Result.h \
    $${PWD}/OAIBatch_Job_Result_Item.h \
    $${PWD}/OAIBrand.h \
    $${PWD}/OAICarrier.h \
    $${PWD}/OAICart.h \
    $${PWD}/OAICartCatalogPriceRulesCount_200_response.h \
    $${PWD}/OAICartCatalogPriceRulesCount_200_response_result.h \
    $${PWD}/OAICartCouponAdd.h \
    $${PWD}/OAICartCouponAdd_200_response.h \
    $${PWD}/OAICartCouponAdd_200_response_result.h \
    $${PWD}/OAICartCouponCount_200_response.h \
    $${PWD}/OAICartCouponCount_200_response_result.h \
    $${PWD}/OAICartDelete_200_response.h \
    $${PWD}/OAICartDelete_200_response_result.h \
    $${PWD}/OAICartGiftcardAdd_200_response.h \
    $${PWD}/OAICartGiftcardAdd_200_response_result.h \
    $${PWD}/OAICartGiftcardCount_200_response.h \
    $${PWD}/OAICartGiftcardCount_200_response_result.h \
    $${PWD}/OAICartInfo_200_response.h \
    $${PWD}/OAICartMethods_200_response.h \
    $${PWD}/OAICartMethods_200_response_result.h \
    $${PWD}/OAICartPluginList_200_response.h \
    $${PWD}/OAICartPluginList_200_response_result.h \
    $${PWD}/OAICartScriptAdd_200_response.h \
    $${PWD}/OAICartScriptAdd_200_response_result.h \
    $${PWD}/OAICartValidate_200_response.h \
    $${PWD}/OAICartValidate_200_response_result.h \
    $${PWD}/OAICart_Channel.h \
    $${PWD}/OAICart_MetaData.h \
    $${PWD}/OAICart_ShippingMethod.h \
    $${PWD}/OAICart_ShippingMethod_Rate.h \
    $${PWD}/OAICart_ShippingZone.h \
    $${PWD}/OAICart_ShippingZone2.h \
    $${PWD}/OAICart_StoreInfo.h \
    $${PWD}/OAICart_Warehouse.h \
    $${PWD}/OAICatalogPriceRule.h \
    $${PWD}/OAICatalogPriceRule_Action.h \
    $${PWD}/OAICategory.h \
    $${PWD}/OAICategoryAddBatch.h \
    $${PWD}/OAICategoryAddBatch_200_response.h \
    $${PWD}/OAICategoryAddBatch_200_response_result.h \
    $${PWD}/OAICategoryAddBatch_payload_inner.h \
    $${PWD}/OAICategoryAddBatch_payload_inner_images_inner.h \
    $${PWD}/OAICategoryAdd_200_response.h \
    $${PWD}/OAICategoryAdd_200_response_result.h \
    $${PWD}/OAICategoryAssign_200_response.h \
    $${PWD}/OAICategoryCount_200_response.h \
    $${PWD}/OAICategoryCount_200_response_result.h \
    $${PWD}/OAICategoryDelete_200_response.h \
    $${PWD}/OAICategoryDelete_200_response_result.h \
    $${PWD}/OAICategoryFind_200_response.h \
    $${PWD}/OAICategoryFind_200_response_result.h \
    $${PWD}/OAICategoryFind_200_response_result_category_inner.h \
    $${PWD}/OAICategoryImageAdd_200_response.h \
    $${PWD}/OAICategoryImageAdd_200_response_result.h \
    $${PWD}/OAICategoryInfo_200_response.h \
    $${PWD}/OAIChild.h \
    $${PWD}/OAICountry.h \
    $${PWD}/OAICoupon.h \
    $${PWD}/OAICoupon_Action.h \
    $${PWD}/OAICoupon_Code.h \
    $${PWD}/OAICoupon_Condition.h \
    $${PWD}/OAICoupon_History.h \
    $${PWD}/OAICurrency.h \
    $${PWD}/OAICustomer.h \
    $${PWD}/OAICustomerAdd.h \
    $${PWD}/OAICustomerAdd_200_response.h \
    $${PWD}/OAICustomerAdd_200_response_result.h \
    $${PWD}/OAICustomerAdd_address_inner.h \
    $${PWD}/OAICustomerAdd_consents_inner.h \
    $${PWD}/OAICustomerAddressAdd.h \
    $${PWD}/OAICustomerCount_200_response.h \
    $${PWD}/OAICustomerCount_200_response_result.h \
    $${PWD}/OAICustomerDelete_200_response.h \
    $${PWD}/OAICustomerDelete_200_response_result.h \
    $${PWD}/OAICustomerFind_200_response.h \
    $${PWD}/OAICustomerFind_200_response_result.h \
    $${PWD}/OAICustomerGroupAdd_200_response.h \
    $${PWD}/OAICustomerGroupAdd_200_response_result.h \
    $${PWD}/OAICustomerInfo_200_response.h \
    $${PWD}/OAICustomerUpdate.h \
    $${PWD}/OAICustomerUpdate_address_inner.h \
    $${PWD}/OAICustomer_Address.h \
    $${PWD}/OAICustomer_Attribute.h \
    $${PWD}/OAICustomer_Attribute_Value.h \
    $${PWD}/OAICustomer_Consent.h \
    $${PWD}/OAICustomer_Group.h \
    $${PWD}/OAICustomer_WishList.h \
    $${PWD}/OAICustomer_WishList_Item.h \
    $${PWD}/OAIDiscount.h \
    $${PWD}/OAIGiftCard.h \
    $${PWD}/OAIImage.h \
    $${PWD}/OAIInfo.h \
    $${PWD}/OAILanguage.h \
    $${PWD}/OAIMarketplace_Product.h \
    $${PWD}/OAIMedia.h \
    $${PWD}/OAIModel_Response_Attribute_Attributeset_List.h \
    $${PWD}/OAIModel_Response_Attribute_Group_List.h \
    $${PWD}/OAIModel_Response_Attribute_List.h \
    $${PWD}/OAIModel_Response_Batch_Job_List.h \
    $${PWD}/OAIModel_Response_Cart_Catalog_PriceRules_List.h \
    $${PWD}/OAIModel_Response_Cart_Coupon_List.h \
    $${PWD}/OAIModel_Response_Cart_GiftCard_List.h \
    $${PWD}/OAIModel_Response_Cart_MetaData_List.h \
    $${PWD}/OAIModel_Response_Cart_Script_List.h \
    $${PWD}/OAIModel_Response_Cart_ShippingZones_List.h \
    $${PWD}/OAIModel_Response_Category_List.h \
    $${PWD}/OAIModel_Response_Customer_Attribute_List.h \
    $${PWD}/OAIModel_Response_Customer_Group_List.h \
    $${PWD}/OAIModel_Response_Customer_List.h \
    $${PWD}/OAIModel_Response_Customer_Wishlist_List.h \
    $${PWD}/OAIModel_Response_Marketplace_Product_Find.h \
    $${PWD}/OAIModel_Response_Order_Abandoned_List.h \
    $${PWD}/OAIModel_Response_Order_List.h \
    $${PWD}/OAIModel_Response_Order_PreestimateShipping_List.h \
    $${PWD}/OAIModel_Response_Order_Shipment_List.h \
    $${PWD}/OAIModel_Response_Order_Status_List.h \
    $${PWD}/OAIModel_Response_Order_Transaction_List.h \
    $${PWD}/OAIModel_Response_Product_Attribute_List.h \
    $${PWD}/OAIModel_Response_Product_Brand_List.h \
    $${PWD}/OAIModel_Response_Product_ChildItem_List.h \
    $${PWD}/OAIModel_Response_Product_Currency_List.h \
    $${PWD}/OAIModel_Response_Product_List.h \
    $${PWD}/OAIModel_Response_Product_Option_List.h \
    $${PWD}/OAIModel_Response_Product_Review_List.h \
    $${PWD}/OAIModel_Response_Return_List.h \
    $${PWD}/OAIModel_Response_Subscriber_List.h \
    $${PWD}/OAIModel_Response_Tax_Class_Info.h \
    $${PWD}/OAIModel_Response_Tax_Class_List.h \
    $${PWD}/OAIOrder.h \
    $${PWD}/OAIOrderAbandoned.h \
    $${PWD}/OAIOrderAdd.h \
    $${PWD}/OAIOrderAdd_200_response.h \
    $${PWD}/OAIOrderAdd_200_response_result.h \
    $${PWD}/OAIOrderAdd_note_attributes_inner.h \
    $${PWD}/OAIOrderAdd_order_item_inner.h \
    $${PWD}/OAIOrderAdd_order_item_inner_order_item_option_inner.h \
    $${PWD}/OAIOrderAdd_order_item_inner_order_item_property_inner.h \
    $${PWD}/OAIOrderCount_200_response.h \
    $${PWD}/OAIOrderCount_200_response_result.h \
    $${PWD}/OAIOrderFinancialStatusList_200_response.h \
    $${PWD}/OAIOrderFinancialStatusList_200_response_result.h \
    $${PWD}/OAIOrderFinancialStatusList_200_response_result_order_financial_statuses_inner.h \
    $${PWD}/OAIOrderFulfillmentStatusList_200_response.h \
    $${PWD}/OAIOrderFulfillmentStatusList_200_response_result.h \
    $${PWD}/OAIOrderInfo_200_response.h \
    $${PWD}/OAIOrderPreestimateShippingList.h \
    $${PWD}/OAIOrderPreestimateShippingList_order_item_inner.h \
    $${PWD}/OAIOrderPreestimateShippingList_order_item_inner_order_item_option_inner.h \
    $${PWD}/OAIOrderRefundAdd.h \
    $${PWD}/OAIOrderRefundAdd_200_response.h \
    $${PWD}/OAIOrderRefundAdd_200_response_result.h \
    $${PWD}/OAIOrderRefundAdd_items_inner.h \
    $${PWD}/OAIOrderReturnAdd.h \
    $${PWD}/OAIOrderReturnAdd_200_response.h \
    $${PWD}/OAIOrderReturnAdd_200_response_result.h \
    $${PWD}/OAIOrderReturnAdd_order_products_inner.h \
    $${PWD}/OAIOrderReturnUpdate.h \
    $${PWD}/OAIOrderReturnUpdate_order_products_inner.h \
    $${PWD}/OAIOrderShipmentAdd.h \
    $${PWD}/OAIOrderShipmentAddBatch.h \
    $${PWD}/OAIOrderShipmentAddBatch_payload_inner.h \
    $${PWD}/OAIOrderShipmentAddBatch_payload_inner_items_inner.h \
    $${PWD}/OAIOrderShipmentAdd_200_response.h \
    $${PWD}/OAIOrderShipmentAdd_200_response_result.h \
    $${PWD}/OAIOrderShipmentAdd_items_inner.h \
    $${PWD}/OAIOrderShipmentAdd_tracking_numbers_inner.h \
    $${PWD}/OAIOrderShipmentDelete_200_response.h \
    $${PWD}/OAIOrderShipmentDelete_200_response_result.h \
    $${PWD}/OAIOrderShipmentInfo_200_response.h \
    $${PWD}/OAIOrderShipmentTrackingAdd.h \
    $${PWD}/OAIOrderShipmentTrackingAdd_200_response.h \
    $${PWD}/OAIOrderShipmentTrackingAdd_200_response_result.h \
    $${PWD}/OAIOrderShipmentUpdate.h \
    $${PWD}/OAIOrder_Item.h \
    $${PWD}/OAIOrder_Item_Option.h \
    $${PWD}/OAIOrder_PaymentMethod.h \
    $${PWD}/OAIOrder_PreestimateShipping.h \
    $${PWD}/OAIOrder_Refund.h \
    $${PWD}/OAIOrder_ShippingMethod.h \
    $${PWD}/OAIOrder_Status.h \
    $${PWD}/OAIOrder_Status_HistoryItem.h \
    $${PWD}/OAIOrder_Status_Refund.h \
    $${PWD}/OAIOrder_Status_Refund_Item.h \
    $${PWD}/OAIOrder_Total.h \
    $${PWD}/OAIOrder_Totals.h \
    $${PWD}/OAIOrder_Totals_NewDiscount.h \
    $${PWD}/OAIOrder_Transaction.h \
    $${PWD}/OAIPagination.h \
    $${PWD}/OAIPlugin.h \
    $${PWD}/OAIPluginList.h \
    $${PWD}/OAIProduct.h \
    $${PWD}/OAIProductAdd.h \
    $${PWD}/OAIProductAddBatch.h \
    $${PWD}/OAIProductAddBatch_payload_inner.h \
    $${PWD}/OAIProductAddBatch_payload_inner_advanced_prices_inner.h \
    $${PWD}/OAIProductAddBatch_payload_inner_images_inner.h \
    $${PWD}/OAIProductAdd_200_response.h \
    $${PWD}/OAIProductAdd_200_response_result.h \
    $${PWD}/OAIProductAdd_best_offer.h \
    $${PWD}/OAIProductAdd_certifications_inner.h \
    $${PWD}/OAIProductAdd_certifications_inner_files_inner.h \
    $${PWD}/OAIProductAdd_certifications_inner_images_inner.h \
    $${PWD}/OAIProductAdd_files_inner.h \
    $${PWD}/OAIProductAdd_group_prices_inner.h \
    $${PWD}/OAIProductAdd_logistic_info_inner.h \
    $${PWD}/OAIProductAdd_manufacturer_info.h \
    $${PWD}/OAIProductAdd_package_details.h \
    $${PWD}/OAIProductAdd_personalization_details.h \
    $${PWD}/OAIProductAdd_sales_tax.h \
    $${PWD}/OAIProductAdd_seller_profiles.h \
    $${PWD}/OAIProductAdd_shipping_details_inner.h \
    $${PWD}/OAIProductAdd_size_chart.h \
    $${PWD}/OAIProductAdd_specifics_inner.h \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details.h \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details_availabilities_inner.h \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner.h \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details_overrides_inner.h \
    $${PWD}/OAIProductAdd_specifics_inner_food_details.h \
    $${PWD}/OAIProductAdd_specifics_inner_group_products_details_inner.h \
    $${PWD}/OAIProductAdd_tier_prices_inner.h \
    $${PWD}/OAIProductAttributeValueSet_200_response.h \
    $${PWD}/OAIProductAttributeValueSet_200_response_result.h \
    $${PWD}/OAIProductAttributeValueUnset_200_response.h \
    $${PWD}/OAIProductAttributeValueUnset_200_response_result.h \
    $${PWD}/OAIProductChildItemFind_200_response.h \
    $${PWD}/OAIProductChildItemFind_200_response_result.h \
    $${PWD}/OAIProductChildItemInfo_200_response.h \
    $${PWD}/OAIProductCount_200_response.h \
    $${PWD}/OAIProductCount_200_response_result.h \
    $${PWD}/OAIProductCurrencyAdd_200_response.h \
    $${PWD}/OAIProductCurrencyAdd_200_response_result.h \
    $${PWD}/OAIProductDeleteBatch.h \
    $${PWD}/OAIProductDeleteBatch_payload_inner.h \
    $${PWD}/OAIProductFind_200_response.h \
    $${PWD}/OAIProductFind_200_response_result.h \
    $${PWD}/OAIProductFind_200_response_result_product_inner.h \
    $${PWD}/OAIProductImageAdd.h \
    $${PWD}/OAIProductImageAdd_200_response.h \
    $${PWD}/OAIProductImageAdd_200_response_result.h \
    $${PWD}/OAIProductImageUpdate_200_response.h \
    $${PWD}/OAIProductImageUpdate_200_response_result.h \
    $${PWD}/OAIProductInfo_200_response.h \
    $${PWD}/OAIProductManufacturerAdd_200_response.h \
    $${PWD}/OAIProductManufacturerAdd_200_response_result.h \
    $${PWD}/OAIProductOptionAdd.h \
    $${PWD}/OAIProductOptionAdd_200_response.h \
    $${PWD}/OAIProductOptionAdd_200_response_result.h \
    $${PWD}/OAIProductOptionAdd_values_inner.h \
    $${PWD}/OAIProductOptionAssign_200_response.h \
    $${PWD}/OAIProductOptionAssign_200_response_result.h \
    $${PWD}/OAIProductOptionValueAdd_200_response.h \
    $${PWD}/OAIProductOptionValueAdd_200_response_result.h \
    $${PWD}/OAIProductOptionValueAssign_200_response.h \
    $${PWD}/OAIProductOptionValueAssign_200_response_result.h \
    $${PWD}/OAIProductPriceAdd.h \
    $${PWD}/OAIProductPriceUpdate.h \
    $${PWD}/OAIProductPriceUpdate_group_prices_inner.h \
    $${PWD}/OAIProductTaxAdd.h \
    $${PWD}/OAIProductTaxAdd_200_response.h \
    $${PWD}/OAIProductTaxAdd_200_response_result.h \
    $${PWD}/OAIProductTaxAdd_tax_rates_inner.h \
    $${PWD}/OAIProductUpdate.h \
    $${PWD}/OAIProductUpdateBatch.h \
    $${PWD}/OAIProductUpdateBatch_payload_inner.h \
    $${PWD}/OAIProductUpdateBatch_payload_inner_advanced_prices_inner.h \
    $${PWD}/OAIProductUpdateBatch_payload_inner_images_inner.h \
    $${PWD}/OAIProductVariantAdd.h \
    $${PWD}/OAIProductVariantAddBatch.h \
    $${PWD}/OAIProductVariantAddBatch_payload_inner.h \
    $${PWD}/OAIProductVariantAddBatch_payload_inner_combination_inner.h \
    $${PWD}/OAIProductVariantAdd_200_response.h \
    $${PWD}/OAIProductVariantAdd_200_response_result.h \
    $${PWD}/OAIProductVariantAdd_attributes_inner.h \
    $${PWD}/OAIProductVariantDeleteBatch.h \
    $${PWD}/OAIProductVariantDeleteBatch_payload_inner.h \
    $${PWD}/OAIProductVariantImageAdd.h \
    $${PWD}/OAIProductVariantImageAdd_200_response.h \
    $${PWD}/OAIProductVariantImageAdd_200_response_result.h \
    $${PWD}/OAIProductVariantPriceAdd.h \
    $${PWD}/OAIProductVariantPriceUpdate.h \
    $${PWD}/OAIProductVariantUpdate.h \
    $${PWD}/OAIProductVariantUpdateBatch.h \
    $${PWD}/OAIProductVariantUpdateBatch_payload_inner.h \
    $${PWD}/OAIProductVariantUpdate_options_inner.h \
    $${PWD}/OAIProduct_AdvancedPrice.h \
    $${PWD}/OAIProduct_Attribute.h \
    $${PWD}/OAIProduct_ChildItem_Combination.h \
    $${PWD}/OAIProduct_GroupItem.h \
    $${PWD}/OAIProduct_GroupPrice.h \
    $${PWD}/OAIProduct_Inventory.h \
    $${PWD}/OAIProduct_Option.h \
    $${PWD}/OAIProduct_Option_Item.h \
    $${PWD}/OAIProduct_Review.h \
    $${PWD}/OAIProduct_Review_Rating.h \
    $${PWD}/OAIProduct_TierPrice.h \
    $${PWD}/OAIResponse_Attribute_Attributeset_List_Result.h \
    $${PWD}/OAIResponse_Attribute_Group_List_Result.h \
    $${PWD}/OAIResponse_Attribute_List_Result.h \
    $${PWD}/OAIResponse_Batch_Job_List_Result.h \
    $${PWD}/OAIResponse_Batch_Job_Result.h \
    $${PWD}/OAIResponse_Cart_CatalogPriceRules_List_Result.h \
    $${PWD}/OAIResponse_Cart_Coupon_List_Result.h \
    $${PWD}/OAIResponse_Cart_Giftcard_List_Result.h \
    $${PWD}/OAIResponse_Cart_MetaData_List_Result.h \
    $${PWD}/OAIResponse_Cart_Script_List_Result.h \
    $${PWD}/OAIResponse_Cart_ShippingZones_List_Result.h \
    $${PWD}/OAIResponse_Category_List_Result.h \
    $${PWD}/OAIResponse_Customer_Attribute_List_Result.h \
    $${PWD}/OAIResponse_Customer_Group_List_Result.h \
    $${PWD}/OAIResponse_Customer_List_Result.h \
    $${PWD}/OAIResponse_Customer_Wishlist_List_Result.h \
    $${PWD}/OAIResponse_Marketplace_Product_Find_Result.h \
    $${PWD}/OAIResponse_Order_Abandoned_List_Result.h \
    $${PWD}/OAIResponse_Order_List_Result.h \
    $${PWD}/OAIResponse_Order_PreestimateShipping_List_Result.h \
    $${PWD}/OAIResponse_Order_Shipment_List_Result.h \
    $${PWD}/OAIResponse_Order_Status_List_Result.h \
    $${PWD}/OAIResponse_Order_Transaction_List_Result.h \
    $${PWD}/OAIResponse_Product_Attribute_List_Result.h \
    $${PWD}/OAIResponse_Product_Brand_List_Result.h \
    $${PWD}/OAIResponse_Product_ChildItem_List_Result.h \
    $${PWD}/OAIResponse_Product_Currency_List_Result.h \
    $${PWD}/OAIResponse_Product_List_Result.h \
    $${PWD}/OAIResponse_Product_Option_List_Result.h \
    $${PWD}/OAIResponse_Product_Review_List_Result.h \
    $${PWD}/OAIResponse_Return_List_Result.h \
    $${PWD}/OAIResponse_Subscriber_List_Result.h \
    $${PWD}/OAIResponse_Tax_Class_Info_Result.h \
    $${PWD}/OAIResponse_Tax_Class_List_Result.h \
    $${PWD}/OAIReturn.h \
    $${PWD}/OAIReturnActionList_200_response.h \
    $${PWD}/OAIReturnActionList_200_response_result.h \
    $${PWD}/OAIReturnCount_200_response.h \
    $${PWD}/OAIReturnCount_200_response_result.h \
    $${PWD}/OAIReturnInfo_200_response.h \
    $${PWD}/OAIReturnReasonList_200_response.h \
    $${PWD}/OAIReturnReasonList_200_response_result.h \
    $${PWD}/OAIReturnStatusList_200_response.h \
    $${PWD}/OAIReturnStatusList_200_response_result.h \
    $${PWD}/OAIReturn_Action.h \
    $${PWD}/OAIReturn_OrderProduct.h \
    $${PWD}/OAIReturn_Reason.h \
    $${PWD}/OAIReturn_Status.h \
    $${PWD}/OAIScript.h \
    $${PWD}/OAIShipment.h \
    $${PWD}/OAIShipment_Item.h \
    $${PWD}/OAIShipment_TrackingNumber.h \
    $${PWD}/OAISpecialPrice.h \
    $${PWD}/OAIState.h \
    $${PWD}/OAIStatus.h \
    $${PWD}/OAIStoreAttribute.h \
    $${PWD}/OAIStoreAttribute_AttributeSet.h \
    $${PWD}/OAIStoreAttribute_Group.h \
    $${PWD}/OAISubscriber.h \
    $${PWD}/OAITaxClass.h \
    $${PWD}/OAITaxClass_Countries.h \
    $${PWD}/OAITaxClass_Rate.h \
    $${PWD}/OAITaxClass_States.h \
    $${PWD}/OAITaxClass_ZipCodes.h \
    $${PWD}/OAITaxClass_ZipCodes_Range.h \
    $${PWD}/OAIWebhook.h \
    $${PWD}/OAIWebhookCount_200_response.h \
    $${PWD}/OAIWebhookCount_200_response_result.h \
    $${PWD}/OAIWebhookEvents_200_response.h \
    $${PWD}/OAIWebhookEvents_200_response_result.h \
    $${PWD}/OAIWebhookEvents_200_response_result_events_inner.h \
    $${PWD}/OAIWebhookList_200_response.h \
    $${PWD}/OAIWebhookList_200_response_result.h \
# APIs
    $${PWD}/OAIAccountApi.h \
    $${PWD}/OAIAttributeApi.h \
    $${PWD}/OAIBasketApi.h \
    $${PWD}/OAIBatchApi.h \
    $${PWD}/OAIBridgeApi.h \
    $${PWD}/OAICartApi.h \
    $${PWD}/OAICategoryApi.h \
    $${PWD}/OAICustomerApi.h \
    $${PWD}/OAIMarketplaceApi.h \
    $${PWD}/OAIOrderApi.h \
    $${PWD}/OAIProductApi.h \
    $${PWD}/OAIReturnApi.h \
    $${PWD}/OAISubscriberApi.h \
    $${PWD}/OAITaxApi.h \
    $${PWD}/OAIWebhookApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIA2CDateTime.cpp \
    $${PWD}/OAIAccountCartAdd.cpp \
    $${PWD}/OAIAccountCartAdd_200_response.cpp \
    $${PWD}/OAIAccountCartAdd_200_response_result.cpp \
    $${PWD}/OAIAccountCartAdd_hybris_websites_inner.cpp \
    $${PWD}/OAIAccountCartList_200_response.cpp \
    $${PWD}/OAIAccountCartList_200_response_result.cpp \
    $${PWD}/OAIAccountCartList_200_response_result_carts_inner.cpp \
    $${PWD}/OAIAccountConfigUpdate_200_response.cpp \
    $${PWD}/OAIAccountConfigUpdate_200_response_result.cpp \
    $${PWD}/OAIAccountFailedWebhooks_200_response.cpp \
    $${PWD}/OAIAccountFailedWebhooks_200_response_result.cpp \
    $${PWD}/OAIAccountFailedWebhooks_200_response_result_webhook_inner.cpp \
    $${PWD}/OAIAccountSupportedPlatforms_200_response.cpp \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result.cpp \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result_supported_platforms_inner.cpp \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result_supported_platforms_inner_params.cpp \
    $${PWD}/OAIAccountSupportedPlatforms_200_response_result_supported_platforms_inner_params_required_inner_inner.cpp \
    $${PWD}/OAIAttributeAdd_200_response.cpp \
    $${PWD}/OAIAttributeAdd_200_response_result.cpp \
    $${PWD}/OAIAttributeAssignGroup_200_response.cpp \
    $${PWD}/OAIAttributeAssignGroup_200_response_result.cpp \
    $${PWD}/OAIAttributeCount_200_response.cpp \
    $${PWD}/OAIAttributeCount_200_response_result.cpp \
    $${PWD}/OAIAttributeDelete_200_response.cpp \
    $${PWD}/OAIAttributeDelete_200_response_result.cpp \
    $${PWD}/OAIAttributeInfo_200_response.cpp \
    $${PWD}/OAIAttributeTypeList_200_response.cpp \
    $${PWD}/OAIAttributeTypeList_200_response_result.cpp \
    $${PWD}/OAIAttributeUnassignGroup_200_response.cpp \
    $${PWD}/OAIAttributeUnassignGroup_200_response_result.cpp \
    $${PWD}/OAIAttributeUpdate_200_response.cpp \
    $${PWD}/OAIAttributeUpdate_200_response_result.cpp \
    $${PWD}/OAIAttributeValueDelete_200_response.cpp \
    $${PWD}/OAIAttributeValueDelete_200_response_result.cpp \
    $${PWD}/OAIBaseCustomer.cpp \
    $${PWD}/OAIBasket.cpp \
    $${PWD}/OAIBasketInfo_200_response.cpp \
    $${PWD}/OAIBasketItemAdd_200_response.cpp \
    $${PWD}/OAIBasketItemAdd_200_response_result.cpp \
    $${PWD}/OAIBasketLiveShippingServiceCreate_200_response.cpp \
    $${PWD}/OAIBasketLiveShippingServiceCreate_200_response_result.cpp \
    $${PWD}/OAIBasketLiveShippingServiceDelete_200_response.cpp \
    $${PWD}/OAIBasketLiveShippingServiceDelete_200_response_result.cpp \
    $${PWD}/OAIBasketLiveShippingServiceList_200_response.cpp \
    $${PWD}/OAIBasketLiveShippingServiceList_200_response_result.cpp \
    $${PWD}/OAIBasket_Item.cpp \
    $${PWD}/OAIBasket_Item_Option.cpp \
    $${PWD}/OAIBasket_LiveShippingService.cpp \
    $${PWD}/OAIBatch_Job.cpp \
    $${PWD}/OAIBatch_Job_Result.cpp \
    $${PWD}/OAIBatch_Job_Result_Item.cpp \
    $${PWD}/OAIBrand.cpp \
    $${PWD}/OAICarrier.cpp \
    $${PWD}/OAICart.cpp \
    $${PWD}/OAICartCatalogPriceRulesCount_200_response.cpp \
    $${PWD}/OAICartCatalogPriceRulesCount_200_response_result.cpp \
    $${PWD}/OAICartCouponAdd.cpp \
    $${PWD}/OAICartCouponAdd_200_response.cpp \
    $${PWD}/OAICartCouponAdd_200_response_result.cpp \
    $${PWD}/OAICartCouponCount_200_response.cpp \
    $${PWD}/OAICartCouponCount_200_response_result.cpp \
    $${PWD}/OAICartDelete_200_response.cpp \
    $${PWD}/OAICartDelete_200_response_result.cpp \
    $${PWD}/OAICartGiftcardAdd_200_response.cpp \
    $${PWD}/OAICartGiftcardAdd_200_response_result.cpp \
    $${PWD}/OAICartGiftcardCount_200_response.cpp \
    $${PWD}/OAICartGiftcardCount_200_response_result.cpp \
    $${PWD}/OAICartInfo_200_response.cpp \
    $${PWD}/OAICartMethods_200_response.cpp \
    $${PWD}/OAICartMethods_200_response_result.cpp \
    $${PWD}/OAICartPluginList_200_response.cpp \
    $${PWD}/OAICartPluginList_200_response_result.cpp \
    $${PWD}/OAICartScriptAdd_200_response.cpp \
    $${PWD}/OAICartScriptAdd_200_response_result.cpp \
    $${PWD}/OAICartValidate_200_response.cpp \
    $${PWD}/OAICartValidate_200_response_result.cpp \
    $${PWD}/OAICart_Channel.cpp \
    $${PWD}/OAICart_MetaData.cpp \
    $${PWD}/OAICart_ShippingMethod.cpp \
    $${PWD}/OAICart_ShippingMethod_Rate.cpp \
    $${PWD}/OAICart_ShippingZone.cpp \
    $${PWD}/OAICart_ShippingZone2.cpp \
    $${PWD}/OAICart_StoreInfo.cpp \
    $${PWD}/OAICart_Warehouse.cpp \
    $${PWD}/OAICatalogPriceRule.cpp \
    $${PWD}/OAICatalogPriceRule_Action.cpp \
    $${PWD}/OAICategory.cpp \
    $${PWD}/OAICategoryAddBatch.cpp \
    $${PWD}/OAICategoryAddBatch_200_response.cpp \
    $${PWD}/OAICategoryAddBatch_200_response_result.cpp \
    $${PWD}/OAICategoryAddBatch_payload_inner.cpp \
    $${PWD}/OAICategoryAddBatch_payload_inner_images_inner.cpp \
    $${PWD}/OAICategoryAdd_200_response.cpp \
    $${PWD}/OAICategoryAdd_200_response_result.cpp \
    $${PWD}/OAICategoryAssign_200_response.cpp \
    $${PWD}/OAICategoryCount_200_response.cpp \
    $${PWD}/OAICategoryCount_200_response_result.cpp \
    $${PWD}/OAICategoryDelete_200_response.cpp \
    $${PWD}/OAICategoryDelete_200_response_result.cpp \
    $${PWD}/OAICategoryFind_200_response.cpp \
    $${PWD}/OAICategoryFind_200_response_result.cpp \
    $${PWD}/OAICategoryFind_200_response_result_category_inner.cpp \
    $${PWD}/OAICategoryImageAdd_200_response.cpp \
    $${PWD}/OAICategoryImageAdd_200_response_result.cpp \
    $${PWD}/OAICategoryInfo_200_response.cpp \
    $${PWD}/OAIChild.cpp \
    $${PWD}/OAICountry.cpp \
    $${PWD}/OAICoupon.cpp \
    $${PWD}/OAICoupon_Action.cpp \
    $${PWD}/OAICoupon_Code.cpp \
    $${PWD}/OAICoupon_Condition.cpp \
    $${PWD}/OAICoupon_History.cpp \
    $${PWD}/OAICurrency.cpp \
    $${PWD}/OAICustomer.cpp \
    $${PWD}/OAICustomerAdd.cpp \
    $${PWD}/OAICustomerAdd_200_response.cpp \
    $${PWD}/OAICustomerAdd_200_response_result.cpp \
    $${PWD}/OAICustomerAdd_address_inner.cpp \
    $${PWD}/OAICustomerAdd_consents_inner.cpp \
    $${PWD}/OAICustomerAddressAdd.cpp \
    $${PWD}/OAICustomerCount_200_response.cpp \
    $${PWD}/OAICustomerCount_200_response_result.cpp \
    $${PWD}/OAICustomerDelete_200_response.cpp \
    $${PWD}/OAICustomerDelete_200_response_result.cpp \
    $${PWD}/OAICustomerFind_200_response.cpp \
    $${PWD}/OAICustomerFind_200_response_result.cpp \
    $${PWD}/OAICustomerGroupAdd_200_response.cpp \
    $${PWD}/OAICustomerGroupAdd_200_response_result.cpp \
    $${PWD}/OAICustomerInfo_200_response.cpp \
    $${PWD}/OAICustomerUpdate.cpp \
    $${PWD}/OAICustomerUpdate_address_inner.cpp \
    $${PWD}/OAICustomer_Address.cpp \
    $${PWD}/OAICustomer_Attribute.cpp \
    $${PWD}/OAICustomer_Attribute_Value.cpp \
    $${PWD}/OAICustomer_Consent.cpp \
    $${PWD}/OAICustomer_Group.cpp \
    $${PWD}/OAICustomer_WishList.cpp \
    $${PWD}/OAICustomer_WishList_Item.cpp \
    $${PWD}/OAIDiscount.cpp \
    $${PWD}/OAIGiftCard.cpp \
    $${PWD}/OAIImage.cpp \
    $${PWD}/OAIInfo.cpp \
    $${PWD}/OAILanguage.cpp \
    $${PWD}/OAIMarketplace_Product.cpp \
    $${PWD}/OAIMedia.cpp \
    $${PWD}/OAIModel_Response_Attribute_Attributeset_List.cpp \
    $${PWD}/OAIModel_Response_Attribute_Group_List.cpp \
    $${PWD}/OAIModel_Response_Attribute_List.cpp \
    $${PWD}/OAIModel_Response_Batch_Job_List.cpp \
    $${PWD}/OAIModel_Response_Cart_Catalog_PriceRules_List.cpp \
    $${PWD}/OAIModel_Response_Cart_Coupon_List.cpp \
    $${PWD}/OAIModel_Response_Cart_GiftCard_List.cpp \
    $${PWD}/OAIModel_Response_Cart_MetaData_List.cpp \
    $${PWD}/OAIModel_Response_Cart_Script_List.cpp \
    $${PWD}/OAIModel_Response_Cart_ShippingZones_List.cpp \
    $${PWD}/OAIModel_Response_Category_List.cpp \
    $${PWD}/OAIModel_Response_Customer_Attribute_List.cpp \
    $${PWD}/OAIModel_Response_Customer_Group_List.cpp \
    $${PWD}/OAIModel_Response_Customer_List.cpp \
    $${PWD}/OAIModel_Response_Customer_Wishlist_List.cpp \
    $${PWD}/OAIModel_Response_Marketplace_Product_Find.cpp \
    $${PWD}/OAIModel_Response_Order_Abandoned_List.cpp \
    $${PWD}/OAIModel_Response_Order_List.cpp \
    $${PWD}/OAIModel_Response_Order_PreestimateShipping_List.cpp \
    $${PWD}/OAIModel_Response_Order_Shipment_List.cpp \
    $${PWD}/OAIModel_Response_Order_Status_List.cpp \
    $${PWD}/OAIModel_Response_Order_Transaction_List.cpp \
    $${PWD}/OAIModel_Response_Product_Attribute_List.cpp \
    $${PWD}/OAIModel_Response_Product_Brand_List.cpp \
    $${PWD}/OAIModel_Response_Product_ChildItem_List.cpp \
    $${PWD}/OAIModel_Response_Product_Currency_List.cpp \
    $${PWD}/OAIModel_Response_Product_List.cpp \
    $${PWD}/OAIModel_Response_Product_Option_List.cpp \
    $${PWD}/OAIModel_Response_Product_Review_List.cpp \
    $${PWD}/OAIModel_Response_Return_List.cpp \
    $${PWD}/OAIModel_Response_Subscriber_List.cpp \
    $${PWD}/OAIModel_Response_Tax_Class_Info.cpp \
    $${PWD}/OAIModel_Response_Tax_Class_List.cpp \
    $${PWD}/OAIOrder.cpp \
    $${PWD}/OAIOrderAbandoned.cpp \
    $${PWD}/OAIOrderAdd.cpp \
    $${PWD}/OAIOrderAdd_200_response.cpp \
    $${PWD}/OAIOrderAdd_200_response_result.cpp \
    $${PWD}/OAIOrderAdd_note_attributes_inner.cpp \
    $${PWD}/OAIOrderAdd_order_item_inner.cpp \
    $${PWD}/OAIOrderAdd_order_item_inner_order_item_option_inner.cpp \
    $${PWD}/OAIOrderAdd_order_item_inner_order_item_property_inner.cpp \
    $${PWD}/OAIOrderCount_200_response.cpp \
    $${PWD}/OAIOrderCount_200_response_result.cpp \
    $${PWD}/OAIOrderFinancialStatusList_200_response.cpp \
    $${PWD}/OAIOrderFinancialStatusList_200_response_result.cpp \
    $${PWD}/OAIOrderFinancialStatusList_200_response_result_order_financial_statuses_inner.cpp \
    $${PWD}/OAIOrderFulfillmentStatusList_200_response.cpp \
    $${PWD}/OAIOrderFulfillmentStatusList_200_response_result.cpp \
    $${PWD}/OAIOrderInfo_200_response.cpp \
    $${PWD}/OAIOrderPreestimateShippingList.cpp \
    $${PWD}/OAIOrderPreestimateShippingList_order_item_inner.cpp \
    $${PWD}/OAIOrderPreestimateShippingList_order_item_inner_order_item_option_inner.cpp \
    $${PWD}/OAIOrderRefundAdd.cpp \
    $${PWD}/OAIOrderRefundAdd_200_response.cpp \
    $${PWD}/OAIOrderRefundAdd_200_response_result.cpp \
    $${PWD}/OAIOrderRefundAdd_items_inner.cpp \
    $${PWD}/OAIOrderReturnAdd.cpp \
    $${PWD}/OAIOrderReturnAdd_200_response.cpp \
    $${PWD}/OAIOrderReturnAdd_200_response_result.cpp \
    $${PWD}/OAIOrderReturnAdd_order_products_inner.cpp \
    $${PWD}/OAIOrderReturnUpdate.cpp \
    $${PWD}/OAIOrderReturnUpdate_order_products_inner.cpp \
    $${PWD}/OAIOrderShipmentAdd.cpp \
    $${PWD}/OAIOrderShipmentAddBatch.cpp \
    $${PWD}/OAIOrderShipmentAddBatch_payload_inner.cpp \
    $${PWD}/OAIOrderShipmentAddBatch_payload_inner_items_inner.cpp \
    $${PWD}/OAIOrderShipmentAdd_200_response.cpp \
    $${PWD}/OAIOrderShipmentAdd_200_response_result.cpp \
    $${PWD}/OAIOrderShipmentAdd_items_inner.cpp \
    $${PWD}/OAIOrderShipmentAdd_tracking_numbers_inner.cpp \
    $${PWD}/OAIOrderShipmentDelete_200_response.cpp \
    $${PWD}/OAIOrderShipmentDelete_200_response_result.cpp \
    $${PWD}/OAIOrderShipmentInfo_200_response.cpp \
    $${PWD}/OAIOrderShipmentTrackingAdd.cpp \
    $${PWD}/OAIOrderShipmentTrackingAdd_200_response.cpp \
    $${PWD}/OAIOrderShipmentTrackingAdd_200_response_result.cpp \
    $${PWD}/OAIOrderShipmentUpdate.cpp \
    $${PWD}/OAIOrder_Item.cpp \
    $${PWD}/OAIOrder_Item_Option.cpp \
    $${PWD}/OAIOrder_PaymentMethod.cpp \
    $${PWD}/OAIOrder_PreestimateShipping.cpp \
    $${PWD}/OAIOrder_Refund.cpp \
    $${PWD}/OAIOrder_ShippingMethod.cpp \
    $${PWD}/OAIOrder_Status.cpp \
    $${PWD}/OAIOrder_Status_HistoryItem.cpp \
    $${PWD}/OAIOrder_Status_Refund.cpp \
    $${PWD}/OAIOrder_Status_Refund_Item.cpp \
    $${PWD}/OAIOrder_Total.cpp \
    $${PWD}/OAIOrder_Totals.cpp \
    $${PWD}/OAIOrder_Totals_NewDiscount.cpp \
    $${PWD}/OAIOrder_Transaction.cpp \
    $${PWD}/OAIPagination.cpp \
    $${PWD}/OAIPlugin.cpp \
    $${PWD}/OAIPluginList.cpp \
    $${PWD}/OAIProduct.cpp \
    $${PWD}/OAIProductAdd.cpp \
    $${PWD}/OAIProductAddBatch.cpp \
    $${PWD}/OAIProductAddBatch_payload_inner.cpp \
    $${PWD}/OAIProductAddBatch_payload_inner_advanced_prices_inner.cpp \
    $${PWD}/OAIProductAddBatch_payload_inner_images_inner.cpp \
    $${PWD}/OAIProductAdd_200_response.cpp \
    $${PWD}/OAIProductAdd_200_response_result.cpp \
    $${PWD}/OAIProductAdd_best_offer.cpp \
    $${PWD}/OAIProductAdd_certifications_inner.cpp \
    $${PWD}/OAIProductAdd_certifications_inner_files_inner.cpp \
    $${PWD}/OAIProductAdd_certifications_inner_images_inner.cpp \
    $${PWD}/OAIProductAdd_files_inner.cpp \
    $${PWD}/OAIProductAdd_group_prices_inner.cpp \
    $${PWD}/OAIProductAdd_logistic_info_inner.cpp \
    $${PWD}/OAIProductAdd_manufacturer_info.cpp \
    $${PWD}/OAIProductAdd_package_details.cpp \
    $${PWD}/OAIProductAdd_personalization_details.cpp \
    $${PWD}/OAIProductAdd_sales_tax.cpp \
    $${PWD}/OAIProductAdd_seller_profiles.cpp \
    $${PWD}/OAIProductAdd_shipping_details_inner.cpp \
    $${PWD}/OAIProductAdd_size_chart.cpp \
    $${PWD}/OAIProductAdd_specifics_inner.cpp \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details.cpp \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details_availabilities_inner.cpp \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner.cpp \
    $${PWD}/OAIProductAdd_specifics_inner_booking_details_overrides_inner.cpp \
    $${PWD}/OAIProductAdd_specifics_inner_food_details.cpp \
    $${PWD}/OAIProductAdd_specifics_inner_group_products_details_inner.cpp \
    $${PWD}/OAIProductAdd_tier_prices_inner.cpp \
    $${PWD}/OAIProductAttributeValueSet_200_response.cpp \
    $${PWD}/OAIProductAttributeValueSet_200_response_result.cpp \
    $${PWD}/OAIProductAttributeValueUnset_200_response.cpp \
    $${PWD}/OAIProductAttributeValueUnset_200_response_result.cpp \
    $${PWD}/OAIProductChildItemFind_200_response.cpp \
    $${PWD}/OAIProductChildItemFind_200_response_result.cpp \
    $${PWD}/OAIProductChildItemInfo_200_response.cpp \
    $${PWD}/OAIProductCount_200_response.cpp \
    $${PWD}/OAIProductCount_200_response_result.cpp \
    $${PWD}/OAIProductCurrencyAdd_200_response.cpp \
    $${PWD}/OAIProductCurrencyAdd_200_response_result.cpp \
    $${PWD}/OAIProductDeleteBatch.cpp \
    $${PWD}/OAIProductDeleteBatch_payload_inner.cpp \
    $${PWD}/OAIProductFind_200_response.cpp \
    $${PWD}/OAIProductFind_200_response_result.cpp \
    $${PWD}/OAIProductFind_200_response_result_product_inner.cpp \
    $${PWD}/OAIProductImageAdd.cpp \
    $${PWD}/OAIProductImageAdd_200_response.cpp \
    $${PWD}/OAIProductImageAdd_200_response_result.cpp \
    $${PWD}/OAIProductImageUpdate_200_response.cpp \
    $${PWD}/OAIProductImageUpdate_200_response_result.cpp \
    $${PWD}/OAIProductInfo_200_response.cpp \
    $${PWD}/OAIProductManufacturerAdd_200_response.cpp \
    $${PWD}/OAIProductManufacturerAdd_200_response_result.cpp \
    $${PWD}/OAIProductOptionAdd.cpp \
    $${PWD}/OAIProductOptionAdd_200_response.cpp \
    $${PWD}/OAIProductOptionAdd_200_response_result.cpp \
    $${PWD}/OAIProductOptionAdd_values_inner.cpp \
    $${PWD}/OAIProductOptionAssign_200_response.cpp \
    $${PWD}/OAIProductOptionAssign_200_response_result.cpp \
    $${PWD}/OAIProductOptionValueAdd_200_response.cpp \
    $${PWD}/OAIProductOptionValueAdd_200_response_result.cpp \
    $${PWD}/OAIProductOptionValueAssign_200_response.cpp \
    $${PWD}/OAIProductOptionValueAssign_200_response_result.cpp \
    $${PWD}/OAIProductPriceAdd.cpp \
    $${PWD}/OAIProductPriceUpdate.cpp \
    $${PWD}/OAIProductPriceUpdate_group_prices_inner.cpp \
    $${PWD}/OAIProductTaxAdd.cpp \
    $${PWD}/OAIProductTaxAdd_200_response.cpp \
    $${PWD}/OAIProductTaxAdd_200_response_result.cpp \
    $${PWD}/OAIProductTaxAdd_tax_rates_inner.cpp \
    $${PWD}/OAIProductUpdate.cpp \
    $${PWD}/OAIProductUpdateBatch.cpp \
    $${PWD}/OAIProductUpdateBatch_payload_inner.cpp \
    $${PWD}/OAIProductUpdateBatch_payload_inner_advanced_prices_inner.cpp \
    $${PWD}/OAIProductUpdateBatch_payload_inner_images_inner.cpp \
    $${PWD}/OAIProductVariantAdd.cpp \
    $${PWD}/OAIProductVariantAddBatch.cpp \
    $${PWD}/OAIProductVariantAddBatch_payload_inner.cpp \
    $${PWD}/OAIProductVariantAddBatch_payload_inner_combination_inner.cpp \
    $${PWD}/OAIProductVariantAdd_200_response.cpp \
    $${PWD}/OAIProductVariantAdd_200_response_result.cpp \
    $${PWD}/OAIProductVariantAdd_attributes_inner.cpp \
    $${PWD}/OAIProductVariantDeleteBatch.cpp \
    $${PWD}/OAIProductVariantDeleteBatch_payload_inner.cpp \
    $${PWD}/OAIProductVariantImageAdd.cpp \
    $${PWD}/OAIProductVariantImageAdd_200_response.cpp \
    $${PWD}/OAIProductVariantImageAdd_200_response_result.cpp \
    $${PWD}/OAIProductVariantPriceAdd.cpp \
    $${PWD}/OAIProductVariantPriceUpdate.cpp \
    $${PWD}/OAIProductVariantUpdate.cpp \
    $${PWD}/OAIProductVariantUpdateBatch.cpp \
    $${PWD}/OAIProductVariantUpdateBatch_payload_inner.cpp \
    $${PWD}/OAIProductVariantUpdate_options_inner.cpp \
    $${PWD}/OAIProduct_AdvancedPrice.cpp \
    $${PWD}/OAIProduct_Attribute.cpp \
    $${PWD}/OAIProduct_ChildItem_Combination.cpp \
    $${PWD}/OAIProduct_GroupItem.cpp \
    $${PWD}/OAIProduct_GroupPrice.cpp \
    $${PWD}/OAIProduct_Inventory.cpp \
    $${PWD}/OAIProduct_Option.cpp \
    $${PWD}/OAIProduct_Option_Item.cpp \
    $${PWD}/OAIProduct_Review.cpp \
    $${PWD}/OAIProduct_Review_Rating.cpp \
    $${PWD}/OAIProduct_TierPrice.cpp \
    $${PWD}/OAIResponse_Attribute_Attributeset_List_Result.cpp \
    $${PWD}/OAIResponse_Attribute_Group_List_Result.cpp \
    $${PWD}/OAIResponse_Attribute_List_Result.cpp \
    $${PWD}/OAIResponse_Batch_Job_List_Result.cpp \
    $${PWD}/OAIResponse_Batch_Job_Result.cpp \
    $${PWD}/OAIResponse_Cart_CatalogPriceRules_List_Result.cpp \
    $${PWD}/OAIResponse_Cart_Coupon_List_Result.cpp \
    $${PWD}/OAIResponse_Cart_Giftcard_List_Result.cpp \
    $${PWD}/OAIResponse_Cart_MetaData_List_Result.cpp \
    $${PWD}/OAIResponse_Cart_Script_List_Result.cpp \
    $${PWD}/OAIResponse_Cart_ShippingZones_List_Result.cpp \
    $${PWD}/OAIResponse_Category_List_Result.cpp \
    $${PWD}/OAIResponse_Customer_Attribute_List_Result.cpp \
    $${PWD}/OAIResponse_Customer_Group_List_Result.cpp \
    $${PWD}/OAIResponse_Customer_List_Result.cpp \
    $${PWD}/OAIResponse_Customer_Wishlist_List_Result.cpp \
    $${PWD}/OAIResponse_Marketplace_Product_Find_Result.cpp \
    $${PWD}/OAIResponse_Order_Abandoned_List_Result.cpp \
    $${PWD}/OAIResponse_Order_List_Result.cpp \
    $${PWD}/OAIResponse_Order_PreestimateShipping_List_Result.cpp \
    $${PWD}/OAIResponse_Order_Shipment_List_Result.cpp \
    $${PWD}/OAIResponse_Order_Status_List_Result.cpp \
    $${PWD}/OAIResponse_Order_Transaction_List_Result.cpp \
    $${PWD}/OAIResponse_Product_Attribute_List_Result.cpp \
    $${PWD}/OAIResponse_Product_Brand_List_Result.cpp \
    $${PWD}/OAIResponse_Product_ChildItem_List_Result.cpp \
    $${PWD}/OAIResponse_Product_Currency_List_Result.cpp \
    $${PWD}/OAIResponse_Product_List_Result.cpp \
    $${PWD}/OAIResponse_Product_Option_List_Result.cpp \
    $${PWD}/OAIResponse_Product_Review_List_Result.cpp \
    $${PWD}/OAIResponse_Return_List_Result.cpp \
    $${PWD}/OAIResponse_Subscriber_List_Result.cpp \
    $${PWD}/OAIResponse_Tax_Class_Info_Result.cpp \
    $${PWD}/OAIResponse_Tax_Class_List_Result.cpp \
    $${PWD}/OAIReturn.cpp \
    $${PWD}/OAIReturnActionList_200_response.cpp \
    $${PWD}/OAIReturnActionList_200_response_result.cpp \
    $${PWD}/OAIReturnCount_200_response.cpp \
    $${PWD}/OAIReturnCount_200_response_result.cpp \
    $${PWD}/OAIReturnInfo_200_response.cpp \
    $${PWD}/OAIReturnReasonList_200_response.cpp \
    $${PWD}/OAIReturnReasonList_200_response_result.cpp \
    $${PWD}/OAIReturnStatusList_200_response.cpp \
    $${PWD}/OAIReturnStatusList_200_response_result.cpp \
    $${PWD}/OAIReturn_Action.cpp \
    $${PWD}/OAIReturn_OrderProduct.cpp \
    $${PWD}/OAIReturn_Reason.cpp \
    $${PWD}/OAIReturn_Status.cpp \
    $${PWD}/OAIScript.cpp \
    $${PWD}/OAIShipment.cpp \
    $${PWD}/OAIShipment_Item.cpp \
    $${PWD}/OAIShipment_TrackingNumber.cpp \
    $${PWD}/OAISpecialPrice.cpp \
    $${PWD}/OAIState.cpp \
    $${PWD}/OAIStatus.cpp \
    $${PWD}/OAIStoreAttribute.cpp \
    $${PWD}/OAIStoreAttribute_AttributeSet.cpp \
    $${PWD}/OAIStoreAttribute_Group.cpp \
    $${PWD}/OAISubscriber.cpp \
    $${PWD}/OAITaxClass.cpp \
    $${PWD}/OAITaxClass_Countries.cpp \
    $${PWD}/OAITaxClass_Rate.cpp \
    $${PWD}/OAITaxClass_States.cpp \
    $${PWD}/OAITaxClass_ZipCodes.cpp \
    $${PWD}/OAITaxClass_ZipCodes_Range.cpp \
    $${PWD}/OAIWebhook.cpp \
    $${PWD}/OAIWebhookCount_200_response.cpp \
    $${PWD}/OAIWebhookCount_200_response_result.cpp \
    $${PWD}/OAIWebhookEvents_200_response.cpp \
    $${PWD}/OAIWebhookEvents_200_response_result.cpp \
    $${PWD}/OAIWebhookEvents_200_response_result_events_inner.cpp \
    $${PWD}/OAIWebhookList_200_response.cpp \
    $${PWD}/OAIWebhookList_200_response_result.cpp \
# APIs
    $${PWD}/OAIAccountApi.cpp \
    $${PWD}/OAIAttributeApi.cpp \
    $${PWD}/OAIBasketApi.cpp \
    $${PWD}/OAIBatchApi.cpp \
    $${PWD}/OAIBridgeApi.cpp \
    $${PWD}/OAICartApi.cpp \
    $${PWD}/OAICategoryApi.cpp \
    $${PWD}/OAICustomerApi.cpp \
    $${PWD}/OAIMarketplaceApi.cpp \
    $${PWD}/OAIOrderApi.cpp \
    $${PWD}/OAIProductApi.cpp \
    $${PWD}/OAIReturnApi.cpp \
    $${PWD}/OAISubscriberApi.cpp \
    $${PWD}/OAITaxApi.cpp \
    $${PWD}/OAIWebhookApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
