/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAccountCartAdd.h
 *
 * 
 */

#ifndef OAIAccountCartAdd_H
#define OAIAccountCartAdd_H

#include <QJsonObject>

#include "OAIAccountCartAdd_hybris_websites_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIAccountCartAdd_hybris_websites_inner;

class OAIAccountCartAdd : public OAIObject {
public:
    OAIAccountCartAdd();
    OAIAccountCartAdd(QString json);
    ~OAIAccountCartAdd() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCartId() const;
    void setCartId(const QString &cart_id);
    bool is_cart_id_Set() const;
    bool is_cart_id_Valid() const;

    QString getStoreUrl() const;
    void setStoreUrl(const QString &store_url);
    bool is_store_url_Set() const;
    bool is_store_url_Valid() const;

    QString getBridgeUrl() const;
    void setBridgeUrl(const QString &bridge_url);
    bool is_bridge_url_Set() const;
    bool is_bridge_url_Valid() const;

    QString getStoreRoot() const;
    void setStoreRoot(const QString &store_root);
    bool is_store_root_Set() const;
    bool is_store_root_Valid() const;

    QString getStoreKey() const;
    void setStoreKey(const QString &store_key);
    bool is_store_key_Set() const;
    bool is_store_key_Valid() const;

    bool isValidateVersion() const;
    void setValidateVersion(const bool &validate_version);
    bool is_validate_version_Set() const;
    bool is_validate_version_Valid() const;

    bool isVerify() const;
    void setVerify(const bool &verify);
    bool is_verify_Set() const;
    bool is_verify_Valid() const;

    QString getDbTablesPrefix() const;
    void setDbTablesPrefix(const QString &db_tables_prefix);
    bool is_db_tables_prefix_Set() const;
    bool is_db_tables_prefix_Valid() const;

    QString getUserAgent() const;
    void setUserAgent(const QString &user_agent);
    bool is_user_agent_Set() const;
    bool is_user_agent_Valid() const;

    QString getFtpHost() const;
    void setFtpHost(const QString &ftp_host);
    bool is_ftp_host_Set() const;
    bool is_ftp_host_Valid() const;

    QString getFtpUser() const;
    void setFtpUser(const QString &ftp_user);
    bool is_ftp_user_Set() const;
    bool is_ftp_user_Valid() const;

    QString getFtpPassword() const;
    void setFtpPassword(const QString &ftp_password);
    bool is_ftp_password_Set() const;
    bool is_ftp_password_Valid() const;

    qint32 getFtpPort() const;
    void setFtpPort(const qint32 &ftp_port);
    bool is_ftp_port_Set() const;
    bool is_ftp_port_Valid() const;

    QString getFtpStoreDir() const;
    void setFtpStoreDir(const QString &ftp_store_dir);
    bool is_ftp_store_dir_Set() const;
    bool is_ftp_store_dir_Valid() const;

    QString getR3dcartPrivateKey() const;
    void setR3dcartPrivateKey(const QString &r_3dcart_private_key);
    bool is_r_3dcart_private_key_Set() const;
    bool is_r_3dcart_private_key_Valid() const;

    QString getR3dcartAccessToken() const;
    void setR3dcartAccessToken(const QString &r_3dcart_access_token);
    bool is_r_3dcart_access_token_Set() const;
    bool is_r_3dcart_access_token_Valid() const;

    QString getR3dcartapiApiKey() const;
    void setR3dcartapiApiKey(const QString &r_3dcartapi_api_key);
    bool is_r_3dcartapi_api_key_Set() const;
    bool is_r_3dcartapi_api_key_Valid() const;

    QString getAmazonSpClientId() const;
    void setAmazonSpClientId(const QString &amazon_sp_client_id);
    bool is_amazon_sp_client_id_Set() const;
    bool is_amazon_sp_client_id_Valid() const;

    QString getAmazonSpClientSecret() const;
    void setAmazonSpClientSecret(const QString &amazon_sp_client_secret);
    bool is_amazon_sp_client_secret_Set() const;
    bool is_amazon_sp_client_secret_Valid() const;

    QString getAmazonSpRefreshToken() const;
    void setAmazonSpRefreshToken(const QString &amazon_sp_refresh_token);
    bool is_amazon_sp_refresh_token_Set() const;
    bool is_amazon_sp_refresh_token_Valid() const;

    QString getAmazonSpAwsRegion() const;
    void setAmazonSpAwsRegion(const QString &amazon_sp_aws_region);
    bool is_amazon_sp_aws_region_Set() const;
    bool is_amazon_sp_aws_region_Valid() const;

    QString getAmazonSpApiEnvironment() const;
    void setAmazonSpApiEnvironment(const QString &amazon_sp_api_environment);
    bool is_amazon_sp_api_environment_Set() const;
    bool is_amazon_sp_api_environment_Valid() const;

    QString getAmazonSellerId() const;
    void setAmazonSellerId(const QString &amazon_seller_id);
    bool is_amazon_seller_id_Set() const;
    bool is_amazon_seller_id_Valid() const;

    QString getAspdotnetstorefrontApiUser() const;
    void setAspdotnetstorefrontApiUser(const QString &aspdotnetstorefront_api_user);
    bool is_aspdotnetstorefront_api_user_Set() const;
    bool is_aspdotnetstorefront_api_user_Valid() const;

    QString getAspdotnetstorefrontApiPass() const;
    void setAspdotnetstorefrontApiPass(const QString &aspdotnetstorefront_api_pass);
    bool is_aspdotnetstorefront_api_pass_Set() const;
    bool is_aspdotnetstorefront_api_pass_Valid() const;

    QString getAmericommerceAppId() const;
    void setAmericommerceAppId(const QString &americommerce_app_id);
    bool is_americommerce_app_id_Set() const;
    bool is_americommerce_app_id_Valid() const;

    QString getAmericommerceAppSecret() const;
    void setAmericommerceAppSecret(const QString &americommerce_app_secret);
    bool is_americommerce_app_secret_Set() const;
    bool is_americommerce_app_secret_Valid() const;

    QString getAmericommerceAccessToken() const;
    void setAmericommerceAccessToken(const QString &americommerce_access_token);
    bool is_americommerce_access_token_Set() const;
    bool is_americommerce_access_token_Valid() const;

    QString getAmericommerceRefreshToken() const;
    void setAmericommerceRefreshToken(const QString &americommerce_refresh_token);
    bool is_americommerce_refresh_token_Set() const;
    bool is_americommerce_refresh_token_Valid() const;

    QString getBigcommerceapiAdminAccount() const;
    void setBigcommerceapiAdminAccount(const QString &bigcommerceapi_admin_account);
    bool is_bigcommerceapi_admin_account_Set() const;
    bool is_bigcommerceapi_admin_account_Valid() const;

    QString getBigcommerceapiApiPath() const;
    void setBigcommerceapiApiPath(const QString &bigcommerceapi_api_path);
    bool is_bigcommerceapi_api_path_Set() const;
    bool is_bigcommerceapi_api_path_Valid() const;

    QString getBigcommerceapiApiKey() const;
    void setBigcommerceapiApiKey(const QString &bigcommerceapi_api_key);
    bool is_bigcommerceapi_api_key_Set() const;
    bool is_bigcommerceapi_api_key_Valid() const;

    QString getBigcommerceapiClientId() const;
    void setBigcommerceapiClientId(const QString &bigcommerceapi_client_id);
    bool is_bigcommerceapi_client_id_Set() const;
    bool is_bigcommerceapi_client_id_Valid() const;

    QString getBigcommerceapiAccessToken() const;
    void setBigcommerceapiAccessToken(const QString &bigcommerceapi_access_token);
    bool is_bigcommerceapi_access_token_Set() const;
    bool is_bigcommerceapi_access_token_Valid() const;

    QString getBigcommerceapiContext() const;
    void setBigcommerceapiContext(const QString &bigcommerceapi_context);
    bool is_bigcommerceapi_context_Set() const;
    bool is_bigcommerceapi_context_Valid() const;

    QString getBolApiKey() const;
    void setBolApiKey(const QString &bol_api_key);
    bool is_bol_api_key_Set() const;
    bool is_bol_api_key_Valid() const;

    QString getBolApiSecret() const;
    void setBolApiSecret(const QString &bol_api_secret);
    bool is_bol_api_secret_Set() const;
    bool is_bol_api_secret_Valid() const;

    qint32 getBolRetailerId() const;
    void setBolRetailerId(const qint32 &bol_retailer_id);
    bool is_bol_retailer_id_Set() const;
    bool is_bol_retailer_id_Valid() const;

    QString getBigcartelUserName() const;
    void setBigcartelUserName(const QString &bigcartel_user_name);
    bool is_bigcartel_user_name_Set() const;
    bool is_bigcartel_user_name_Valid() const;

    QString getBigcartelPassword() const;
    void setBigcartelPassword(const QString &bigcartel_password);
    bool is_bigcartel_password_Set() const;
    bool is_bigcartel_password_Valid() const;

    QString getBricklinkConsumerKey() const;
    void setBricklinkConsumerKey(const QString &bricklink_consumer_key);
    bool is_bricklink_consumer_key_Set() const;
    bool is_bricklink_consumer_key_Valid() const;

    QString getBricklinkConsumerSecret() const;
    void setBricklinkConsumerSecret(const QString &bricklink_consumer_secret);
    bool is_bricklink_consumer_secret_Set() const;
    bool is_bricklink_consumer_secret_Valid() const;

    QString getBricklinkToken() const;
    void setBricklinkToken(const QString &bricklink_token);
    bool is_bricklink_token_Set() const;
    bool is_bricklink_token_Valid() const;

    QString getBricklinkTokenSecret() const;
    void setBricklinkTokenSecret(const QString &bricklink_token_secret);
    bool is_bricklink_token_secret_Set() const;
    bool is_bricklink_token_secret_Valid() const;

    QString getDemandwareClientId() const;
    void setDemandwareClientId(const QString &demandware_client_id);
    bool is_demandware_client_id_Set() const;
    bool is_demandware_client_id_Valid() const;

    QString getDemandwareApiPassword() const;
    void setDemandwareApiPassword(const QString &demandware_api_password);
    bool is_demandware_api_password_Set() const;
    bool is_demandware_api_password_Valid() const;

    QString getDemandwareUserName() const;
    void setDemandwareUserName(const QString &demandware_user_name);
    bool is_demandware_user_name_Set() const;
    bool is_demandware_user_name_Valid() const;

    QString getDemandwareUserPassword() const;
    void setDemandwareUserPassword(const QString &demandware_user_password);
    bool is_demandware_user_password_Set() const;
    bool is_demandware_user_password_Valid() const;

    QString getEbayClientId() const;
    void setEbayClientId(const QString &ebay_client_id);
    bool is_ebay_client_id_Set() const;
    bool is_ebay_client_id_Valid() const;

    QString getEbayClientSecret() const;
    void setEbayClientSecret(const QString &ebay_client_secret);
    bool is_ebay_client_secret_Set() const;
    bool is_ebay_client_secret_Valid() const;

    QString getEbayRuname() const;
    void setEbayRuname(const QString &ebay_runame);
    bool is_ebay_runame_Set() const;
    bool is_ebay_runame_Valid() const;

    QString getEbayAccessToken() const;
    void setEbayAccessToken(const QString &ebay_access_token);
    bool is_ebay_access_token_Set() const;
    bool is_ebay_access_token_Valid() const;

    QString getEbayRefreshToken() const;
    void setEbayRefreshToken(const QString &ebay_refresh_token);
    bool is_ebay_refresh_token_Set() const;
    bool is_ebay_refresh_token_Valid() const;

    QString getEbayEnvironment() const;
    void setEbayEnvironment(const QString &ebay_environment);
    bool is_ebay_environment_Set() const;
    bool is_ebay_environment_Valid() const;

    qint32 getEbaySiteId() const;
    void setEbaySiteId(const qint32 &ebay_site_id);
    bool is_ebay_site_id_Set() const;
    bool is_ebay_site_id_Valid() const;

    QString getWalmartClientId() const;
    void setWalmartClientId(const QString &walmart_client_id);
    bool is_walmart_client_id_Set() const;
    bool is_walmart_client_id_Valid() const;

    QString getWalmartClientSecret() const;
    void setWalmartClientSecret(const QString &walmart_client_secret);
    bool is_walmart_client_secret_Set() const;
    bool is_walmart_client_secret_Valid() const;

    QString getWalmartEnvironment() const;
    void setWalmartEnvironment(const QString &walmart_environment);
    bool is_walmart_environment_Set() const;
    bool is_walmart_environment_Valid() const;

    QString getWalmartChannelType() const;
    void setWalmartChannelType(const QString &walmart_channel_type);
    bool is_walmart_channel_type_Set() const;
    bool is_walmart_channel_type_Valid() const;

    QString getWalmartRegion() const;
    void setWalmartRegion(const QString &walmart_region);
    bool is_walmart_region_Set() const;
    bool is_walmart_region_Valid() const;

    QString getEcwidAcessToken() const;
    void setEcwidAcessToken(const QString &ecwid_acess_token);
    bool is_ecwid_acess_token_Set() const;
    bool is_ecwid_acess_token_Valid() const;

    QString getEcwidStoreId() const;
    void setEcwidStoreId(const QString &ecwid_store_id);
    bool is_ecwid_store_id_Set() const;
    bool is_ecwid_store_id_Valid() const;

    QString getLazadaAppId() const;
    void setLazadaAppId(const QString &lazada_app_id);
    bool is_lazada_app_id_Set() const;
    bool is_lazada_app_id_Valid() const;

    QString getLazadaAppSecret() const;
    void setLazadaAppSecret(const QString &lazada_app_secret);
    bool is_lazada_app_secret_Set() const;
    bool is_lazada_app_secret_Valid() const;

    QString getLazadaRefreshToken() const;
    void setLazadaRefreshToken(const QString &lazada_refresh_token);
    bool is_lazada_refresh_token_Set() const;
    bool is_lazada_refresh_token_Valid() const;

    QString getLazadaRegion() const;
    void setLazadaRegion(const QString &lazada_region);
    bool is_lazada_region_Set() const;
    bool is_lazada_region_Valid() const;

    QString getLightspeedApiKey() const;
    void setLightspeedApiKey(const QString &lightspeed_api_key);
    bool is_lightspeed_api_key_Set() const;
    bool is_lightspeed_api_key_Valid() const;

    QString getLightspeedApiSecret() const;
    void setLightspeedApiSecret(const QString &lightspeed_api_secret);
    bool is_lightspeed_api_secret_Set() const;
    bool is_lightspeed_api_secret_Valid() const;

    QString getEtsyKeystring() const;
    void setEtsyKeystring(const QString &etsy_keystring);
    bool is_etsy_keystring_Set() const;
    bool is_etsy_keystring_Valid() const;

    QString getEtsySharedSecret() const;
    void setEtsySharedSecret(const QString &etsy_shared_secret);
    bool is_etsy_shared_secret_Set() const;
    bool is_etsy_shared_secret_Valid() const;

    QString getEtsyAccessToken() const;
    void setEtsyAccessToken(const QString &etsy_access_token);
    bool is_etsy_access_token_Set() const;
    bool is_etsy_access_token_Valid() const;

    QString getEtsyTokenSecret() const;
    void setEtsyTokenSecret(const QString &etsy_token_secret);
    bool is_etsy_token_secret_Set() const;
    bool is_etsy_token_secret_Valid() const;

    QString getEtsyClientId() const;
    void setEtsyClientId(const QString &etsy_client_id);
    bool is_etsy_client_id_Set() const;
    bool is_etsy_client_id_Valid() const;

    QString getEtsyRefreshToken() const;
    void setEtsyRefreshToken(const QString &etsy_refresh_token);
    bool is_etsy_refresh_token_Set() const;
    bool is_etsy_refresh_token_Valid() const;

    QString getFacebookAppId() const;
    void setFacebookAppId(const QString &facebook_app_id);
    bool is_facebook_app_id_Set() const;
    bool is_facebook_app_id_Valid() const;

    QString getFacebookAppSecret() const;
    void setFacebookAppSecret(const QString &facebook_app_secret);
    bool is_facebook_app_secret_Set() const;
    bool is_facebook_app_secret_Valid() const;

    QString getFacebookAccessToken() const;
    void setFacebookAccessToken(const QString &facebook_access_token);
    bool is_facebook_access_token_Set() const;
    bool is_facebook_access_token_Valid() const;

    QString getFacebookBusinessId() const;
    void setFacebookBusinessId(const QString &facebook_business_id);
    bool is_facebook_business_id_Set() const;
    bool is_facebook_business_id_Valid() const;

    QString getNetoApiKey() const;
    void setNetoApiKey(const QString &neto_api_key);
    bool is_neto_api_key_Set() const;
    bool is_neto_api_key_Valid() const;

    QString getNetoApiUsername() const;
    void setNetoApiUsername(const QString &neto_api_username);
    bool is_neto_api_username_Set() const;
    bool is_neto_api_username_Valid() const;

    QString getShoplineAccessToken() const;
    void setShoplineAccessToken(const QString &shopline_access_token);
    bool is_shopline_access_token_Set() const;
    bool is_shopline_access_token_Valid() const;

    QString getShoplineAppKey() const;
    void setShoplineAppKey(const QString &shopline_app_key);
    bool is_shopline_app_key_Set() const;
    bool is_shopline_app_key_Valid() const;

    QString getShoplineAppSecret() const;
    void setShoplineAppSecret(const QString &shopline_app_secret);
    bool is_shopline_app_secret_Set() const;
    bool is_shopline_app_secret_Valid() const;

    QString getShoplineSharedSecret() const;
    void setShoplineSharedSecret(const QString &shopline_shared_secret);
    bool is_shopline_shared_secret_Set() const;
    bool is_shopline_shared_secret_Valid() const;

    QString getShopifyAccessToken() const;
    void setShopifyAccessToken(const QString &shopify_access_token);
    bool is_shopify_access_token_Set() const;
    bool is_shopify_access_token_Valid() const;

    QString getShopifyApiKey() const;
    void setShopifyApiKey(const QString &shopify_api_key);
    bool is_shopify_api_key_Set() const;
    bool is_shopify_api_key_Valid() const;

    QString getShopifyApiPassword() const;
    void setShopifyApiPassword(const QString &shopify_api_password);
    bool is_shopify_api_password_Set() const;
    bool is_shopify_api_password_Valid() const;

    QString getShopifySharedSecret() const;
    void setShopifySharedSecret(const QString &shopify_shared_secret);
    bool is_shopify_shared_secret_Set() const;
    bool is_shopify_shared_secret_Valid() const;

    QString getShopeePartnerId() const;
    void setShopeePartnerId(const QString &shopee_partner_id);
    bool is_shopee_partner_id_Set() const;
    bool is_shopee_partner_id_Valid() const;

    QString getShopeePartnerKey() const;
    void setShopeePartnerKey(const QString &shopee_partner_key);
    bool is_shopee_partner_key_Set() const;
    bool is_shopee_partner_key_Valid() const;

    QString getShopeeShopId() const;
    void setShopeeShopId(const QString &shopee_shop_id);
    bool is_shopee_shop_id_Set() const;
    bool is_shopee_shop_id_Valid() const;

    QString getShopeeRefreshToken() const;
    void setShopeeRefreshToken(const QString &shopee_refresh_token);
    bool is_shopee_refresh_token_Set() const;
    bool is_shopee_refresh_token_Valid() const;

    QString getShopeeRegion() const;
    void setShopeeRegion(const QString &shopee_region);
    bool is_shopee_region_Set() const;
    bool is_shopee_region_Valid() const;

    QString getShopeeEnvironment() const;
    void setShopeeEnvironment(const QString &shopee_environment);
    bool is_shopee_environment_Set() const;
    bool is_shopee_environment_Valid() const;

    QString getShoplazzaAccessToken() const;
    void setShoplazzaAccessToken(const QString &shoplazza_access_token);
    bool is_shoplazza_access_token_Set() const;
    bool is_shoplazza_access_token_Valid() const;

    QString getShoplazzaSharedSecret() const;
    void setShoplazzaSharedSecret(const QString &shoplazza_shared_secret);
    bool is_shoplazza_shared_secret_Set() const;
    bool is_shoplazza_shared_secret_Valid() const;

    QString getShopwareAccessKey() const;
    void setShopwareAccessKey(const QString &shopware_access_key);
    bool is_shopware_access_key_Set() const;
    bool is_shopware_access_key_Valid() const;

    QString getUnasApiKey() const;
    void setUnasApiKey(const QString &unas_api_key);
    bool is_unas_api_key_Set() const;
    bool is_unas_api_key_Valid() const;

    QString getShopwareApiKey() const;
    void setShopwareApiKey(const QString &shopware_api_key);
    bool is_shopware_api_key_Set() const;
    bool is_shopware_api_key_Valid() const;

    QString getShopwareApiSecret() const;
    void setShopwareApiSecret(const QString &shopware_api_secret);
    bool is_shopware_api_secret_Set() const;
    bool is_shopware_api_secret_Valid() const;

    QString getMivaAccessToken() const;
    void setMivaAccessToken(const QString &miva_access_token);
    bool is_miva_access_token_Set() const;
    bool is_miva_access_token_Valid() const;

    QString getMivaSignature() const;
    void setMivaSignature(const QString &miva_signature);
    bool is_miva_signature_Set() const;
    bool is_miva_signature_Valid() const;

    qint32 getTiendanubeUserId() const;
    void setTiendanubeUserId(const qint32 &tiendanube_user_id);
    bool is_tiendanube_user_id_Set() const;
    bool is_tiendanube_user_id_Valid() const;

    QString getTiendanubeAccessToken() const;
    void setTiendanubeAccessToken(const QString &tiendanube_access_token);
    bool is_tiendanube_access_token_Set() const;
    bool is_tiendanube_access_token_Valid() const;

    QString getTiendanubeClientSecret() const;
    void setTiendanubeClientSecret(const QString &tiendanube_client_secret);
    bool is_tiendanube_client_secret_Set() const;
    bool is_tiendanube_client_secret_Valid() const;

    QString getVolusionLogin() const;
    void setVolusionLogin(const QString &volusion_login);
    bool is_volusion_login_Set() const;
    bool is_volusion_login_Valid() const;

    QString getVolusionPassword() const;
    void setVolusionPassword(const QString &volusion_password);
    bool is_volusion_password_Set() const;
    bool is_volusion_password_Valid() const;

    QString getHybrisClientId() const;
    void setHybrisClientId(const QString &hybris_client_id);
    bool is_hybris_client_id_Set() const;
    bool is_hybris_client_id_Valid() const;

    QString getHybrisClientSecret() const;
    void setHybrisClientSecret(const QString &hybris_client_secret);
    bool is_hybris_client_secret_Set() const;
    bool is_hybris_client_secret_Valid() const;

    QString getHybrisUsername() const;
    void setHybrisUsername(const QString &hybris_username);
    bool is_hybris_username_Set() const;
    bool is_hybris_username_Valid() const;

    QString getHybrisPassword() const;
    void setHybrisPassword(const QString &hybris_password);
    bool is_hybris_password_Set() const;
    bool is_hybris_password_Valid() const;

    QList<OAIAccountCartAdd_hybris_websites_inner> getHybrisWebsites() const;
    void setHybrisWebsites(const QList<OAIAccountCartAdd_hybris_websites_inner> &hybris_websites);
    bool is_hybris_websites_Set() const;
    bool is_hybris_websites_Valid() const;

    QString getSquareClientId() const;
    void setSquareClientId(const QString &square_client_id);
    bool is_square_client_id_Set() const;
    bool is_square_client_id_Valid() const;

    QString getSquareClientSecret() const;
    void setSquareClientSecret(const QString &square_client_secret);
    bool is_square_client_secret_Set() const;
    bool is_square_client_secret_Valid() const;

    QString getSquareRefreshToken() const;
    void setSquareRefreshToken(const QString &square_refresh_token);
    bool is_square_refresh_token_Set() const;
    bool is_square_refresh_token_Valid() const;

    QString getSquarespaceApiKey() const;
    void setSquarespaceApiKey(const QString &squarespace_api_key);
    bool is_squarespace_api_key_Set() const;
    bool is_squarespace_api_key_Valid() const;

    QString getSquarespaceClientId() const;
    void setSquarespaceClientId(const QString &squarespace_client_id);
    bool is_squarespace_client_id_Set() const;
    bool is_squarespace_client_id_Valid() const;

    QString getSquarespaceClientSecret() const;
    void setSquarespaceClientSecret(const QString &squarespace_client_secret);
    bool is_squarespace_client_secret_Set() const;
    bool is_squarespace_client_secret_Valid() const;

    QString getSquarespaceAccessToken() const;
    void setSquarespaceAccessToken(const QString &squarespace_access_token);
    bool is_squarespace_access_token_Set() const;
    bool is_squarespace_access_token_Valid() const;

    QString getSquarespaceRefreshToken() const;
    void setSquarespaceRefreshToken(const QString &squarespace_refresh_token);
    bool is_squarespace_refresh_token_Set() const;
    bool is_squarespace_refresh_token_Valid() const;

    QString getCommercehqApiKey() const;
    void setCommercehqApiKey(const QString &commercehq_api_key);
    bool is_commercehq_api_key_Set() const;
    bool is_commercehq_api_key_Valid() const;

    QString getCommercehqApiPassword() const;
    void setCommercehqApiPassword(const QString &commercehq_api_password);
    bool is_commercehq_api_password_Set() const;
    bool is_commercehq_api_password_Valid() const;

    QString getWcConsumerKey() const;
    void setWcConsumerKey(const QString &wc_consumer_key);
    bool is_wc_consumer_key_Set() const;
    bool is_wc_consumer_key_Valid() const;

    QString getWcConsumerSecret() const;
    void setWcConsumerSecret(const QString &wc_consumer_secret);
    bool is_wc_consumer_secret_Set() const;
    bool is_wc_consumer_secret_Valid() const;

    QString getMagentoConsumerKey() const;
    void setMagentoConsumerKey(const QString &magento_consumer_key);
    bool is_magento_consumer_key_Set() const;
    bool is_magento_consumer_key_Valid() const;

    QString getMagentoConsumerSecret() const;
    void setMagentoConsumerSecret(const QString &magento_consumer_secret);
    bool is_magento_consumer_secret_Set() const;
    bool is_magento_consumer_secret_Valid() const;

    QString getMagentoAccessToken() const;
    void setMagentoAccessToken(const QString &magento_access_token);
    bool is_magento_access_token_Set() const;
    bool is_magento_access_token_Valid() const;

    QString getMagentoTokenSecret() const;
    void setMagentoTokenSecret(const QString &magento_token_secret);
    bool is_magento_token_secret_Set() const;
    bool is_magento_token_secret_Valid() const;

    QString getPrestashopWebserviceKey() const;
    void setPrestashopWebserviceKey(const QString &prestashop_webservice_key);
    bool is_prestashop_webservice_key_Set() const;
    bool is_prestashop_webservice_key_Valid() const;

    QString getWixAppId() const;
    void setWixAppId(const QString &wix_app_id);
    bool is_wix_app_id_Set() const;
    bool is_wix_app_id_Valid() const;

    QString getWixAppSecretKey() const;
    void setWixAppSecretKey(const QString &wix_app_secret_key);
    bool is_wix_app_secret_key_Set() const;
    bool is_wix_app_secret_key_Valid() const;

    QString getWixInstanceId() const;
    void setWixInstanceId(const QString &wix_instance_id);
    bool is_wix_instance_id_Set() const;
    bool is_wix_instance_id_Valid() const;

    QString getWixRefreshToken() const;
    void setWixRefreshToken(const QString &wix_refresh_token);
    bool is_wix_refresh_token_Set() const;
    bool is_wix_refresh_token_Valid() const;

    QString getMercadoLibreAppId() const;
    void setMercadoLibreAppId(const QString &mercado_libre_app_id);
    bool is_mercado_libre_app_id_Set() const;
    bool is_mercado_libre_app_id_Valid() const;

    QString getMercadoLibreAppSecretKey() const;
    void setMercadoLibreAppSecretKey(const QString &mercado_libre_app_secret_key);
    bool is_mercado_libre_app_secret_key_Set() const;
    bool is_mercado_libre_app_secret_key_Valid() const;

    QString getMercadoLibreRefreshToken() const;
    void setMercadoLibreRefreshToken(const QString &mercado_libre_refresh_token);
    bool is_mercado_libre_refresh_token_Set() const;
    bool is_mercado_libre_refresh_token_Valid() const;

    qint32 getZidClientId() const;
    void setZidClientId(const qint32 &zid_client_id);
    bool is_zid_client_id_Set() const;
    bool is_zid_client_id_Valid() const;

    QString getZidClientSecret() const;
    void setZidClientSecret(const QString &zid_client_secret);
    bool is_zid_client_secret_Set() const;
    bool is_zid_client_secret_Valid() const;

    QString getZidAccessToken() const;
    void setZidAccessToken(const QString &zid_access_token);
    bool is_zid_access_token_Set() const;
    bool is_zid_access_token_Valid() const;

    QString getZidAuthorization() const;
    void setZidAuthorization(const QString &zid_authorization);
    bool is_zid_authorization_Set() const;
    bool is_zid_authorization_Valid() const;

    QString getZidRefreshToken() const;
    void setZidRefreshToken(const QString &zid_refresh_token);
    bool is_zid_refresh_token_Set() const;
    bool is_zid_refresh_token_Valid() const;

    QString getFlipkartClientId() const;
    void setFlipkartClientId(const QString &flipkart_client_id);
    bool is_flipkart_client_id_Set() const;
    bool is_flipkart_client_id_Valid() const;

    QString getFlipkartClientSecret() const;
    void setFlipkartClientSecret(const QString &flipkart_client_secret);
    bool is_flipkart_client_secret_Set() const;
    bool is_flipkart_client_secret_Valid() const;

    QString getAllegroClientId() const;
    void setAllegroClientId(const QString &allegro_client_id);
    bool is_allegro_client_id_Set() const;
    bool is_allegro_client_id_Valid() const;

    QString getAllegroClientSecret() const;
    void setAllegroClientSecret(const QString &allegro_client_secret);
    bool is_allegro_client_secret_Set() const;
    bool is_allegro_client_secret_Valid() const;

    QString getAllegroAccessToken() const;
    void setAllegroAccessToken(const QString &allegro_access_token);
    bool is_allegro_access_token_Set() const;
    bool is_allegro_access_token_Valid() const;

    QString getAllegroRefreshToken() const;
    void setAllegroRefreshToken(const QString &allegro_refresh_token);
    bool is_allegro_refresh_token_Set() const;
    bool is_allegro_refresh_token_Valid() const;

    QString getAllegroEnvironment() const;
    void setAllegroEnvironment(const QString &allegro_environment);
    bool is_allegro_environment_Set() const;
    bool is_allegro_environment_Valid() const;

    QString getZohoClientId() const;
    void setZohoClientId(const QString &zoho_client_id);
    bool is_zoho_client_id_Set() const;
    bool is_zoho_client_id_Valid() const;

    QString getZohoClientSecret() const;
    void setZohoClientSecret(const QString &zoho_client_secret);
    bool is_zoho_client_secret_Set() const;
    bool is_zoho_client_secret_Valid() const;

    QString getZohoRefreshToken() const;
    void setZohoRefreshToken(const QString &zoho_refresh_token);
    bool is_zoho_refresh_token_Set() const;
    bool is_zoho_refresh_token_Valid() const;

    QString getZohoRegion() const;
    void setZohoRegion(const QString &zoho_region);
    bool is_zoho_region_Set() const;
    bool is_zoho_region_Valid() const;

    QString getOttoClientId() const;
    void setOttoClientId(const QString &otto_client_id);
    bool is_otto_client_id_Set() const;
    bool is_otto_client_id_Valid() const;

    QString getOttoClientSecret() const;
    void setOttoClientSecret(const QString &otto_client_secret);
    bool is_otto_client_secret_Set() const;
    bool is_otto_client_secret_Valid() const;

    QString getOttoAppId() const;
    void setOttoAppId(const QString &otto_app_id);
    bool is_otto_app_id_Set() const;
    bool is_otto_app_id_Valid() const;

    QString getOttoRefreshToken() const;
    void setOttoRefreshToken(const QString &otto_refresh_token);
    bool is_otto_refresh_token_Set() const;
    bool is_otto_refresh_token_Valid() const;

    QString getOttoEnvironment() const;
    void setOttoEnvironment(const QString &otto_environment);
    bool is_otto_environment_Set() const;
    bool is_otto_environment_Valid() const;

    QString getOttoAccessToken() const;
    void setOttoAccessToken(const QString &otto_access_token);
    bool is_otto_access_token_Set() const;
    bool is_otto_access_token_Valid() const;

    QString getTiktokshopAppKey() const;
    void setTiktokshopAppKey(const QString &tiktokshop_app_key);
    bool is_tiktokshop_app_key_Set() const;
    bool is_tiktokshop_app_key_Valid() const;

    QString getTiktokshopAppSecret() const;
    void setTiktokshopAppSecret(const QString &tiktokshop_app_secret);
    bool is_tiktokshop_app_secret_Set() const;
    bool is_tiktokshop_app_secret_Valid() const;

    QString getTiktokshopRefreshToken() const;
    void setTiktokshopRefreshToken(const QString &tiktokshop_refresh_token);
    bool is_tiktokshop_refresh_token_Set() const;
    bool is_tiktokshop_refresh_token_Valid() const;

    QString getTiktokshopAccessToken() const;
    void setTiktokshopAccessToken(const QString &tiktokshop_access_token);
    bool is_tiktokshop_access_token_Set() const;
    bool is_tiktokshop_access_token_Valid() const;

    QString getSallaClientId() const;
    void setSallaClientId(const QString &salla_client_id);
    bool is_salla_client_id_Set() const;
    bool is_salla_client_id_Valid() const;

    QString getSallaClientSecret() const;
    void setSallaClientSecret(const QString &salla_client_secret);
    bool is_salla_client_secret_Set() const;
    bool is_salla_client_secret_Valid() const;

    QString getSallaRefreshToken() const;
    void setSallaRefreshToken(const QString &salla_refresh_token);
    bool is_salla_refresh_token_Set() const;
    bool is_salla_refresh_token_Valid() const;

    QString getSallaAccessToken() const;
    void setSallaAccessToken(const QString &salla_access_token);
    bool is_salla_access_token_Set() const;
    bool is_salla_access_token_Valid() const;

    QString getTemuAppKey() const;
    void setTemuAppKey(const QString &temu_app_key);
    bool is_temu_app_key_Set() const;
    bool is_temu_app_key_Valid() const;

    QString getTemuAppSecret() const;
    void setTemuAppSecret(const QString &temu_app_secret);
    bool is_temu_app_secret_Set() const;
    bool is_temu_app_secret_Valid() const;

    QString getTemuAccessToken() const;
    void setTemuAccessToken(const QString &temu_access_token);
    bool is_temu_access_token_Set() const;
    bool is_temu_access_token_Valid() const;

    QString getTemuRegion() const;
    void setTemuRegion(const QString &temu_region);
    bool is_temu_region_Set() const;
    bool is_temu_region_Valid() const;

    QString getScapiClientId() const;
    void setScapiClientId(const QString &scapi_client_id);
    bool is_scapi_client_id_Set() const;
    bool is_scapi_client_id_Valid() const;

    QString getScapiClientSecret() const;
    void setScapiClientSecret(const QString &scapi_client_secret);
    bool is_scapi_client_secret_Set() const;
    bool is_scapi_client_secret_Valid() const;

    QString getScapiOrganizationId() const;
    void setScapiOrganizationId(const QString &scapi_organization_id);
    bool is_scapi_organization_id_Set() const;
    bool is_scapi_organization_id_Valid() const;

    QString getScapiShortCode() const;
    void setScapiShortCode(const QString &scapi_short_code);
    bool is_scapi_short_code_Set() const;
    bool is_scapi_short_code_Valid() const;

    QString getScapiScopes() const;
    void setScapiScopes(const QString &scapi_scopes);
    bool is_scapi_scopes_Set() const;
    bool is_scapi_scopes_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_cart_id;
    bool m_cart_id_isSet;
    bool m_cart_id_isValid;

    QString m_store_url;
    bool m_store_url_isSet;
    bool m_store_url_isValid;

    QString m_bridge_url;
    bool m_bridge_url_isSet;
    bool m_bridge_url_isValid;

    QString m_store_root;
    bool m_store_root_isSet;
    bool m_store_root_isValid;

    QString m_store_key;
    bool m_store_key_isSet;
    bool m_store_key_isValid;

    bool m_validate_version;
    bool m_validate_version_isSet;
    bool m_validate_version_isValid;

    bool m_verify;
    bool m_verify_isSet;
    bool m_verify_isValid;

    QString m_db_tables_prefix;
    bool m_db_tables_prefix_isSet;
    bool m_db_tables_prefix_isValid;

    QString m_user_agent;
    bool m_user_agent_isSet;
    bool m_user_agent_isValid;

    QString m_ftp_host;
    bool m_ftp_host_isSet;
    bool m_ftp_host_isValid;

    QString m_ftp_user;
    bool m_ftp_user_isSet;
    bool m_ftp_user_isValid;

    QString m_ftp_password;
    bool m_ftp_password_isSet;
    bool m_ftp_password_isValid;

    qint32 m_ftp_port;
    bool m_ftp_port_isSet;
    bool m_ftp_port_isValid;

    QString m_ftp_store_dir;
    bool m_ftp_store_dir_isSet;
    bool m_ftp_store_dir_isValid;

    QString m_r_3dcart_private_key;
    bool m_r_3dcart_private_key_isSet;
    bool m_r_3dcart_private_key_isValid;

    QString m_r_3dcart_access_token;
    bool m_r_3dcart_access_token_isSet;
    bool m_r_3dcart_access_token_isValid;

    QString m_r_3dcartapi_api_key;
    bool m_r_3dcartapi_api_key_isSet;
    bool m_r_3dcartapi_api_key_isValid;

    QString m_amazon_sp_client_id;
    bool m_amazon_sp_client_id_isSet;
    bool m_amazon_sp_client_id_isValid;

    QString m_amazon_sp_client_secret;
    bool m_amazon_sp_client_secret_isSet;
    bool m_amazon_sp_client_secret_isValid;

    QString m_amazon_sp_refresh_token;
    bool m_amazon_sp_refresh_token_isSet;
    bool m_amazon_sp_refresh_token_isValid;

    QString m_amazon_sp_aws_region;
    bool m_amazon_sp_aws_region_isSet;
    bool m_amazon_sp_aws_region_isValid;

    QString m_amazon_sp_api_environment;
    bool m_amazon_sp_api_environment_isSet;
    bool m_amazon_sp_api_environment_isValid;

    QString m_amazon_seller_id;
    bool m_amazon_seller_id_isSet;
    bool m_amazon_seller_id_isValid;

    QString m_aspdotnetstorefront_api_user;
    bool m_aspdotnetstorefront_api_user_isSet;
    bool m_aspdotnetstorefront_api_user_isValid;

    QString m_aspdotnetstorefront_api_pass;
    bool m_aspdotnetstorefront_api_pass_isSet;
    bool m_aspdotnetstorefront_api_pass_isValid;

    QString m_americommerce_app_id;
    bool m_americommerce_app_id_isSet;
    bool m_americommerce_app_id_isValid;

    QString m_americommerce_app_secret;
    bool m_americommerce_app_secret_isSet;
    bool m_americommerce_app_secret_isValid;

    QString m_americommerce_access_token;
    bool m_americommerce_access_token_isSet;
    bool m_americommerce_access_token_isValid;

    QString m_americommerce_refresh_token;
    bool m_americommerce_refresh_token_isSet;
    bool m_americommerce_refresh_token_isValid;

    QString m_bigcommerceapi_admin_account;
    bool m_bigcommerceapi_admin_account_isSet;
    bool m_bigcommerceapi_admin_account_isValid;

    QString m_bigcommerceapi_api_path;
    bool m_bigcommerceapi_api_path_isSet;
    bool m_bigcommerceapi_api_path_isValid;

    QString m_bigcommerceapi_api_key;
    bool m_bigcommerceapi_api_key_isSet;
    bool m_bigcommerceapi_api_key_isValid;

    QString m_bigcommerceapi_client_id;
    bool m_bigcommerceapi_client_id_isSet;
    bool m_bigcommerceapi_client_id_isValid;

    QString m_bigcommerceapi_access_token;
    bool m_bigcommerceapi_access_token_isSet;
    bool m_bigcommerceapi_access_token_isValid;

    QString m_bigcommerceapi_context;
    bool m_bigcommerceapi_context_isSet;
    bool m_bigcommerceapi_context_isValid;

    QString m_bol_api_key;
    bool m_bol_api_key_isSet;
    bool m_bol_api_key_isValid;

    QString m_bol_api_secret;
    bool m_bol_api_secret_isSet;
    bool m_bol_api_secret_isValid;

    qint32 m_bol_retailer_id;
    bool m_bol_retailer_id_isSet;
    bool m_bol_retailer_id_isValid;

    QString m_bigcartel_user_name;
    bool m_bigcartel_user_name_isSet;
    bool m_bigcartel_user_name_isValid;

    QString m_bigcartel_password;
    bool m_bigcartel_password_isSet;
    bool m_bigcartel_password_isValid;

    QString m_bricklink_consumer_key;
    bool m_bricklink_consumer_key_isSet;
    bool m_bricklink_consumer_key_isValid;

    QString m_bricklink_consumer_secret;
    bool m_bricklink_consumer_secret_isSet;
    bool m_bricklink_consumer_secret_isValid;

    QString m_bricklink_token;
    bool m_bricklink_token_isSet;
    bool m_bricklink_token_isValid;

    QString m_bricklink_token_secret;
    bool m_bricklink_token_secret_isSet;
    bool m_bricklink_token_secret_isValid;

    QString m_demandware_client_id;
    bool m_demandware_client_id_isSet;
    bool m_demandware_client_id_isValid;

    QString m_demandware_api_password;
    bool m_demandware_api_password_isSet;
    bool m_demandware_api_password_isValid;

    QString m_demandware_user_name;
    bool m_demandware_user_name_isSet;
    bool m_demandware_user_name_isValid;

    QString m_demandware_user_password;
    bool m_demandware_user_password_isSet;
    bool m_demandware_user_password_isValid;

    QString m_ebay_client_id;
    bool m_ebay_client_id_isSet;
    bool m_ebay_client_id_isValid;

    QString m_ebay_client_secret;
    bool m_ebay_client_secret_isSet;
    bool m_ebay_client_secret_isValid;

    QString m_ebay_runame;
    bool m_ebay_runame_isSet;
    bool m_ebay_runame_isValid;

    QString m_ebay_access_token;
    bool m_ebay_access_token_isSet;
    bool m_ebay_access_token_isValid;

    QString m_ebay_refresh_token;
    bool m_ebay_refresh_token_isSet;
    bool m_ebay_refresh_token_isValid;

    QString m_ebay_environment;
    bool m_ebay_environment_isSet;
    bool m_ebay_environment_isValid;

    qint32 m_ebay_site_id;
    bool m_ebay_site_id_isSet;
    bool m_ebay_site_id_isValid;

    QString m_walmart_client_id;
    bool m_walmart_client_id_isSet;
    bool m_walmart_client_id_isValid;

    QString m_walmart_client_secret;
    bool m_walmart_client_secret_isSet;
    bool m_walmart_client_secret_isValid;

    QString m_walmart_environment;
    bool m_walmart_environment_isSet;
    bool m_walmart_environment_isValid;

    QString m_walmart_channel_type;
    bool m_walmart_channel_type_isSet;
    bool m_walmart_channel_type_isValid;

    QString m_walmart_region;
    bool m_walmart_region_isSet;
    bool m_walmart_region_isValid;

    QString m_ecwid_acess_token;
    bool m_ecwid_acess_token_isSet;
    bool m_ecwid_acess_token_isValid;

    QString m_ecwid_store_id;
    bool m_ecwid_store_id_isSet;
    bool m_ecwid_store_id_isValid;

    QString m_lazada_app_id;
    bool m_lazada_app_id_isSet;
    bool m_lazada_app_id_isValid;

    QString m_lazada_app_secret;
    bool m_lazada_app_secret_isSet;
    bool m_lazada_app_secret_isValid;

    QString m_lazada_refresh_token;
    bool m_lazada_refresh_token_isSet;
    bool m_lazada_refresh_token_isValid;

    QString m_lazada_region;
    bool m_lazada_region_isSet;
    bool m_lazada_region_isValid;

    QString m_lightspeed_api_key;
    bool m_lightspeed_api_key_isSet;
    bool m_lightspeed_api_key_isValid;

    QString m_lightspeed_api_secret;
    bool m_lightspeed_api_secret_isSet;
    bool m_lightspeed_api_secret_isValid;

    QString m_etsy_keystring;
    bool m_etsy_keystring_isSet;
    bool m_etsy_keystring_isValid;

    QString m_etsy_shared_secret;
    bool m_etsy_shared_secret_isSet;
    bool m_etsy_shared_secret_isValid;

    QString m_etsy_access_token;
    bool m_etsy_access_token_isSet;
    bool m_etsy_access_token_isValid;

    QString m_etsy_token_secret;
    bool m_etsy_token_secret_isSet;
    bool m_etsy_token_secret_isValid;

    QString m_etsy_client_id;
    bool m_etsy_client_id_isSet;
    bool m_etsy_client_id_isValid;

    QString m_etsy_refresh_token;
    bool m_etsy_refresh_token_isSet;
    bool m_etsy_refresh_token_isValid;

    QString m_facebook_app_id;
    bool m_facebook_app_id_isSet;
    bool m_facebook_app_id_isValid;

    QString m_facebook_app_secret;
    bool m_facebook_app_secret_isSet;
    bool m_facebook_app_secret_isValid;

    QString m_facebook_access_token;
    bool m_facebook_access_token_isSet;
    bool m_facebook_access_token_isValid;

    QString m_facebook_business_id;
    bool m_facebook_business_id_isSet;
    bool m_facebook_business_id_isValid;

    QString m_neto_api_key;
    bool m_neto_api_key_isSet;
    bool m_neto_api_key_isValid;

    QString m_neto_api_username;
    bool m_neto_api_username_isSet;
    bool m_neto_api_username_isValid;

    QString m_shopline_access_token;
    bool m_shopline_access_token_isSet;
    bool m_shopline_access_token_isValid;

    QString m_shopline_app_key;
    bool m_shopline_app_key_isSet;
    bool m_shopline_app_key_isValid;

    QString m_shopline_app_secret;
    bool m_shopline_app_secret_isSet;
    bool m_shopline_app_secret_isValid;

    QString m_shopline_shared_secret;
    bool m_shopline_shared_secret_isSet;
    bool m_shopline_shared_secret_isValid;

    QString m_shopify_access_token;
    bool m_shopify_access_token_isSet;
    bool m_shopify_access_token_isValid;

    QString m_shopify_api_key;
    bool m_shopify_api_key_isSet;
    bool m_shopify_api_key_isValid;

    QString m_shopify_api_password;
    bool m_shopify_api_password_isSet;
    bool m_shopify_api_password_isValid;

    QString m_shopify_shared_secret;
    bool m_shopify_shared_secret_isSet;
    bool m_shopify_shared_secret_isValid;

    QString m_shopee_partner_id;
    bool m_shopee_partner_id_isSet;
    bool m_shopee_partner_id_isValid;

    QString m_shopee_partner_key;
    bool m_shopee_partner_key_isSet;
    bool m_shopee_partner_key_isValid;

    QString m_shopee_shop_id;
    bool m_shopee_shop_id_isSet;
    bool m_shopee_shop_id_isValid;

    QString m_shopee_refresh_token;
    bool m_shopee_refresh_token_isSet;
    bool m_shopee_refresh_token_isValid;

    QString m_shopee_region;
    bool m_shopee_region_isSet;
    bool m_shopee_region_isValid;

    QString m_shopee_environment;
    bool m_shopee_environment_isSet;
    bool m_shopee_environment_isValid;

    QString m_shoplazza_access_token;
    bool m_shoplazza_access_token_isSet;
    bool m_shoplazza_access_token_isValid;

    QString m_shoplazza_shared_secret;
    bool m_shoplazza_shared_secret_isSet;
    bool m_shoplazza_shared_secret_isValid;

    QString m_shopware_access_key;
    bool m_shopware_access_key_isSet;
    bool m_shopware_access_key_isValid;

    QString m_unas_api_key;
    bool m_unas_api_key_isSet;
    bool m_unas_api_key_isValid;

    QString m_shopware_api_key;
    bool m_shopware_api_key_isSet;
    bool m_shopware_api_key_isValid;

    QString m_shopware_api_secret;
    bool m_shopware_api_secret_isSet;
    bool m_shopware_api_secret_isValid;

    QString m_miva_access_token;
    bool m_miva_access_token_isSet;
    bool m_miva_access_token_isValid;

    QString m_miva_signature;
    bool m_miva_signature_isSet;
    bool m_miva_signature_isValid;

    qint32 m_tiendanube_user_id;
    bool m_tiendanube_user_id_isSet;
    bool m_tiendanube_user_id_isValid;

    QString m_tiendanube_access_token;
    bool m_tiendanube_access_token_isSet;
    bool m_tiendanube_access_token_isValid;

    QString m_tiendanube_client_secret;
    bool m_tiendanube_client_secret_isSet;
    bool m_tiendanube_client_secret_isValid;

    QString m_volusion_login;
    bool m_volusion_login_isSet;
    bool m_volusion_login_isValid;

    QString m_volusion_password;
    bool m_volusion_password_isSet;
    bool m_volusion_password_isValid;

    QString m_hybris_client_id;
    bool m_hybris_client_id_isSet;
    bool m_hybris_client_id_isValid;

    QString m_hybris_client_secret;
    bool m_hybris_client_secret_isSet;
    bool m_hybris_client_secret_isValid;

    QString m_hybris_username;
    bool m_hybris_username_isSet;
    bool m_hybris_username_isValid;

    QString m_hybris_password;
    bool m_hybris_password_isSet;
    bool m_hybris_password_isValid;

    QList<OAIAccountCartAdd_hybris_websites_inner> m_hybris_websites;
    bool m_hybris_websites_isSet;
    bool m_hybris_websites_isValid;

    QString m_square_client_id;
    bool m_square_client_id_isSet;
    bool m_square_client_id_isValid;

    QString m_square_client_secret;
    bool m_square_client_secret_isSet;
    bool m_square_client_secret_isValid;

    QString m_square_refresh_token;
    bool m_square_refresh_token_isSet;
    bool m_square_refresh_token_isValid;

    QString m_squarespace_api_key;
    bool m_squarespace_api_key_isSet;
    bool m_squarespace_api_key_isValid;

    QString m_squarespace_client_id;
    bool m_squarespace_client_id_isSet;
    bool m_squarespace_client_id_isValid;

    QString m_squarespace_client_secret;
    bool m_squarespace_client_secret_isSet;
    bool m_squarespace_client_secret_isValid;

    QString m_squarespace_access_token;
    bool m_squarespace_access_token_isSet;
    bool m_squarespace_access_token_isValid;

    QString m_squarespace_refresh_token;
    bool m_squarespace_refresh_token_isSet;
    bool m_squarespace_refresh_token_isValid;

    QString m_commercehq_api_key;
    bool m_commercehq_api_key_isSet;
    bool m_commercehq_api_key_isValid;

    QString m_commercehq_api_password;
    bool m_commercehq_api_password_isSet;
    bool m_commercehq_api_password_isValid;

    QString m_wc_consumer_key;
    bool m_wc_consumer_key_isSet;
    bool m_wc_consumer_key_isValid;

    QString m_wc_consumer_secret;
    bool m_wc_consumer_secret_isSet;
    bool m_wc_consumer_secret_isValid;

    QString m_magento_consumer_key;
    bool m_magento_consumer_key_isSet;
    bool m_magento_consumer_key_isValid;

    QString m_magento_consumer_secret;
    bool m_magento_consumer_secret_isSet;
    bool m_magento_consumer_secret_isValid;

    QString m_magento_access_token;
    bool m_magento_access_token_isSet;
    bool m_magento_access_token_isValid;

    QString m_magento_token_secret;
    bool m_magento_token_secret_isSet;
    bool m_magento_token_secret_isValid;

    QString m_prestashop_webservice_key;
    bool m_prestashop_webservice_key_isSet;
    bool m_prestashop_webservice_key_isValid;

    QString m_wix_app_id;
    bool m_wix_app_id_isSet;
    bool m_wix_app_id_isValid;

    QString m_wix_app_secret_key;
    bool m_wix_app_secret_key_isSet;
    bool m_wix_app_secret_key_isValid;

    QString m_wix_instance_id;
    bool m_wix_instance_id_isSet;
    bool m_wix_instance_id_isValid;

    QString m_wix_refresh_token;
    bool m_wix_refresh_token_isSet;
    bool m_wix_refresh_token_isValid;

    QString m_mercado_libre_app_id;
    bool m_mercado_libre_app_id_isSet;
    bool m_mercado_libre_app_id_isValid;

    QString m_mercado_libre_app_secret_key;
    bool m_mercado_libre_app_secret_key_isSet;
    bool m_mercado_libre_app_secret_key_isValid;

    QString m_mercado_libre_refresh_token;
    bool m_mercado_libre_refresh_token_isSet;
    bool m_mercado_libre_refresh_token_isValid;

    qint32 m_zid_client_id;
    bool m_zid_client_id_isSet;
    bool m_zid_client_id_isValid;

    QString m_zid_client_secret;
    bool m_zid_client_secret_isSet;
    bool m_zid_client_secret_isValid;

    QString m_zid_access_token;
    bool m_zid_access_token_isSet;
    bool m_zid_access_token_isValid;

    QString m_zid_authorization;
    bool m_zid_authorization_isSet;
    bool m_zid_authorization_isValid;

    QString m_zid_refresh_token;
    bool m_zid_refresh_token_isSet;
    bool m_zid_refresh_token_isValid;

    QString m_flipkart_client_id;
    bool m_flipkart_client_id_isSet;
    bool m_flipkart_client_id_isValid;

    QString m_flipkart_client_secret;
    bool m_flipkart_client_secret_isSet;
    bool m_flipkart_client_secret_isValid;

    QString m_allegro_client_id;
    bool m_allegro_client_id_isSet;
    bool m_allegro_client_id_isValid;

    QString m_allegro_client_secret;
    bool m_allegro_client_secret_isSet;
    bool m_allegro_client_secret_isValid;

    QString m_allegro_access_token;
    bool m_allegro_access_token_isSet;
    bool m_allegro_access_token_isValid;

    QString m_allegro_refresh_token;
    bool m_allegro_refresh_token_isSet;
    bool m_allegro_refresh_token_isValid;

    QString m_allegro_environment;
    bool m_allegro_environment_isSet;
    bool m_allegro_environment_isValid;

    QString m_zoho_client_id;
    bool m_zoho_client_id_isSet;
    bool m_zoho_client_id_isValid;

    QString m_zoho_client_secret;
    bool m_zoho_client_secret_isSet;
    bool m_zoho_client_secret_isValid;

    QString m_zoho_refresh_token;
    bool m_zoho_refresh_token_isSet;
    bool m_zoho_refresh_token_isValid;

    QString m_zoho_region;
    bool m_zoho_region_isSet;
    bool m_zoho_region_isValid;

    QString m_otto_client_id;
    bool m_otto_client_id_isSet;
    bool m_otto_client_id_isValid;

    QString m_otto_client_secret;
    bool m_otto_client_secret_isSet;
    bool m_otto_client_secret_isValid;

    QString m_otto_app_id;
    bool m_otto_app_id_isSet;
    bool m_otto_app_id_isValid;

    QString m_otto_refresh_token;
    bool m_otto_refresh_token_isSet;
    bool m_otto_refresh_token_isValid;

    QString m_otto_environment;
    bool m_otto_environment_isSet;
    bool m_otto_environment_isValid;

    QString m_otto_access_token;
    bool m_otto_access_token_isSet;
    bool m_otto_access_token_isValid;

    QString m_tiktokshop_app_key;
    bool m_tiktokshop_app_key_isSet;
    bool m_tiktokshop_app_key_isValid;

    QString m_tiktokshop_app_secret;
    bool m_tiktokshop_app_secret_isSet;
    bool m_tiktokshop_app_secret_isValid;

    QString m_tiktokshop_refresh_token;
    bool m_tiktokshop_refresh_token_isSet;
    bool m_tiktokshop_refresh_token_isValid;

    QString m_tiktokshop_access_token;
    bool m_tiktokshop_access_token_isSet;
    bool m_tiktokshop_access_token_isValid;

    QString m_salla_client_id;
    bool m_salla_client_id_isSet;
    bool m_salla_client_id_isValid;

    QString m_salla_client_secret;
    bool m_salla_client_secret_isSet;
    bool m_salla_client_secret_isValid;

    QString m_salla_refresh_token;
    bool m_salla_refresh_token_isSet;
    bool m_salla_refresh_token_isValid;

    QString m_salla_access_token;
    bool m_salla_access_token_isSet;
    bool m_salla_access_token_isValid;

    QString m_temu_app_key;
    bool m_temu_app_key_isSet;
    bool m_temu_app_key_isValid;

    QString m_temu_app_secret;
    bool m_temu_app_secret_isSet;
    bool m_temu_app_secret_isValid;

    QString m_temu_access_token;
    bool m_temu_access_token_isSet;
    bool m_temu_access_token_isValid;

    QString m_temu_region;
    bool m_temu_region_isSet;
    bool m_temu_region_isValid;

    QString m_scapi_client_id;
    bool m_scapi_client_id_isSet;
    bool m_scapi_client_id_isValid;

    QString m_scapi_client_secret;
    bool m_scapi_client_secret_isSet;
    bool m_scapi_client_secret_isValid;

    QString m_scapi_organization_id;
    bool m_scapi_organization_id_isSet;
    bool m_scapi_organization_id_isValid;

    QString m_scapi_short_code;
    bool m_scapi_short_code_isSet;
    bool m_scapi_short_code_isValid;

    QString m_scapi_scopes;
    bool m_scapi_scopes_isSet;
    bool m_scapi_scopes_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAccountCartAdd)

#endif // OAIAccountCartAdd_H
