/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAnalytics_Interval.h
 *
 * 
 */

#ifndef OAIAnalytics_Interval_H
#define OAIAnalytics_Interval_H

#include <QJsonObject>

#include "OAIAnalytics_Metric.h"
#include "OAIObject.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIAnalytics_Metric;

class OAIAnalytics_Interval : public OAIObject {
public:
    OAIAnalytics_Interval();
    OAIAnalytics_Interval(QString json);
    ~OAIAnalytics_Interval() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getDateFrom() const;
    void setDateFrom(const QString &date_from);
    bool is_date_from_Set() const;
    bool is_date_from_Valid() const;

    QString getDateTo() const;
    void setDateTo(const QString &date_to);
    bool is_date_to_Set() const;
    bool is_date_to_Valid() const;

    OAIAnalytics_Metric getMetrics() const;
    void setMetrics(const OAIAnalytics_Metric &metrics);
    bool is_metrics_Set() const;
    bool is_metrics_Valid() const;

    OAIObject getAdditionalFields() const;
    void setAdditionalFields(const OAIObject &additional_fields);
    bool is_additional_fields_Set() const;
    bool is_additional_fields_Valid() const;

    OAIObject getCustomFields() const;
    void setCustomFields(const OAIObject &custom_fields);
    bool is_custom_fields_Set() const;
    bool is_custom_fields_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_date_from;
    bool m_date_from_isSet;
    bool m_date_from_isValid;

    QString m_date_to;
    bool m_date_to_isSet;
    bool m_date_to_isValid;

    OAIAnalytics_Metric m_metrics;
    bool m_metrics_isSet;
    bool m_metrics_isValid;

    OAIObject m_additional_fields;
    bool m_additional_fields_isSet;
    bool m_additional_fields_isValid;

    OAIObject m_custom_fields;
    bool m_custom_fields_isSet;
    bool m_custom_fields_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAnalytics_Interval)

#endif // OAIAnalytics_Interval_H
