/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBatch_Job.h
 *
 * 
 */

#ifndef OAIBatch_Job_H
#define OAIBatch_Job_H

#include <QJsonObject>

#include "OAIA2CDateTime.h"
#include "OAIObject.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIA2CDateTime;

class OAIBatch_Job : public OAIObject {
public:
    OAIBatch_Job();
    OAIBatch_Job(QString json);
    ~OAIBatch_Job() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getMethod() const;
    void setMethod(const QString &method);
    bool is_method_Set() const;
    bool is_method_Valid() const;

    QString getStatus() const;
    void setStatus(const QString &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    OAIA2CDateTime getCreatedTime() const;
    void setCreatedTime(const OAIA2CDateTime &created_time);
    bool is_created_time_Set() const;
    bool is_created_time_Valid() const;

    OAIA2CDateTime getProcessedTime() const;
    void setProcessedTime(const OAIA2CDateTime &processed_time);
    bool is_processed_time_Set() const;
    bool is_processed_time_Valid() const;

    OAIObject getAdditionalFields() const;
    void setAdditionalFields(const OAIObject &additional_fields);
    bool is_additional_fields_Set() const;
    bool is_additional_fields_Valid() const;

    OAIObject getCustomFields() const;
    void setCustomFields(const OAIObject &custom_fields);
    bool is_custom_fields_Set() const;
    bool is_custom_fields_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString m_method;
    bool m_method_isSet;
    bool m_method_isValid;

    QString m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    OAIA2CDateTime m_created_time;
    bool m_created_time_isSet;
    bool m_created_time_isValid;

    OAIA2CDateTime m_processed_time;
    bool m_processed_time_isSet;
    bool m_processed_time_isValid;

    OAIObject m_additional_fields;
    bool m_additional_fields_isSet;
    bool m_additional_fields_isValid;

    OAIObject m_custom_fields;
    bool m_custom_fields_isSet;
    bool m_custom_fields_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIBatch_Job)

#endif // OAIBatch_Job_H
