/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICategoryDeleteBatch.h
 *
 * 
 */

#ifndef OAICategoryDeleteBatch_H
#define OAICategoryDeleteBatch_H

#include <QJsonObject>

#include "OAICategoryDeleteBatch_payload_inner.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAICategoryDeleteBatch_payload_inner;

class OAICategoryDeleteBatch : public OAIObject {
public:
    OAICategoryDeleteBatch();
    OAICategoryDeleteBatch(QString json);
    ~OAICategoryDeleteBatch() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAICategoryDeleteBatch_payload_inner> getPayload() const;
    void setPayload(const QList<OAICategoryDeleteBatch_payload_inner> &payload);
    bool is_payload_Set() const;
    bool is_payload_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAICategoryDeleteBatch_payload_inner> m_payload;
    bool m_payload_isSet;
    bool m_payload_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICategoryDeleteBatch)

#endif // OAICategoryDeleteBatch_H
