/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICustomerAdd_consents_inner.h
 *
 * 
 */

#ifndef OAICustomerAdd_consents_inner_H
#define OAICustomerAdd_consents_inner_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAICustomerAdd_consents_inner : public OAIObject {
public:
    OAICustomerAdd_consents_inner();
    OAICustomerAdd_consents_inner(QString json);
    ~OAICustomerAdd_consents_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getType() const;
    void setType(const QString &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    QString getStatus() const;
    void setStatus(const QString &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QString getOptInLevel() const;
    void setOptInLevel(const QString &opt_in_level);
    bool is_opt_in_level_Set() const;
    bool is_opt_in_level_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_type;
    bool m_type_isSet;
    bool m_type_isValid;

    QString m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    QString m_opt_in_level;
    bool m_opt_in_level_isSet;
    bool m_opt_in_level_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICustomerAdd_consents_inner)

#endif // OAICustomerAdd_consents_inner_H
