/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICart_ShippingZone2.h
 *
 * 
 */

#ifndef OAICart_ShippingZone2_H
#define OAICart_ShippingZone2_H

#include <QJsonObject>

#include "OAICart_ShippingMethod.h"
#include "OAICountry.h"
#include "OAIObject.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAICountry;
class OAICart_ShippingMethod;

class OAICart_ShippingZone2 : public OAIObject {
public:
    OAICart_ShippingZone2();
    OAICart_ShippingZone2(QString json);
    ~OAICart_ShippingZone2() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    bool isEnabled() const;
    void setEnabled(const bool &enabled);
    bool is_enabled_Set() const;
    bool is_enabled_Valid() const;

    QList<OAICountry> getCountries() const;
    void setCountries(const QList<OAICountry> &countries);
    bool is_countries_Set() const;
    bool is_countries_Valid() const;

    QList<OAICart_ShippingMethod> getShippingMethods() const;
    void setShippingMethods(const QList<OAICart_ShippingMethod> &shipping_methods);
    bool is_shipping_methods_Set() const;
    bool is_shipping_methods_Valid() const;

    OAIObject getAdditionalFields() const;
    void setAdditionalFields(const OAIObject &additional_fields);
    bool is_additional_fields_Set() const;
    bool is_additional_fields_Valid() const;

    OAIObject getCustomFields() const;
    void setCustomFields(const OAIObject &custom_fields);
    bool is_custom_fields_Set() const;
    bool is_custom_fields_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    bool m_enabled;
    bool m_enabled_isSet;
    bool m_enabled_isValid;

    QList<OAICountry> m_countries;
    bool m_countries_isSet;
    bool m_countries_isValid;

    QList<OAICart_ShippingMethod> m_shipping_methods;
    bool m_shipping_methods_isSet;
    bool m_shipping_methods_isValid;

    OAIObject m_additional_fields;
    bool m_additional_fields_isSet;
    bool m_additional_fields_isValid;

    OAIObject m_custom_fields;
    bool m_custom_fields_isSet;
    bool m_custom_fields_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICart_ShippingZone2)

#endif // OAICart_ShippingZone2_H
