/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICategoryAddBatch.h
 *
 * 
 */

#ifndef OAICategoryAddBatch_H
#define OAICategoryAddBatch_H

#include <QJsonObject>

#include "OAICategoryAddBatch_payload_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAICategoryAddBatch_payload_inner;

class OAICategoryAddBatch : public OAIObject {
public:
    OAICategoryAddBatch();
    OAICategoryAddBatch(QString json);
    ~OAICategoryAddBatch() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAICategoryAddBatch_payload_inner> getPayload() const;
    void setPayload(const QList<OAICategoryAddBatch_payload_inner> &payload);
    bool is_payload_Set() const;
    bool is_payload_Valid() const;

    QString getIdempotencyKey() const;
    void setIdempotencyKey(const QString &idempotency_key);
    bool is_idempotency_key_Set() const;
    bool is_idempotency_key_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAICategoryAddBatch_payload_inner> m_payload;
    bool m_payload_isSet;
    bool m_payload_isValid;

    QString m_idempotency_key;
    bool m_idempotency_key_isSet;
    bool m_idempotency_key_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICategoryAddBatch)

#endif // OAICategoryAddBatch_H
