/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAICart_PickupLocation.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAICart_PickupLocation::OAICart_PickupLocation(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAICart_PickupLocation::OAICart_PickupLocation() {
    this->initializeModel();
}

OAICart_PickupLocation::~OAICart_PickupLocation() {}

void OAICart_PickupLocation::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_avail_isSet = false;
    m_avail_isValid = false;

    m_address_isSet = false;
    m_address_isValid = false;

    m_pickup_instructions_isSet = false;
    m_pickup_instructions_isValid = false;

    m_expected_ready_time_isSet = false;
    m_expected_ready_time_isValid = false;

    m_additional_fields_isSet = false;
    m_additional_fields_isValid = false;

    m_custom_fields_isSet = false;
    m_custom_fields_isValid = false;
}

void OAICart_PickupLocation::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAICart_PickupLocation::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_name_isValid = ::OpenAPI::fromJsonValue(m_name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_avail_isValid = ::OpenAPI::fromJsonValue(m_avail, json[QString("avail")]);
    m_avail_isSet = !json[QString("avail")].isNull() && m_avail_isValid;

    m_address_isValid = ::OpenAPI::fromJsonValue(m_address, json[QString("address")]);
    m_address_isSet = !json[QString("address")].isNull() && m_address_isValid;

    m_pickup_instructions_isValid = ::OpenAPI::fromJsonValue(m_pickup_instructions, json[QString("pickup_instructions")]);
    m_pickup_instructions_isSet = !json[QString("pickup_instructions")].isNull() && m_pickup_instructions_isValid;

    m_expected_ready_time_isValid = ::OpenAPI::fromJsonValue(m_expected_ready_time, json[QString("expected_ready_time")]);
    m_expected_ready_time_isSet = !json[QString("expected_ready_time")].isNull() && m_expected_ready_time_isValid;

    m_additional_fields_isValid = ::OpenAPI::fromJsonValue(m_additional_fields, json[QString("additional_fields")]);
    m_additional_fields_isSet = !json[QString("additional_fields")].isNull() && m_additional_fields_isValid;

    m_custom_fields_isValid = ::OpenAPI::fromJsonValue(m_custom_fields, json[QString("custom_fields")]);
    m_custom_fields_isSet = !json[QString("custom_fields")].isNull() && m_custom_fields_isValid;
}

QString OAICart_PickupLocation::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAICart_PickupLocation::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(m_name));
    }
    if (m_avail_isSet) {
        obj.insert(QString("avail"), ::OpenAPI::toJsonValue(m_avail));
    }
    if (m_address.isSet()) {
        obj.insert(QString("address"), ::OpenAPI::toJsonValue(m_address));
    }
    if (m_pickup_instructions_isSet) {
        obj.insert(QString("pickup_instructions"), ::OpenAPI::toJsonValue(m_pickup_instructions));
    }
    if (m_expected_ready_time_isSet) {
        obj.insert(QString("expected_ready_time"), ::OpenAPI::toJsonValue(m_expected_ready_time));
    }
    if (m_additional_fields_isSet) {
        obj.insert(QString("additional_fields"), ::OpenAPI::toJsonValue(m_additional_fields));
    }
    if (m_custom_fields_isSet) {
        obj.insert(QString("custom_fields"), ::OpenAPI::toJsonValue(m_custom_fields));
    }
    return obj;
}

QString OAICart_PickupLocation::getId() const {
    return m_id;
}
void OAICart_PickupLocation::setId(const QString &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAICart_PickupLocation::is_id_Set() const{
    return m_id_isSet;
}

bool OAICart_PickupLocation::is_id_Valid() const{
    return m_id_isValid;
}

QString OAICart_PickupLocation::getName() const {
    return m_name;
}
void OAICart_PickupLocation::setName(const QString &name) {
    m_name = name;
    m_name_isSet = true;
}

bool OAICart_PickupLocation::is_name_Set() const{
    return m_name_isSet;
}

bool OAICart_PickupLocation::is_name_Valid() const{
    return m_name_isValid;
}

bool OAICart_PickupLocation::isAvail() const {
    return m_avail;
}
void OAICart_PickupLocation::setAvail(const bool &avail) {
    m_avail = avail;
    m_avail_isSet = true;
}

bool OAICart_PickupLocation::is_avail_Set() const{
    return m_avail_isSet;
}

bool OAICart_PickupLocation::is_avail_Valid() const{
    return m_avail_isValid;
}

OAICustomer_Address OAICart_PickupLocation::getAddress() const {
    return m_address;
}
void OAICart_PickupLocation::setAddress(const OAICustomer_Address &address) {
    m_address = address;
    m_address_isSet = true;
}

bool OAICart_PickupLocation::is_address_Set() const{
    return m_address_isSet;
}

bool OAICart_PickupLocation::is_address_Valid() const{
    return m_address_isValid;
}

QString OAICart_PickupLocation::getPickupInstructions() const {
    return m_pickup_instructions;
}
void OAICart_PickupLocation::setPickupInstructions(const QString &pickup_instructions) {
    m_pickup_instructions = pickup_instructions;
    m_pickup_instructions_isSet = true;
}

bool OAICart_PickupLocation::is_pickup_instructions_Set() const{
    return m_pickup_instructions_isSet;
}

bool OAICart_PickupLocation::is_pickup_instructions_Valid() const{
    return m_pickup_instructions_isValid;
}

QString OAICart_PickupLocation::getExpectedReadyTime() const {
    return m_expected_ready_time;
}
void OAICart_PickupLocation::setExpectedReadyTime(const QString &expected_ready_time) {
    m_expected_ready_time = expected_ready_time;
    m_expected_ready_time_isSet = true;
}

bool OAICart_PickupLocation::is_expected_ready_time_Set() const{
    return m_expected_ready_time_isSet;
}

bool OAICart_PickupLocation::is_expected_ready_time_Valid() const{
    return m_expected_ready_time_isValid;
}

OAIObject OAICart_PickupLocation::getAdditionalFields() const {
    return m_additional_fields;
}
void OAICart_PickupLocation::setAdditionalFields(const OAIObject &additional_fields) {
    m_additional_fields = additional_fields;
    m_additional_fields_isSet = true;
}

bool OAICart_PickupLocation::is_additional_fields_Set() const{
    return m_additional_fields_isSet;
}

bool OAICart_PickupLocation::is_additional_fields_Valid() const{
    return m_additional_fields_isValid;
}

OAIObject OAICart_PickupLocation::getCustomFields() const {
    return m_custom_fields;
}
void OAICart_PickupLocation::setCustomFields(const OAIObject &custom_fields) {
    m_custom_fields = custom_fields;
    m_custom_fields_isSet = true;
}

bool OAICart_PickupLocation::is_custom_fields_Set() const{
    return m_custom_fields_isSet;
}

bool OAICart_PickupLocation::is_custom_fields_Valid() const{
    return m_custom_fields_isValid;
}

bool OAICart_PickupLocation::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_avail_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_address.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_pickup_instructions_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_expected_ready_time_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_additional_fields_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_custom_fields_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAICart_PickupLocation::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
