/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICartCreate.h
 *
 * 
 */

#ifndef OAICartCreate_H
#define OAICartCreate_H

#include <QJsonObject>

#include "OAIAccountCartAdd_hybris_websites_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIAccountCartAdd_hybris_websites_inner;

class OAICartCreate : public OAIObject {
public:
    OAICartCreate();
    OAICartCreate(QString json);
    ~OAICartCreate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCartId() const;
    void setCartId(const QString &cart_id);
    bool is_cart_id_Set() const;
    bool is_cart_id_Valid() const;

    QString getStoreUrl() const;
    void setStoreUrl(const QString &store_url);
    bool is_store_url_Set() const;
    bool is_store_url_Valid() const;

    QString getBridgeUrl() const;
    void setBridgeUrl(const QString &bridge_url);
    bool is_bridge_url_Set() const;
    bool is_bridge_url_Valid() const;

    QString getStoreRoot() const;
    void setStoreRoot(const QString &store_root);
    bool is_store_root_Set() const;
    bool is_store_root_Valid() const;

    QString getStoreKey() const;
    void setStoreKey(const QString &store_key);
    bool is_store_key_Set() const;
    bool is_store_key_Valid() const;

    QString getSharedSecret() const;
    void setSharedSecret(const QString &shared_secret);
    bool is_shared_secret_Set() const;
    bool is_shared_secret_Valid() const;

    bool isValidateVersion() const;
    void setValidateVersion(const bool &validate_version);
    bool is_validate_version_Set() const;
    bool is_validate_version_Valid() const;

    bool isVerify() const;
    void setVerify(const bool &verify);
    bool is_verify_Set() const;
    bool is_verify_Valid() const;

    QString getDbTablesPrefix() const;
    void setDbTablesPrefix(const QString &db_tables_prefix);
    bool is_db_tables_prefix_Set() const;
    bool is_db_tables_prefix_Valid() const;

    QString getUserAgent() const;
    void setUserAgent(const QString &user_agent);
    bool is_user_agent_Set() const;
    bool is_user_agent_Valid() const;

    QString getFtpHost() const;
    void setFtpHost(const QString &ftp_host);
    bool is_ftp_host_Set() const;
    bool is_ftp_host_Valid() const;

    QString getFtpUser() const;
    void setFtpUser(const QString &ftp_user);
    bool is_ftp_user_Set() const;
    bool is_ftp_user_Valid() const;

    QString getFtpPassword() const;
    void setFtpPassword(const QString &ftp_password);
    bool is_ftp_password_Set() const;
    bool is_ftp_password_Valid() const;

    qint32 getFtpPort() const;
    void setFtpPort(const qint32 &ftp_port);
    bool is_ftp_port_Set() const;
    bool is_ftp_port_Valid() const;

    QString getFtpStoreDir() const;
    void setFtpStoreDir(const QString &ftp_store_dir);
    bool is_ftp_store_dir_Set() const;
    bool is_ftp_store_dir_Valid() const;

    QString getApiKey3dcart() const;
    void setApiKey3dcart(const QString &api_key_3dcart);
    bool is_api_key_3dcart_Set() const;
    bool is_api_key_3dcart_Valid() const;

    QString getAdminAccount() const;
    void setAdminAccount(const QString &admin_account);
    bool is_admin_account_Set() const;
    bool is_admin_account_Valid() const;

    QString getApiPath() const;
    void setApiPath(const QString &api_path);
    bool is_api_path_Set() const;
    bool is_api_path_Valid() const;

    QString getApiKeyBigcommerce() const;
    void setApiKeyBigcommerce(const QString &api_key_bigcommerce);
    bool is_api_key_bigcommerce_Set() const;
    bool is_api_key_bigcommerce_Valid() const;

    QString getClientId() const;
    void setClientId(const QString &client_id);
    bool is_client_id_Set() const;
    bool is_client_id_Valid() const;

    QString getAccessToken() const;
    void setAccessToken(const QString &access_token);
    bool is_access_token_Set() const;
    bool is_access_token_Valid() const;

    QString getContext() const;
    void setContext(const QString &context);
    bool is_context_Set() const;
    bool is_context_Valid() const;

    QString getAccessToken() const;
    void setAccessToken(const QString &access_token);
    bool is_access_token_Set() const;
    bool is_access_token_Valid() const;

    QString getApiKeyShopify() const;
    void setApiKeyShopify(const QString &api_key_shopify);
    bool is_api_key_shopify_Set() const;
    bool is_api_key_shopify_Valid() const;

    QString getApiPassword() const;
    void setApiPassword(const QString &api_password);
    bool is_api_password_Set() const;
    bool is_api_password_Valid() const;

    QString getAccessTokenShopify() const;
    void setAccessTokenShopify(const QString &access_token_shopify);
    bool is_access_token_shopify_Set() const;
    bool is_access_token_shopify_Valid() const;

    QString getApiKey() const;
    void setApiKey(const QString &api_key);
    bool is_api_key_Set() const;
    bool is_api_key_Valid() const;

    QString getApiUsername() const;
    void setApiUsername(const QString &api_username);
    bool is_api_username_Set() const;
    bool is_api_username_Valid() const;

    QString getEncryptedPassword() const;
    void setEncryptedPassword(const QString &encrypted_password);
    bool is_encrypted_password_Set() const;
    bool is_encrypted_password_Valid() const;

    QString getLogin() const;
    void setLogin(const QString &login);
    bool is_login_Set() const;
    bool is_login_Valid() const;

    QString getApiUserAdnsf() const;
    void setApiUserAdnsf(const QString &api_user_adnsf);
    bool is_api_user_adnsf_Set() const;
    bool is_api_user_adnsf_Valid() const;

    QString getApiPass() const;
    void setApiPass(const QString &api_pass);
    bool is_api_pass_Set() const;
    bool is_api_pass_Valid() const;

    QString getPrivateKey() const;
    void setPrivateKey(const QString &private_key);
    bool is_private_key_Set() const;
    bool is_private_key_Valid() const;

    QString getAppToken() const;
    void setAppToken(const QString &app_token);
    bool is_app_token_Set() const;
    bool is_app_token_Valid() const;

    QString getEtsyKeystring() const;
    void setEtsyKeystring(const QString &etsy_keystring);
    bool is_etsy_keystring_Set() const;
    bool is_etsy_keystring_Valid() const;

    QString getEtsySharedSecret() const;
    void setEtsySharedSecret(const QString &etsy_shared_secret);
    bool is_etsy_shared_secret_Set() const;
    bool is_etsy_shared_secret_Valid() const;

    QString getTokenSecret() const;
    void setTokenSecret(const QString &token_secret);
    bool is_token_secret_Set() const;
    bool is_token_secret_Valid() const;

    QString getEtsyClientId() const;
    void setEtsyClientId(const QString &etsy_client_id);
    bool is_etsy_client_id_Set() const;
    bool is_etsy_client_id_Valid() const;

    QString getEtsyRefreshToken() const;
    void setEtsyRefreshToken(const QString &etsy_refresh_token);
    bool is_etsy_refresh_token_Set() const;
    bool is_etsy_refresh_token_Valid() const;

    QString getEbayClientId() const;
    void setEbayClientId(const QString &ebay_client_id);
    bool is_ebay_client_id_Set() const;
    bool is_ebay_client_id_Valid() const;

    QString getEbayClientSecret() const;
    void setEbayClientSecret(const QString &ebay_client_secret);
    bool is_ebay_client_secret_Set() const;
    bool is_ebay_client_secret_Valid() const;

    QString getEbayRuname() const;
    void setEbayRuname(const QString &ebay_runame);
    bool is_ebay_runame_Set() const;
    bool is_ebay_runame_Valid() const;

    QString getEbayAccessToken() const;
    void setEbayAccessToken(const QString &ebay_access_token);
    bool is_ebay_access_token_Set() const;
    bool is_ebay_access_token_Valid() const;

    QString getEbayRefreshToken() const;
    void setEbayRefreshToken(const QString &ebay_refresh_token);
    bool is_ebay_refresh_token_Set() const;
    bool is_ebay_refresh_token_Valid() const;

    QString getEbayEnvironment() const;
    void setEbayEnvironment(const QString &ebay_environment);
    bool is_ebay_environment_Set() const;
    bool is_ebay_environment_Valid() const;

    qint32 getEbaySiteId() const;
    void setEbaySiteId(const qint32 &ebay_site_id);
    bool is_ebay_site_id_Set() const;
    bool is_ebay_site_id_Valid() const;

    QString getDwClientId() const;
    void setDwClientId(const QString &dw_client_id);
    bool is_dw_client_id_Set() const;
    bool is_dw_client_id_Valid() const;

    QString getDwApiPass() const;
    void setDwApiPass(const QString &dw_api_pass);
    bool is_dw_api_pass_Set() const;
    bool is_dw_api_pass_Valid() const;

    QString getDemandwareUserName() const;
    void setDemandwareUserName(const QString &demandware_user_name);
    bool is_demandware_user_name_Set() const;
    bool is_demandware_user_name_Valid() const;

    QString getDemandwareUserPassword() const;
    void setDemandwareUserPassword(const QString &demandware_user_password);
    bool is_demandware_user_password_Set() const;
    bool is_demandware_user_password_Valid() const;

    QString getStoreId() const;
    void setStoreId(const QString &store_id);
    bool is_store_id_Set() const;
    bool is_store_id_Valid() const;

    QString getSellerId() const;
    void setSellerId(const QString &seller_id);
    bool is_seller_id_Set() const;
    bool is_seller_id_Valid() const;

    QString getEnvironment() const;
    void setEnvironment(const QString &environment);
    bool is_environment_Set() const;
    bool is_environment_Valid() const;

    QString getHybrisClientId() const;
    void setHybrisClientId(const QString &hybris_client_id);
    bool is_hybris_client_id_Set() const;
    bool is_hybris_client_id_Valid() const;

    QString getHybrisClientSecret() const;
    void setHybrisClientSecret(const QString &hybris_client_secret);
    bool is_hybris_client_secret_Set() const;
    bool is_hybris_client_secret_Valid() const;

    QString getHybrisUsername() const;
    void setHybrisUsername(const QString &hybris_username);
    bool is_hybris_username_Set() const;
    bool is_hybris_username_Valid() const;

    QString getHybrisPassword() const;
    void setHybrisPassword(const QString &hybris_password);
    bool is_hybris_password_Set() const;
    bool is_hybris_password_Valid() const;

    QList<OAIAccountCartAdd_hybris_websites_inner> getHybrisWebsites() const;
    void setHybrisWebsites(const QList<OAIAccountCartAdd_hybris_websites_inner> &hybris_websites);
    bool is_hybris_websites_Set() const;
    bool is_hybris_websites_Valid() const;

    QString getWalmartClientId() const;
    void setWalmartClientId(const QString &walmart_client_id);
    bool is_walmart_client_id_Set() const;
    bool is_walmart_client_id_Valid() const;

    QString getWalmartClientSecret() const;
    void setWalmartClientSecret(const QString &walmart_client_secret);
    bool is_walmart_client_secret_Set() const;
    bool is_walmart_client_secret_Valid() const;

    QString getWalmartEnvironment() const;
    void setWalmartEnvironment(const QString &walmart_environment);
    bool is_walmart_environment_Set() const;
    bool is_walmart_environment_Valid() const;

    QString getWalmartChannelType() const;
    void setWalmartChannelType(const QString &walmart_channel_type);
    bool is_walmart_channel_type_Set() const;
    bool is_walmart_channel_type_Valid() const;

    QString getWalmartRegion() const;
    void setWalmartRegion(const QString &walmart_region);
    bool is_walmart_region_Set() const;
    bool is_walmart_region_Valid() const;

    QString getLightspeedApiKey() const;
    void setLightspeedApiKey(const QString &lightspeed_api_key);
    bool is_lightspeed_api_key_Set() const;
    bool is_lightspeed_api_key_Valid() const;

    QString getLightspeedApiSecret() const;
    void setLightspeedApiSecret(const QString &lightspeed_api_secret);
    bool is_lightspeed_api_secret_Set() const;
    bool is_lightspeed_api_secret_Valid() const;

    QString getShoplazzaAccessToken() const;
    void setShoplazzaAccessToken(const QString &shoplazza_access_token);
    bool is_shoplazza_access_token_Set() const;
    bool is_shoplazza_access_token_Valid() const;

    QString getShoplazzaSharedSecret() const;
    void setShoplazzaSharedSecret(const QString &shoplazza_shared_secret);
    bool is_shoplazza_shared_secret_Set() const;
    bool is_shoplazza_shared_secret_Valid() const;

    QString getShopwareAccessKey() const;
    void setShopwareAccessKey(const QString &shopware_access_key);
    bool is_shopware_access_key_Set() const;
    bool is_shopware_access_key_Valid() const;

    QString getShopwareApiKey() const;
    void setShopwareApiKey(const QString &shopware_api_key);
    bool is_shopware_api_key_Set() const;
    bool is_shopware_api_key_Valid() const;

    QString getShopwareApiSecret() const;
    void setShopwareApiSecret(const QString &shopware_api_secret);
    bool is_shopware_api_secret_Set() const;
    bool is_shopware_api_secret_Valid() const;

    QString getCommercehqApiKey() const;
    void setCommercehqApiKey(const QString &commercehq_api_key);
    bool is_commercehq_api_key_Set() const;
    bool is_commercehq_api_key_Valid() const;

    QString getCommercehqApiPassword() const;
    void setCommercehqApiPassword(const QString &commercehq_api_password);
    bool is_commercehq_api_password_Set() const;
    bool is_commercehq_api_password_Valid() const;

    QString getR3dcartPrivateKey() const;
    void setR3dcartPrivateKey(const QString &r_3dcart_private_key);
    bool is_r_3dcart_private_key_Set() const;
    bool is_r_3dcart_private_key_Valid() const;

    QString getR3dcartAccessToken() const;
    void setR3dcartAccessToken(const QString &r_3dcart_access_token);
    bool is_r_3dcart_access_token_Set() const;
    bool is_r_3dcart_access_token_Valid() const;

    QString getWcConsumerKey() const;
    void setWcConsumerKey(const QString &wc_consumer_key);
    bool is_wc_consumer_key_Set() const;
    bool is_wc_consumer_key_Valid() const;

    QString getWcConsumerSecret() const;
    void setWcConsumerSecret(const QString &wc_consumer_secret);
    bool is_wc_consumer_secret_Set() const;
    bool is_wc_consumer_secret_Valid() const;

    QString getMagentoConsumerKey() const;
    void setMagentoConsumerKey(const QString &magento_consumer_key);
    bool is_magento_consumer_key_Set() const;
    bool is_magento_consumer_key_Valid() const;

    QString getMagentoConsumerSecret() const;
    void setMagentoConsumerSecret(const QString &magento_consumer_secret);
    bool is_magento_consumer_secret_Set() const;
    bool is_magento_consumer_secret_Valid() const;

    QString getMagentoAccessToken() const;
    void setMagentoAccessToken(const QString &magento_access_token);
    bool is_magento_access_token_Set() const;
    bool is_magento_access_token_Valid() const;

    QString getMagentoTokenSecret() const;
    void setMagentoTokenSecret(const QString &magento_token_secret);
    bool is_magento_token_secret_Set() const;
    bool is_magento_token_secret_Valid() const;

    QString getPrestashopWebserviceKey() const;
    void setPrestashopWebserviceKey(const QString &prestashop_webservice_key);
    bool is_prestashop_webservice_key_Set() const;
    bool is_prestashop_webservice_key_Valid() const;

    QString getWixAppId() const;
    void setWixAppId(const QString &wix_app_id);
    bool is_wix_app_id_Set() const;
    bool is_wix_app_id_Valid() const;

    QString getWixAppSecretKey() const;
    void setWixAppSecretKey(const QString &wix_app_secret_key);
    bool is_wix_app_secret_key_Set() const;
    bool is_wix_app_secret_key_Valid() const;

    QString getWixInstanceId() const;
    void setWixInstanceId(const QString &wix_instance_id);
    bool is_wix_instance_id_Set() const;
    bool is_wix_instance_id_Valid() const;

    QString getWixRefreshToken() const;
    void setWixRefreshToken(const QString &wix_refresh_token);
    bool is_wix_refresh_token_Set() const;
    bool is_wix_refresh_token_Valid() const;

    QString getMercadoLibreAppId() const;
    void setMercadoLibreAppId(const QString &mercado_libre_app_id);
    bool is_mercado_libre_app_id_Set() const;
    bool is_mercado_libre_app_id_Valid() const;

    QString getMercadoLibreAppSecretKey() const;
    void setMercadoLibreAppSecretKey(const QString &mercado_libre_app_secret_key);
    bool is_mercado_libre_app_secret_key_Set() const;
    bool is_mercado_libre_app_secret_key_Valid() const;

    QString getMercadoLibreRefreshToken() const;
    void setMercadoLibreRefreshToken(const QString &mercado_libre_refresh_token);
    bool is_mercado_libre_refresh_token_Set() const;
    bool is_mercado_libre_refresh_token_Valid() const;

    qint32 getZidClientId() const;
    void setZidClientId(const qint32 &zid_client_id);
    bool is_zid_client_id_Set() const;
    bool is_zid_client_id_Valid() const;

    QString getZidClientSecret() const;
    void setZidClientSecret(const QString &zid_client_secret);
    bool is_zid_client_secret_Set() const;
    bool is_zid_client_secret_Valid() const;

    QString getZidAccessToken() const;
    void setZidAccessToken(const QString &zid_access_token);
    bool is_zid_access_token_Set() const;
    bool is_zid_access_token_Valid() const;

    QString getZidAuthorization() const;
    void setZidAuthorization(const QString &zid_authorization);
    bool is_zid_authorization_Set() const;
    bool is_zid_authorization_Valid() const;

    QString getZidRefreshToken() const;
    void setZidRefreshToken(const QString &zid_refresh_token);
    bool is_zid_refresh_token_Set() const;
    bool is_zid_refresh_token_Valid() const;

    QString getFlipkartClientId() const;
    void setFlipkartClientId(const QString &flipkart_client_id);
    bool is_flipkart_client_id_Set() const;
    bool is_flipkart_client_id_Valid() const;

    QString getFlipkartClientSecret() const;
    void setFlipkartClientSecret(const QString &flipkart_client_secret);
    bool is_flipkart_client_secret_Set() const;
    bool is_flipkart_client_secret_Valid() const;

    QString getAllegroClientId() const;
    void setAllegroClientId(const QString &allegro_client_id);
    bool is_allegro_client_id_Set() const;
    bool is_allegro_client_id_Valid() const;

    QString getAllegroClientSecret() const;
    void setAllegroClientSecret(const QString &allegro_client_secret);
    bool is_allegro_client_secret_Set() const;
    bool is_allegro_client_secret_Valid() const;

    QString getAllegroAccessToken() const;
    void setAllegroAccessToken(const QString &allegro_access_token);
    bool is_allegro_access_token_Set() const;
    bool is_allegro_access_token_Valid() const;

    QString getAllegroRefreshToken() const;
    void setAllegroRefreshToken(const QString &allegro_refresh_token);
    bool is_allegro_refresh_token_Set() const;
    bool is_allegro_refresh_token_Valid() const;

    QString getAllegroEnvironment() const;
    void setAllegroEnvironment(const QString &allegro_environment);
    bool is_allegro_environment_Set() const;
    bool is_allegro_environment_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_cart_id;
    bool m_cart_id_isSet;
    bool m_cart_id_isValid;

    QString m_store_url;
    bool m_store_url_isSet;
    bool m_store_url_isValid;

    QString m_bridge_url;
    bool m_bridge_url_isSet;
    bool m_bridge_url_isValid;

    QString m_store_root;
    bool m_store_root_isSet;
    bool m_store_root_isValid;

    QString m_store_key;
    bool m_store_key_isSet;
    bool m_store_key_isValid;

    QString m_shared_secret;
    bool m_shared_secret_isSet;
    bool m_shared_secret_isValid;

    bool m_validate_version;
    bool m_validate_version_isSet;
    bool m_validate_version_isValid;

    bool m_verify;
    bool m_verify_isSet;
    bool m_verify_isValid;

    QString m_db_tables_prefix;
    bool m_db_tables_prefix_isSet;
    bool m_db_tables_prefix_isValid;

    QString m_user_agent;
    bool m_user_agent_isSet;
    bool m_user_agent_isValid;

    QString m_ftp_host;
    bool m_ftp_host_isSet;
    bool m_ftp_host_isValid;

    QString m_ftp_user;
    bool m_ftp_user_isSet;
    bool m_ftp_user_isValid;

    QString m_ftp_password;
    bool m_ftp_password_isSet;
    bool m_ftp_password_isValid;

    qint32 m_ftp_port;
    bool m_ftp_port_isSet;
    bool m_ftp_port_isValid;

    QString m_ftp_store_dir;
    bool m_ftp_store_dir_isSet;
    bool m_ftp_store_dir_isValid;

    QString m_api_key_3dcart;
    bool m_api_key_3dcart_isSet;
    bool m_api_key_3dcart_isValid;

    QString m_admin_account;
    bool m_admin_account_isSet;
    bool m_admin_account_isValid;

    QString m_api_path;
    bool m_api_path_isSet;
    bool m_api_path_isValid;

    QString m_api_key_bigcommerce;
    bool m_api_key_bigcommerce_isSet;
    bool m_api_key_bigcommerce_isValid;

    QString m_client_id;
    bool m_client_id_isSet;
    bool m_client_id_isValid;

    QString m_access_token;
    bool m_access_token_isSet;
    bool m_access_token_isValid;

    QString m_context;
    bool m_context_isSet;
    bool m_context_isValid;

    QString m_access_token;
    bool m_access_token_isSet;
    bool m_access_token_isValid;

    QString m_api_key_shopify;
    bool m_api_key_shopify_isSet;
    bool m_api_key_shopify_isValid;

    QString m_api_password;
    bool m_api_password_isSet;
    bool m_api_password_isValid;

    QString m_access_token_shopify;
    bool m_access_token_shopify_isSet;
    bool m_access_token_shopify_isValid;

    QString m_api_key;
    bool m_api_key_isSet;
    bool m_api_key_isValid;

    QString m_api_username;
    bool m_api_username_isSet;
    bool m_api_username_isValid;

    QString m_encrypted_password;
    bool m_encrypted_password_isSet;
    bool m_encrypted_password_isValid;

    QString m_login;
    bool m_login_isSet;
    bool m_login_isValid;

    QString m_api_user_adnsf;
    bool m_api_user_adnsf_isSet;
    bool m_api_user_adnsf_isValid;

    QString m_api_pass;
    bool m_api_pass_isSet;
    bool m_api_pass_isValid;

    QString m_private_key;
    bool m_private_key_isSet;
    bool m_private_key_isValid;

    QString m_app_token;
    bool m_app_token_isSet;
    bool m_app_token_isValid;

    QString m_etsy_keystring;
    bool m_etsy_keystring_isSet;
    bool m_etsy_keystring_isValid;

    QString m_etsy_shared_secret;
    bool m_etsy_shared_secret_isSet;
    bool m_etsy_shared_secret_isValid;

    QString m_token_secret;
    bool m_token_secret_isSet;
    bool m_token_secret_isValid;

    QString m_etsy_client_id;
    bool m_etsy_client_id_isSet;
    bool m_etsy_client_id_isValid;

    QString m_etsy_refresh_token;
    bool m_etsy_refresh_token_isSet;
    bool m_etsy_refresh_token_isValid;

    QString m_ebay_client_id;
    bool m_ebay_client_id_isSet;
    bool m_ebay_client_id_isValid;

    QString m_ebay_client_secret;
    bool m_ebay_client_secret_isSet;
    bool m_ebay_client_secret_isValid;

    QString m_ebay_runame;
    bool m_ebay_runame_isSet;
    bool m_ebay_runame_isValid;

    QString m_ebay_access_token;
    bool m_ebay_access_token_isSet;
    bool m_ebay_access_token_isValid;

    QString m_ebay_refresh_token;
    bool m_ebay_refresh_token_isSet;
    bool m_ebay_refresh_token_isValid;

    QString m_ebay_environment;
    bool m_ebay_environment_isSet;
    bool m_ebay_environment_isValid;

    qint32 m_ebay_site_id;
    bool m_ebay_site_id_isSet;
    bool m_ebay_site_id_isValid;

    QString m_dw_client_id;
    bool m_dw_client_id_isSet;
    bool m_dw_client_id_isValid;

    QString m_dw_api_pass;
    bool m_dw_api_pass_isSet;
    bool m_dw_api_pass_isValid;

    QString m_demandware_user_name;
    bool m_demandware_user_name_isSet;
    bool m_demandware_user_name_isValid;

    QString m_demandware_user_password;
    bool m_demandware_user_password_isSet;
    bool m_demandware_user_password_isValid;

    QString m_store_id;
    bool m_store_id_isSet;
    bool m_store_id_isValid;

    QString m_seller_id;
    bool m_seller_id_isSet;
    bool m_seller_id_isValid;

    QString m_environment;
    bool m_environment_isSet;
    bool m_environment_isValid;

    QString m_hybris_client_id;
    bool m_hybris_client_id_isSet;
    bool m_hybris_client_id_isValid;

    QString m_hybris_client_secret;
    bool m_hybris_client_secret_isSet;
    bool m_hybris_client_secret_isValid;

    QString m_hybris_username;
    bool m_hybris_username_isSet;
    bool m_hybris_username_isValid;

    QString m_hybris_password;
    bool m_hybris_password_isSet;
    bool m_hybris_password_isValid;

    QList<OAIAccountCartAdd_hybris_websites_inner> m_hybris_websites;
    bool m_hybris_websites_isSet;
    bool m_hybris_websites_isValid;

    QString m_walmart_client_id;
    bool m_walmart_client_id_isSet;
    bool m_walmart_client_id_isValid;

    QString m_walmart_client_secret;
    bool m_walmart_client_secret_isSet;
    bool m_walmart_client_secret_isValid;

    QString m_walmart_environment;
    bool m_walmart_environment_isSet;
    bool m_walmart_environment_isValid;

    QString m_walmart_channel_type;
    bool m_walmart_channel_type_isSet;
    bool m_walmart_channel_type_isValid;

    QString m_walmart_region;
    bool m_walmart_region_isSet;
    bool m_walmart_region_isValid;

    QString m_lightspeed_api_key;
    bool m_lightspeed_api_key_isSet;
    bool m_lightspeed_api_key_isValid;

    QString m_lightspeed_api_secret;
    bool m_lightspeed_api_secret_isSet;
    bool m_lightspeed_api_secret_isValid;

    QString m_shoplazza_access_token;
    bool m_shoplazza_access_token_isSet;
    bool m_shoplazza_access_token_isValid;

    QString m_shoplazza_shared_secret;
    bool m_shoplazza_shared_secret_isSet;
    bool m_shoplazza_shared_secret_isValid;

    QString m_shopware_access_key;
    bool m_shopware_access_key_isSet;
    bool m_shopware_access_key_isValid;

    QString m_shopware_api_key;
    bool m_shopware_api_key_isSet;
    bool m_shopware_api_key_isValid;

    QString m_shopware_api_secret;
    bool m_shopware_api_secret_isSet;
    bool m_shopware_api_secret_isValid;

    QString m_commercehq_api_key;
    bool m_commercehq_api_key_isSet;
    bool m_commercehq_api_key_isValid;

    QString m_commercehq_api_password;
    bool m_commercehq_api_password_isSet;
    bool m_commercehq_api_password_isValid;

    QString m_r_3dcart_private_key;
    bool m_r_3dcart_private_key_isSet;
    bool m_r_3dcart_private_key_isValid;

    QString m_r_3dcart_access_token;
    bool m_r_3dcart_access_token_isSet;
    bool m_r_3dcart_access_token_isValid;

    QString m_wc_consumer_key;
    bool m_wc_consumer_key_isSet;
    bool m_wc_consumer_key_isValid;

    QString m_wc_consumer_secret;
    bool m_wc_consumer_secret_isSet;
    bool m_wc_consumer_secret_isValid;

    QString m_magento_consumer_key;
    bool m_magento_consumer_key_isSet;
    bool m_magento_consumer_key_isValid;

    QString m_magento_consumer_secret;
    bool m_magento_consumer_secret_isSet;
    bool m_magento_consumer_secret_isValid;

    QString m_magento_access_token;
    bool m_magento_access_token_isSet;
    bool m_magento_access_token_isValid;

    QString m_magento_token_secret;
    bool m_magento_token_secret_isSet;
    bool m_magento_token_secret_isValid;

    QString m_prestashop_webservice_key;
    bool m_prestashop_webservice_key_isSet;
    bool m_prestashop_webservice_key_isValid;

    QString m_wix_app_id;
    bool m_wix_app_id_isSet;
    bool m_wix_app_id_isValid;

    QString m_wix_app_secret_key;
    bool m_wix_app_secret_key_isSet;
    bool m_wix_app_secret_key_isValid;

    QString m_wix_instance_id;
    bool m_wix_instance_id_isSet;
    bool m_wix_instance_id_isValid;

    QString m_wix_refresh_token;
    bool m_wix_refresh_token_isSet;
    bool m_wix_refresh_token_isValid;

    QString m_mercado_libre_app_id;
    bool m_mercado_libre_app_id_isSet;
    bool m_mercado_libre_app_id_isValid;

    QString m_mercado_libre_app_secret_key;
    bool m_mercado_libre_app_secret_key_isSet;
    bool m_mercado_libre_app_secret_key_isValid;

    QString m_mercado_libre_refresh_token;
    bool m_mercado_libre_refresh_token_isSet;
    bool m_mercado_libre_refresh_token_isValid;

    qint32 m_zid_client_id;
    bool m_zid_client_id_isSet;
    bool m_zid_client_id_isValid;

    QString m_zid_client_secret;
    bool m_zid_client_secret_isSet;
    bool m_zid_client_secret_isValid;

    QString m_zid_access_token;
    bool m_zid_access_token_isSet;
    bool m_zid_access_token_isValid;

    QString m_zid_authorization;
    bool m_zid_authorization_isSet;
    bool m_zid_authorization_isValid;

    QString m_zid_refresh_token;
    bool m_zid_refresh_token_isSet;
    bool m_zid_refresh_token_isValid;

    QString m_flipkart_client_id;
    bool m_flipkart_client_id_isSet;
    bool m_flipkart_client_id_isValid;

    QString m_flipkart_client_secret;
    bool m_flipkart_client_secret_isSet;
    bool m_flipkart_client_secret_isValid;

    QString m_allegro_client_id;
    bool m_allegro_client_id_isSet;
    bool m_allegro_client_id_isValid;

    QString m_allegro_client_secret;
    bool m_allegro_client_secret_isSet;
    bool m_allegro_client_secret_isValid;

    QString m_allegro_access_token;
    bool m_allegro_access_token_isSet;
    bool m_allegro_access_token_isValid;

    QString m_allegro_refresh_token;
    bool m_allegro_refresh_token_isSet;
    bool m_allegro_refresh_token_isValid;

    QString m_allegro_environment;
    bool m_allegro_environment_isSet;
    bool m_allegro_environment_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICartCreate)

#endif // OAICartCreate_H
