/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIOrderShipmentAddBatch_payload_inner_items_inner.h
 *
 * 
 */

#ifndef OAIOrderShipmentAddBatch_payload_inner_items_inner_H
#define OAIOrderShipmentAddBatch_payload_inner_items_inner_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIOrderShipmentAddBatch_payload_inner_items_inner : public OAIObject {
public:
    OAIOrderShipmentAddBatch_payload_inner_items_inner();
    OAIOrderShipmentAddBatch_payload_inner_items_inner(QString json);
    ~OAIOrderShipmentAddBatch_payload_inner_items_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getOrderProductId() const;
    void setOrderProductId(const QString &order_product_id);
    bool is_order_product_id_Set() const;
    bool is_order_product_id_Valid() const;

    double getQuantity() const;
    void setQuantity(const double &quantity);
    bool is_quantity_Set() const;
    bool is_quantity_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_order_product_id;
    bool m_order_product_id_isSet;
    bool m_order_product_id_isValid;

    double m_quantity;
    bool m_quantity_isSet;
    bool m_quantity_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIOrderShipmentAddBatch_payload_inner_items_inner)

#endif // OAIOrderShipmentAddBatch_payload_inner_items_inner_H
