/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIOrderShipmentAdd.h
 *
 * 
 */

#ifndef OAIOrderShipmentAdd_H
#define OAIOrderShipmentAdd_H

#include <QJsonObject>

#include "OAIOrderShipmentAdd_items_inner.h"
#include "OAIOrderShipmentAdd_tracking_numbers_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIOrderShipmentAdd_items_inner;
class OAIOrderShipmentAdd_tracking_numbers_inner;

class OAIOrderShipmentAdd : public OAIObject {
public:
    OAIOrderShipmentAdd();
    OAIOrderShipmentAdd(QString json);
    ~OAIOrderShipmentAdd() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getOrderId() const;
    void setOrderId(const QString &order_id);
    bool is_order_id_Set() const;
    bool is_order_id_Valid() const;

    QString getWarehouseId() const;
    void setWarehouseId(const QString &warehouse_id);
    bool is_warehouse_id_Set() const;
    bool is_warehouse_id_Valid() const;

    QString getStoreId() const;
    void setStoreId(const QString &store_id);
    bool is_store_id_Set() const;
    bool is_store_id_Valid() const;

    QString getShipmentProvider() const;
    void setShipmentProvider(const QString &shipment_provider);
    bool is_shipment_provider_Set() const;
    bool is_shipment_provider_Valid() const;

    QString getShippingMethod() const;
    void setShippingMethod(const QString &shipping_method);
    bool is_shipping_method_Set() const;
    bool is_shipping_method_Valid() const;

    QList<OAIOrderShipmentAdd_items_inner> getItems() const;
    void setItems(const QList<OAIOrderShipmentAdd_items_inner> &items);
    bool is_items_Set() const;
    bool is_items_Valid() const;

    QList<OAIOrderShipmentAdd_tracking_numbers_inner> getTrackingNumbers() const;
    void setTrackingNumbers(const QList<OAIOrderShipmentAdd_tracking_numbers_inner> &tracking_numbers);
    bool is_tracking_numbers_Set() const;
    bool is_tracking_numbers_Valid() const;

    QString getTrackingLink() const;
    void setTrackingLink(const QString &tracking_link);
    bool is_tracking_link_Set() const;
    bool is_tracking_link_Valid() const;

    bool isIsShipped() const;
    void setIsShipped(const bool &is_shipped);
    bool is_is_shipped_Set() const;
    bool is_is_shipped_Valid() const;

    bool isSendNotifications() const;
    void setSendNotifications(const bool &send_notifications);
    bool is_send_notifications_Set() const;
    bool is_send_notifications_Valid() const;

    bool isAdjustStock() const;
    void setAdjustStock(const bool &adjust_stock);
    bool is_adjust_stock_Set() const;
    bool is_adjust_stock_Valid() const;

    bool isCheckProcessStatus() const;
    void setCheckProcessStatus(const bool &check_process_status);
    bool is_check_process_status_Set() const;
    bool is_check_process_status_Valid() const;

    QString getTrackingProvider() const;
    void setTrackingProvider(const QString &tracking_provider);
    bool is_tracking_provider_Set() const;
    bool is_tracking_provider_Valid() const;

    QString getAdminComment() const;
    void setAdminComment(const QString &admin_comment);
    bool is_admin_comment_Set() const;
    bool is_admin_comment_Valid() const;

    QString getMailClass() const;
    void setMailClass(const QString &mail_class);
    bool is_mail_class_Set() const;
    bool is_mail_class_Valid() const;

    QString getShipDate() const;
    void setShipDate(const QString &ship_date);
    bool is_ship_date_Set() const;
    bool is_ship_date_Valid() const;

    double getWeight() const;
    void setWeight(const double &weight);
    bool is_weight_Set() const;
    bool is_weight_Valid() const;

    QString getWeightUnit() const;
    void setWeightUnit(const QString &weight_unit);
    bool is_weight_unit_Set() const;
    bool is_weight_unit_Valid() const;

    double getLength() const;
    void setLength(const double &length);
    bool is_length_Set() const;
    bool is_length_Valid() const;

    double getWidth() const;
    void setWidth(const double &width);
    bool is_width_Set() const;
    bool is_width_Valid() const;

    double getHeight() const;
    void setHeight(const double &height);
    bool is_height_Set() const;
    bool is_height_Valid() const;

    QString getDimensionsUnit() const;
    void setDimensionsUnit(const QString &dimensions_unit);
    bool is_dimensions_unit_Set() const;
    bool is_dimensions_unit_Valid() const;

    double getShippingLabelCost() const;
    void setShippingLabelCost(const double &shipping_label_cost);
    bool is_shipping_label_cost_Set() const;
    bool is_shipping_label_cost_Valid() const;

    QString getShippingLabelCurrency() const;
    void setShippingLabelCurrency(const QString &shipping_label_currency);
    bool is_shipping_label_currency_Set() const;
    bool is_shipping_label_currency_Valid() const;

    bool isRevenueEligibility() const;
    void setRevenueEligibility(const bool &revenue_eligibility);
    bool is_revenue_eligibility_Set() const;
    bool is_revenue_eligibility_Valid() const;

    QString getShipFromCountry() const;
    void setShipFromCountry(const QString &ship_from_country);
    bool is_ship_from_country_Set() const;
    bool is_ship_from_country_Valid() const;

    QString getShipToCountry() const;
    void setShipToCountry(const QString &ship_to_country);
    bool is_ship_to_country_Set() const;
    bool is_ship_to_country_Valid() const;

    QString getIncoterm() const;
    void setIncoterm(const QString &incoterm);
    bool is_incoterm_Set() const;
    bool is_incoterm_Valid() const;

    double getDutyAmount() const;
    void setDutyAmount(const double &duty_amount);
    bool is_duty_amount_Set() const;
    bool is_duty_amount_Valid() const;

    QString getDutyCurrency() const;
    void setDutyCurrency(const QString &duty_currency);
    bool is_duty_currency_Set() const;
    bool is_duty_currency_Valid() const;

    bool isEnableCache() const;
    void setEnableCache(const bool &enable_cache);
    bool is_enable_cache_Set() const;
    bool is_enable_cache_Valid() const;

    bool isUseLatestApiVersion() const;
    void setUseLatestApiVersion(const bool &use_latest_api_version);
    bool is_use_latest_api_version_Set() const;
    bool is_use_latest_api_version_Valid() const;

    QString getIdempotencyKey() const;
    void setIdempotencyKey(const QString &idempotency_key);
    bool is_idempotency_key_Set() const;
    bool is_idempotency_key_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_order_id;
    bool m_order_id_isSet;
    bool m_order_id_isValid;

    QString m_warehouse_id;
    bool m_warehouse_id_isSet;
    bool m_warehouse_id_isValid;

    QString m_store_id;
    bool m_store_id_isSet;
    bool m_store_id_isValid;

    QString m_shipment_provider;
    bool m_shipment_provider_isSet;
    bool m_shipment_provider_isValid;

    QString m_shipping_method;
    bool m_shipping_method_isSet;
    bool m_shipping_method_isValid;

    QList<OAIOrderShipmentAdd_items_inner> m_items;
    bool m_items_isSet;
    bool m_items_isValid;

    QList<OAIOrderShipmentAdd_tracking_numbers_inner> m_tracking_numbers;
    bool m_tracking_numbers_isSet;
    bool m_tracking_numbers_isValid;

    QString m_tracking_link;
    bool m_tracking_link_isSet;
    bool m_tracking_link_isValid;

    bool m_is_shipped;
    bool m_is_shipped_isSet;
    bool m_is_shipped_isValid;

    bool m_send_notifications;
    bool m_send_notifications_isSet;
    bool m_send_notifications_isValid;

    bool m_adjust_stock;
    bool m_adjust_stock_isSet;
    bool m_adjust_stock_isValid;

    bool m_check_process_status;
    bool m_check_process_status_isSet;
    bool m_check_process_status_isValid;

    QString m_tracking_provider;
    bool m_tracking_provider_isSet;
    bool m_tracking_provider_isValid;

    QString m_admin_comment;
    bool m_admin_comment_isSet;
    bool m_admin_comment_isValid;

    QString m_mail_class;
    bool m_mail_class_isSet;
    bool m_mail_class_isValid;

    QString m_ship_date;
    bool m_ship_date_isSet;
    bool m_ship_date_isValid;

    double m_weight;
    bool m_weight_isSet;
    bool m_weight_isValid;

    QString m_weight_unit;
    bool m_weight_unit_isSet;
    bool m_weight_unit_isValid;

    double m_length;
    bool m_length_isSet;
    bool m_length_isValid;

    double m_width;
    bool m_width_isSet;
    bool m_width_isValid;

    double m_height;
    bool m_height_isSet;
    bool m_height_isValid;

    QString m_dimensions_unit;
    bool m_dimensions_unit_isSet;
    bool m_dimensions_unit_isValid;

    double m_shipping_label_cost;
    bool m_shipping_label_cost_isSet;
    bool m_shipping_label_cost_isValid;

    QString m_shipping_label_currency;
    bool m_shipping_label_currency_isSet;
    bool m_shipping_label_currency_isValid;

    bool m_revenue_eligibility;
    bool m_revenue_eligibility_isSet;
    bool m_revenue_eligibility_isValid;

    QString m_ship_from_country;
    bool m_ship_from_country_isSet;
    bool m_ship_from_country_isValid;

    QString m_ship_to_country;
    bool m_ship_to_country_isSet;
    bool m_ship_to_country_isValid;

    QString m_incoterm;
    bool m_incoterm_isSet;
    bool m_incoterm_isValid;

    double m_duty_amount;
    bool m_duty_amount_isSet;
    bool m_duty_amount_isValid;

    QString m_duty_currency;
    bool m_duty_currency_isSet;
    bool m_duty_currency_isValid;

    bool m_enable_cache;
    bool m_enable_cache_isSet;
    bool m_enable_cache_isValid;

    bool m_use_latest_api_version;
    bool m_use_latest_api_version_isSet;
    bool m_use_latest_api_version_isValid;

    QString m_idempotency_key;
    bool m_idempotency_key_isSet;
    bool m_idempotency_key_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIOrderShipmentAdd)

#endif // OAIOrderShipmentAdd_H
