/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIOrderShipmentUpdate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIOrderShipmentUpdate::OAIOrderShipmentUpdate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIOrderShipmentUpdate::OAIOrderShipmentUpdate() {
    this->initializeModel();
}

OAIOrderShipmentUpdate::~OAIOrderShipmentUpdate() {}

void OAIOrderShipmentUpdate::initializeModel() {

    m_shipment_id_isSet = false;
    m_shipment_id_isValid = false;

    m_order_id_isSet = false;
    m_order_id_isValid = false;

    m_store_id_isSet = false;
    m_store_id_isValid = false;

    m_shipment_provider_isSet = false;
    m_shipment_provider_isValid = false;

    m_tracking_numbers_isSet = false;
    m_tracking_numbers_isValid = false;

    m_tracking_link_isSet = false;
    m_tracking_link_isValid = false;

    m_is_shipped_isSet = false;
    m_is_shipped_isValid = false;

    m_delivered_at_isSet = false;
    m_delivered_at_isValid = false;

    m_replace_isSet = false;
    m_replace_isValid = false;

    m_send_notifications_isSet = false;
    m_send_notifications_isValid = false;

    m_tracking_provider_isSet = false;
    m_tracking_provider_isValid = false;

    m_items_isSet = false;
    m_items_isValid = false;
}

void OAIOrderShipmentUpdate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIOrderShipmentUpdate::fromJsonObject(QJsonObject json) {

    m_shipment_id_isValid = ::OpenAPI::fromJsonValue(m_shipment_id, json[QString("shipment_id")]);
    m_shipment_id_isSet = !json[QString("shipment_id")].isNull() && m_shipment_id_isValid;

    m_order_id_isValid = ::OpenAPI::fromJsonValue(m_order_id, json[QString("order_id")]);
    m_order_id_isSet = !json[QString("order_id")].isNull() && m_order_id_isValid;

    m_store_id_isValid = ::OpenAPI::fromJsonValue(m_store_id, json[QString("store_id")]);
    m_store_id_isSet = !json[QString("store_id")].isNull() && m_store_id_isValid;

    m_shipment_provider_isValid = ::OpenAPI::fromJsonValue(m_shipment_provider, json[QString("shipment_provider")]);
    m_shipment_provider_isSet = !json[QString("shipment_provider")].isNull() && m_shipment_provider_isValid;

    m_tracking_numbers_isValid = ::OpenAPI::fromJsonValue(m_tracking_numbers, json[QString("tracking_numbers")]);
    m_tracking_numbers_isSet = !json[QString("tracking_numbers")].isNull() && m_tracking_numbers_isValid;

    m_tracking_link_isValid = ::OpenAPI::fromJsonValue(m_tracking_link, json[QString("tracking_link")]);
    m_tracking_link_isSet = !json[QString("tracking_link")].isNull() && m_tracking_link_isValid;

    m_is_shipped_isValid = ::OpenAPI::fromJsonValue(m_is_shipped, json[QString("is_shipped")]);
    m_is_shipped_isSet = !json[QString("is_shipped")].isNull() && m_is_shipped_isValid;

    m_delivered_at_isValid = ::OpenAPI::fromJsonValue(m_delivered_at, json[QString("delivered_at")]);
    m_delivered_at_isSet = !json[QString("delivered_at")].isNull() && m_delivered_at_isValid;

    m_replace_isValid = ::OpenAPI::fromJsonValue(m_replace, json[QString("replace")]);
    m_replace_isSet = !json[QString("replace")].isNull() && m_replace_isValid;

    m_send_notifications_isValid = ::OpenAPI::fromJsonValue(m_send_notifications, json[QString("send_notifications")]);
    m_send_notifications_isSet = !json[QString("send_notifications")].isNull() && m_send_notifications_isValid;

    m_tracking_provider_isValid = ::OpenAPI::fromJsonValue(m_tracking_provider, json[QString("tracking_provider")]);
    m_tracking_provider_isSet = !json[QString("tracking_provider")].isNull() && m_tracking_provider_isValid;

    m_items_isValid = ::OpenAPI::fromJsonValue(m_items, json[QString("items")]);
    m_items_isSet = !json[QString("items")].isNull() && m_items_isValid;
}

QString OAIOrderShipmentUpdate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIOrderShipmentUpdate::asJsonObject() const {
    QJsonObject obj;
    if (m_shipment_id_isSet) {
        obj.insert(QString("shipment_id"), ::OpenAPI::toJsonValue(m_shipment_id));
    }
    if (m_order_id_isSet) {
        obj.insert(QString("order_id"), ::OpenAPI::toJsonValue(m_order_id));
    }
    if (m_store_id_isSet) {
        obj.insert(QString("store_id"), ::OpenAPI::toJsonValue(m_store_id));
    }
    if (m_shipment_provider_isSet) {
        obj.insert(QString("shipment_provider"), ::OpenAPI::toJsonValue(m_shipment_provider));
    }
    if (m_tracking_numbers.size() > 0) {
        obj.insert(QString("tracking_numbers"), ::OpenAPI::toJsonValue(m_tracking_numbers));
    }
    if (m_tracking_link_isSet) {
        obj.insert(QString("tracking_link"), ::OpenAPI::toJsonValue(m_tracking_link));
    }
    if (m_is_shipped_isSet) {
        obj.insert(QString("is_shipped"), ::OpenAPI::toJsonValue(m_is_shipped));
    }
    if (m_delivered_at_isSet) {
        obj.insert(QString("delivered_at"), ::OpenAPI::toJsonValue(m_delivered_at));
    }
    if (m_replace_isSet) {
        obj.insert(QString("replace"), ::OpenAPI::toJsonValue(m_replace));
    }
    if (m_send_notifications_isSet) {
        obj.insert(QString("send_notifications"), ::OpenAPI::toJsonValue(m_send_notifications));
    }
    if (m_tracking_provider_isSet) {
        obj.insert(QString("tracking_provider"), ::OpenAPI::toJsonValue(m_tracking_provider));
    }
    if (m_items.size() > 0) {
        obj.insert(QString("items"), ::OpenAPI::toJsonValue(m_items));
    }
    return obj;
}

QString OAIOrderShipmentUpdate::getShipmentId() const {
    return m_shipment_id;
}
void OAIOrderShipmentUpdate::setShipmentId(const QString &shipment_id) {
    m_shipment_id = shipment_id;
    m_shipment_id_isSet = true;
}

bool OAIOrderShipmentUpdate::is_shipment_id_Set() const{
    return m_shipment_id_isSet;
}

bool OAIOrderShipmentUpdate::is_shipment_id_Valid() const{
    return m_shipment_id_isValid;
}

QString OAIOrderShipmentUpdate::getOrderId() const {
    return m_order_id;
}
void OAIOrderShipmentUpdate::setOrderId(const QString &order_id) {
    m_order_id = order_id;
    m_order_id_isSet = true;
}

bool OAIOrderShipmentUpdate::is_order_id_Set() const{
    return m_order_id_isSet;
}

bool OAIOrderShipmentUpdate::is_order_id_Valid() const{
    return m_order_id_isValid;
}

QString OAIOrderShipmentUpdate::getStoreId() const {
    return m_store_id;
}
void OAIOrderShipmentUpdate::setStoreId(const QString &store_id) {
    m_store_id = store_id;
    m_store_id_isSet = true;
}

bool OAIOrderShipmentUpdate::is_store_id_Set() const{
    return m_store_id_isSet;
}

bool OAIOrderShipmentUpdate::is_store_id_Valid() const{
    return m_store_id_isValid;
}

QString OAIOrderShipmentUpdate::getShipmentProvider() const {
    return m_shipment_provider;
}
void OAIOrderShipmentUpdate::setShipmentProvider(const QString &shipment_provider) {
    m_shipment_provider = shipment_provider;
    m_shipment_provider_isSet = true;
}

bool OAIOrderShipmentUpdate::is_shipment_provider_Set() const{
    return m_shipment_provider_isSet;
}

bool OAIOrderShipmentUpdate::is_shipment_provider_Valid() const{
    return m_shipment_provider_isValid;
}

QList<OAIOrderShipmentAdd_tracking_numbers_inner> OAIOrderShipmentUpdate::getTrackingNumbers() const {
    return m_tracking_numbers;
}
void OAIOrderShipmentUpdate::setTrackingNumbers(const QList<OAIOrderShipmentAdd_tracking_numbers_inner> &tracking_numbers) {
    m_tracking_numbers = tracking_numbers;
    m_tracking_numbers_isSet = true;
}

bool OAIOrderShipmentUpdate::is_tracking_numbers_Set() const{
    return m_tracking_numbers_isSet;
}

bool OAIOrderShipmentUpdate::is_tracking_numbers_Valid() const{
    return m_tracking_numbers_isValid;
}

QString OAIOrderShipmentUpdate::getTrackingLink() const {
    return m_tracking_link;
}
void OAIOrderShipmentUpdate::setTrackingLink(const QString &tracking_link) {
    m_tracking_link = tracking_link;
    m_tracking_link_isSet = true;
}

bool OAIOrderShipmentUpdate::is_tracking_link_Set() const{
    return m_tracking_link_isSet;
}

bool OAIOrderShipmentUpdate::is_tracking_link_Valid() const{
    return m_tracking_link_isValid;
}

bool OAIOrderShipmentUpdate::isIsShipped() const {
    return m_is_shipped;
}
void OAIOrderShipmentUpdate::setIsShipped(const bool &is_shipped) {
    m_is_shipped = is_shipped;
    m_is_shipped_isSet = true;
}

bool OAIOrderShipmentUpdate::is_is_shipped_Set() const{
    return m_is_shipped_isSet;
}

bool OAIOrderShipmentUpdate::is_is_shipped_Valid() const{
    return m_is_shipped_isValid;
}

QString OAIOrderShipmentUpdate::getDeliveredAt() const {
    return m_delivered_at;
}
void OAIOrderShipmentUpdate::setDeliveredAt(const QString &delivered_at) {
    m_delivered_at = delivered_at;
    m_delivered_at_isSet = true;
}

bool OAIOrderShipmentUpdate::is_delivered_at_Set() const{
    return m_delivered_at_isSet;
}

bool OAIOrderShipmentUpdate::is_delivered_at_Valid() const{
    return m_delivered_at_isValid;
}

bool OAIOrderShipmentUpdate::isReplace() const {
    return m_replace;
}
void OAIOrderShipmentUpdate::setReplace(const bool &replace) {
    m_replace = replace;
    m_replace_isSet = true;
}

bool OAIOrderShipmentUpdate::is_replace_Set() const{
    return m_replace_isSet;
}

bool OAIOrderShipmentUpdate::is_replace_Valid() const{
    return m_replace_isValid;
}

bool OAIOrderShipmentUpdate::isSendNotifications() const {
    return m_send_notifications;
}
void OAIOrderShipmentUpdate::setSendNotifications(const bool &send_notifications) {
    m_send_notifications = send_notifications;
    m_send_notifications_isSet = true;
}

bool OAIOrderShipmentUpdate::is_send_notifications_Set() const{
    return m_send_notifications_isSet;
}

bool OAIOrderShipmentUpdate::is_send_notifications_Valid() const{
    return m_send_notifications_isValid;
}

QString OAIOrderShipmentUpdate::getTrackingProvider() const {
    return m_tracking_provider;
}
void OAIOrderShipmentUpdate::setTrackingProvider(const QString &tracking_provider) {
    m_tracking_provider = tracking_provider;
    m_tracking_provider_isSet = true;
}

bool OAIOrderShipmentUpdate::is_tracking_provider_Set() const{
    return m_tracking_provider_isSet;
}

bool OAIOrderShipmentUpdate::is_tracking_provider_Valid() const{
    return m_tracking_provider_isValid;
}

QList<OAIOrderShipmentAdd_items_inner> OAIOrderShipmentUpdate::getItems() const {
    return m_items;
}
void OAIOrderShipmentUpdate::setItems(const QList<OAIOrderShipmentAdd_items_inner> &items) {
    m_items = items;
    m_items_isSet = true;
}

bool OAIOrderShipmentUpdate::is_items_Set() const{
    return m_items_isSet;
}

bool OAIOrderShipmentUpdate::is_items_Valid() const{
    return m_items_isValid;
}

bool OAIOrderShipmentUpdate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_shipment_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_order_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_store_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_shipment_provider_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_tracking_numbers.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_tracking_link_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_is_shipped_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_delivered_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_replace_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_send_notifications_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_tracking_provider_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_items.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIOrderShipmentUpdate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_shipment_id_isValid && true;
}

} // namespace OpenAPI
