/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIOrder_Calculate_Discount.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIOrder_Calculate_Discount::OAIOrder_Calculate_Discount(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIOrder_Calculate_Discount::OAIOrder_Calculate_Discount() {
    this->initializeModel();
}

OAIOrder_Calculate_Discount::~OAIOrder_Calculate_Discount() {}

void OAIOrder_Calculate_Discount::initializeModel() {

    m_code_isSet = false;
    m_code_isValid = false;

    m_value_isSet = false;
    m_value_isValid = false;

    m_type_isSet = false;
    m_type_isValid = false;

    m_free_shipping_isSet = false;
    m_free_shipping_isValid = false;

    m_additional_fields_isSet = false;
    m_additional_fields_isValid = false;

    m_custom_fields_isSet = false;
    m_custom_fields_isValid = false;
}

void OAIOrder_Calculate_Discount::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIOrder_Calculate_Discount::fromJsonObject(QJsonObject json) {

    m_code_isValid = ::OpenAPI::fromJsonValue(m_code, json[QString("code")]);
    m_code_isSet = !json[QString("code")].isNull() && m_code_isValid;

    m_value_isValid = ::OpenAPI::fromJsonValue(m_value, json[QString("value")]);
    m_value_isSet = !json[QString("value")].isNull() && m_value_isValid;

    m_type_isValid = ::OpenAPI::fromJsonValue(m_type, json[QString("type")]);
    m_type_isSet = !json[QString("type")].isNull() && m_type_isValid;

    m_free_shipping_isValid = ::OpenAPI::fromJsonValue(m_free_shipping, json[QString("free_shipping")]);
    m_free_shipping_isSet = !json[QString("free_shipping")].isNull() && m_free_shipping_isValid;

    m_additional_fields_isValid = ::OpenAPI::fromJsonValue(m_additional_fields, json[QString("additional_fields")]);
    m_additional_fields_isSet = !json[QString("additional_fields")].isNull() && m_additional_fields_isValid;

    m_custom_fields_isValid = ::OpenAPI::fromJsonValue(m_custom_fields, json[QString("custom_fields")]);
    m_custom_fields_isSet = !json[QString("custom_fields")].isNull() && m_custom_fields_isValid;
}

QString OAIOrder_Calculate_Discount::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIOrder_Calculate_Discount::asJsonObject() const {
    QJsonObject obj;
    if (m_code_isSet) {
        obj.insert(QString("code"), ::OpenAPI::toJsonValue(m_code));
    }
    if (m_value_isSet) {
        obj.insert(QString("value"), ::OpenAPI::toJsonValue(m_value));
    }
    if (m_type_isSet) {
        obj.insert(QString("type"), ::OpenAPI::toJsonValue(m_type));
    }
    if (m_free_shipping_isSet) {
        obj.insert(QString("free_shipping"), ::OpenAPI::toJsonValue(m_free_shipping));
    }
    if (m_additional_fields_isSet) {
        obj.insert(QString("additional_fields"), ::OpenAPI::toJsonValue(m_additional_fields));
    }
    if (m_custom_fields_isSet) {
        obj.insert(QString("custom_fields"), ::OpenAPI::toJsonValue(m_custom_fields));
    }
    return obj;
}

QString OAIOrder_Calculate_Discount::getCode() const {
    return m_code;
}
void OAIOrder_Calculate_Discount::setCode(const QString &code) {
    m_code = code;
    m_code_isSet = true;
}

bool OAIOrder_Calculate_Discount::is_code_Set() const{
    return m_code_isSet;
}

bool OAIOrder_Calculate_Discount::is_code_Valid() const{
    return m_code_isValid;
}

double OAIOrder_Calculate_Discount::getValue() const {
    return m_value;
}
void OAIOrder_Calculate_Discount::setValue(const double &value) {
    m_value = value;
    m_value_isSet = true;
}

bool OAIOrder_Calculate_Discount::is_value_Set() const{
    return m_value_isSet;
}

bool OAIOrder_Calculate_Discount::is_value_Valid() const{
    return m_value_isValid;
}

QString OAIOrder_Calculate_Discount::getType() const {
    return m_type;
}
void OAIOrder_Calculate_Discount::setType(const QString &type) {
    m_type = type;
    m_type_isSet = true;
}

bool OAIOrder_Calculate_Discount::is_type_Set() const{
    return m_type_isSet;
}

bool OAIOrder_Calculate_Discount::is_type_Valid() const{
    return m_type_isValid;
}

bool OAIOrder_Calculate_Discount::isFreeShipping() const {
    return m_free_shipping;
}
void OAIOrder_Calculate_Discount::setFreeShipping(const bool &free_shipping) {
    m_free_shipping = free_shipping;
    m_free_shipping_isSet = true;
}

bool OAIOrder_Calculate_Discount::is_free_shipping_Set() const{
    return m_free_shipping_isSet;
}

bool OAIOrder_Calculate_Discount::is_free_shipping_Valid() const{
    return m_free_shipping_isValid;
}

OAIObject OAIOrder_Calculate_Discount::getAdditionalFields() const {
    return m_additional_fields;
}
void OAIOrder_Calculate_Discount::setAdditionalFields(const OAIObject &additional_fields) {
    m_additional_fields = additional_fields;
    m_additional_fields_isSet = true;
}

bool OAIOrder_Calculate_Discount::is_additional_fields_Set() const{
    return m_additional_fields_isSet;
}

bool OAIOrder_Calculate_Discount::is_additional_fields_Valid() const{
    return m_additional_fields_isValid;
}

OAIObject OAIOrder_Calculate_Discount::getCustomFields() const {
    return m_custom_fields;
}
void OAIOrder_Calculate_Discount::setCustomFields(const OAIObject &custom_fields) {
    m_custom_fields = custom_fields;
    m_custom_fields_isSet = true;
}

bool OAIOrder_Calculate_Discount::is_custom_fields_Set() const{
    return m_custom_fields_isSet;
}

bool OAIOrder_Calculate_Discount::is_custom_fields_Valid() const{
    return m_custom_fields_isValid;
}

bool OAIOrder_Calculate_Discount::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_value_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_free_shipping_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_additional_fields_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_custom_fields_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIOrder_Calculate_Discount::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
