/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIProductAdd_certifications_inner.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIProductAdd_certifications_inner::OAIProductAdd_certifications_inner(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIProductAdd_certifications_inner::OAIProductAdd_certifications_inner() {
    this->initializeModel();
}

OAIProductAdd_certifications_inner::~OAIProductAdd_certifications_inner() {}

void OAIProductAdd_certifications_inner::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_images_isSet = false;
    m_images_isValid = false;

    m_files_isSet = false;
    m_files_isValid = false;
}

void OAIProductAdd_certifications_inner::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIProductAdd_certifications_inner::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_images_isValid = ::OpenAPI::fromJsonValue(m_images, json[QString("images")]);
    m_images_isSet = !json[QString("images")].isNull() && m_images_isValid;

    m_files_isValid = ::OpenAPI::fromJsonValue(m_files, json[QString("files")]);
    m_files_isSet = !json[QString("files")].isNull() && m_files_isValid;
}

QString OAIProductAdd_certifications_inner::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIProductAdd_certifications_inner::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_images.size() > 0) {
        obj.insert(QString("images"), ::OpenAPI::toJsonValue(m_images));
    }
    if (m_files.size() > 0) {
        obj.insert(QString("files"), ::OpenAPI::toJsonValue(m_files));
    }
    return obj;
}

QString OAIProductAdd_certifications_inner::getId() const {
    return m_id;
}
void OAIProductAdd_certifications_inner::setId(const QString &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAIProductAdd_certifications_inner::is_id_Set() const{
    return m_id_isSet;
}

bool OAIProductAdd_certifications_inner::is_id_Valid() const{
    return m_id_isValid;
}

QList<OAIProductAdd_certifications_inner_images_inner> OAIProductAdd_certifications_inner::getImages() const {
    return m_images;
}
void OAIProductAdd_certifications_inner::setImages(const QList<OAIProductAdd_certifications_inner_images_inner> &images) {
    m_images = images;
    m_images_isSet = true;
}

bool OAIProductAdd_certifications_inner::is_images_Set() const{
    return m_images_isSet;
}

bool OAIProductAdd_certifications_inner::is_images_Valid() const{
    return m_images_isValid;
}

QList<OAIProductAdd_certifications_inner_files_inner> OAIProductAdd_certifications_inner::getFiles() const {
    return m_files;
}
void OAIProductAdd_certifications_inner::setFiles(const QList<OAIProductAdd_certifications_inner_files_inner> &files) {
    m_files = files;
    m_files_isSet = true;
}

bool OAIProductAdd_certifications_inner::is_files_Set() const{
    return m_files_isSet;
}

bool OAIProductAdd_certifications_inner::is_files_Valid() const{
    return m_files_isValid;
}

bool OAIProductAdd_certifications_inner::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_images.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_files.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIProductAdd_certifications_inner::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && true;
}

} // namespace OpenAPI
