/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIProductAdd_specifics_inner_group_products_details_inner.h
 *
 * 
 */

#ifndef OAIProductAdd_specifics_inner_group_products_details_inner_H
#define OAIProductAdd_specifics_inner_group_products_details_inner_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIProductAdd_specifics_inner_group_products_details_inner : public OAIObject {
public:
    OAIProductAdd_specifics_inner_group_products_details_inner();
    OAIProductAdd_specifics_inner_group_products_details_inner(QString json);
    ~OAIProductAdd_specifics_inner_group_products_details_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    qint32 getQuantity() const;
    void setQuantity(const qint32 &quantity);
    bool is_quantity_Set() const;
    bool is_quantity_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    qint32 m_quantity;
    bool m_quantity_isSet;
    bool m_quantity_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIProductAdd_specifics_inner_group_products_details_inner)

#endif // OAIProductAdd_specifics_inner_group_products_details_inner_H
