/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIParamDefinition_FilteringConditions_FilterGroup.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIParamDefinition_FilteringConditions_FilterGroup::OAIParamDefinition_FilteringConditions_FilterGroup(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIParamDefinition_FilteringConditions_FilterGroup::OAIParamDefinition_FilteringConditions_FilterGroup() {
    this->initializeModel();
}

OAIParamDefinition_FilteringConditions_FilterGroup::~OAIParamDefinition_FilteringConditions_FilterGroup() {}

void OAIParamDefinition_FilteringConditions_FilterGroup::initializeModel() {

    m_r_and_isSet = false;
    m_r_and_isValid = false;

    m_r_or_isSet = false;
    m_r_or_isValid = false;

    m_r_not_isSet = false;
    m_r_not_isValid = false;
}

void OAIParamDefinition_FilteringConditions_FilterGroup::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIParamDefinition_FilteringConditions_FilterGroup::fromJsonObject(QJsonObject json) {

    m_r_and_isValid = ::OpenAPI::fromJsonValue(m_r_and, json[QString("and")]);
    m_r_and_isSet = !json[QString("and")].isNull() && m_r_and_isValid;

    m_r_or_isValid = ::OpenAPI::fromJsonValue(m_r_or, json[QString("or")]);
    m_r_or_isSet = !json[QString("or")].isNull() && m_r_or_isValid;

    m_r_not_isValid = ::OpenAPI::fromJsonValue(m_r_not, json[QString("not")]);
    m_r_not_isSet = !json[QString("not")].isNull() && m_r_not_isValid;
}

QString OAIParamDefinition_FilteringConditions_FilterGroup::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIParamDefinition_FilteringConditions_FilterGroup::asJsonObject() const {
    QJsonObject obj;
    if (m_r_and.size() > 0) {
        obj.insert(QString("and"), ::OpenAPI::toJsonValue(m_r_and));
    }
    if (m_r_or.size() > 0) {
        obj.insert(QString("or"), ::OpenAPI::toJsonValue(m_r_or));
    }
    if (m_r_not_isSet) {
        obj.insert(QString("not"), ::OpenAPI::toJsonValue(m_r_not));
    }
    return obj;
}

QList<OAIObject> OAIParamDefinition_FilteringConditions_FilterGroup::getRAnd() const {
    return m_r_and;
}
void OAIParamDefinition_FilteringConditions_FilterGroup::setRAnd(const QList<OAIObject> &r_and) {
    m_r_and = r_and;
    m_r_and_isSet = true;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::is_r_and_Set() const{
    return m_r_and_isSet;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::is_r_and_Valid() const{
    return m_r_and_isValid;
}

QList<OAIObject> OAIParamDefinition_FilteringConditions_FilterGroup::getROr() const {
    return m_r_or;
}
void OAIParamDefinition_FilteringConditions_FilterGroup::setROr(const QList<OAIObject> &r_or) {
    m_r_or = r_or;
    m_r_or_isSet = true;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::is_r_or_Set() const{
    return m_r_or_isSet;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::is_r_or_Valid() const{
    return m_r_or_isValid;
}

OAIObject OAIParamDefinition_FilteringConditions_FilterGroup::getRNot() const {
    return m_r_not;
}
void OAIParamDefinition_FilteringConditions_FilterGroup::setRNot(const OAIObject &r_not) {
    m_r_not = r_not;
    m_r_not_isSet = true;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::is_r_not_Set() const{
    return m_r_not_isSet;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::is_r_not_Valid() const{
    return m_r_not_isValid;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_r_and.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_r_or.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_r_not_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIParamDefinition_FilteringConditions_FilterGroup::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
