/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner.h
 *
 * 
 */

#ifndef OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner_H
#define OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner : public OAIObject {
public:
    OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner();
    OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner(QString json);
    ~OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFrom() const;
    void setFrom(const QString &from);
    bool is_from_Set() const;
    bool is_from_Valid() const;

    QString getTo() const;
    void setTo(const QString &to);
    bool is_to_Set() const;
    bool is_to_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_from;
    bool m_from_isSet;
    bool m_from_isValid;

    QString m_to;
    bool m_to_isSet;
    bool m_to_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner)

#endif // OAIProductAdd_specifics_inner_booking_details_availabilities_inner_times_inner_H
