/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIProductAddBatch_payload_inner_sales_tax.h
 *
 * 
 */

#ifndef OAIProductAddBatch_payload_inner_sales_tax_H
#define OAIProductAddBatch_payload_inner_sales_tax_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIProductAddBatch_payload_inner_sales_tax : public OAIObject {
public:
    OAIProductAddBatch_payload_inner_sales_tax();
    OAIProductAddBatch_payload_inner_sales_tax(QString json);
    ~OAIProductAddBatch_payload_inner_sales_tax() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getTaxPercent() const;
    void setTaxPercent(const double &tax_percent);
    bool is_tax_percent_Set() const;
    bool is_tax_percent_Valid() const;

    bool isTaxable() const;
    void setTaxable(const bool &taxable);
    bool is_taxable_Set() const;
    bool is_taxable_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double m_tax_percent;
    bool m_tax_percent_isSet;
    bool m_tax_percent_isValid;

    bool m_taxable;
    bool m_taxable_isSet;
    bool m_taxable_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIProductAddBatch_payload_inner_sales_tax)

#endif // OAIProductAddBatch_payload_inner_sales_tax_H
