/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIProductUpdate.h
 *
 * 
 */

#ifndef OAIProductUpdate_H
#define OAIProductUpdate_H

#include <QJsonObject>

#include "OAIProductAdd_manufacturer_info.h"
#include "OAIProductAdd_package_details.h"
#include "OAIProductAdd_personalization_details.h"
#include "OAIProductAdd_specifics_inner.h"
#include "OAIProductAdd_tier_prices_inner.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIProductAdd_tier_prices_inner;
class OAIProductAdd_package_details;
class OAIProductAdd_manufacturer_info;
class OAIProductAdd_specifics_inner;
class OAIProductAdd_personalization_details;

class OAIProductUpdate : public OAIObject {
public:
    OAIProductUpdate();
    OAIProductUpdate(QString json);
    ~OAIProductUpdate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getModel() const;
    void setModel(const QString &model);
    bool is_model_Set() const;
    bool is_model_Valid() const;

    QString getSku() const;
    void setSku(const QString &sku);
    bool is_sku_Set() const;
    bool is_sku_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getDescription() const;
    void setDescription(const QString &description);
    bool is_description_Set() const;
    bool is_description_Valid() const;

    QString getShortDescription() const;
    void setShortDescription(const QString &short_description);
    bool is_short_description_Set() const;
    bool is_short_description_Valid() const;

    double getPrice() const;
    void setPrice(const double &price);
    bool is_price_Set() const;
    bool is_price_Valid() const;

    double getOldPrice() const;
    void setOldPrice(const double &old_price);
    bool is_old_price_Set() const;
    bool is_old_price_Valid() const;

    double getSpecialPrice() const;
    void setSpecialPrice(const double &special_price);
    bool is_special_price_Set() const;
    bool is_special_price_Valid() const;

    QString getSpriceCreate() const;
    void setSpriceCreate(const QString &sprice_create);
    bool is_sprice_create_Set() const;
    bool is_sprice_create_Valid() const;

    QString getSpriceExpire() const;
    void setSpriceExpire(const QString &sprice_expire);
    bool is_sprice_expire_Set() const;
    bool is_sprice_expire_Valid() const;

    double getCostPrice() const;
    void setCostPrice(const double &cost_price);
    bool is_cost_price_Set() const;
    bool is_cost_price_Valid() const;

    double getFixedCostShippingPrice() const;
    void setFixedCostShippingPrice(const double &fixed_cost_shipping_price);
    bool is_fixed_cost_shipping_price_Set() const;
    bool is_fixed_cost_shipping_price_Valid() const;

    double getRetailPrice() const;
    void setRetailPrice(const double &retail_price);
    bool is_retail_price_Set() const;
    bool is_retail_price_Valid() const;

    QList<OAIProductAdd_tier_prices_inner> getTierPrices() const;
    void setTierPrices(const QList<OAIProductAdd_tier_prices_inner> &tier_prices);
    bool is_tier_prices_Set() const;
    bool is_tier_prices_Valid() const;

    double getReservePrice() const;
    void setReservePrice(const double &reserve_price);
    bool is_reserve_price_Set() const;
    bool is_reserve_price_Valid() const;

    double getBuyitnowPrice() const;
    void setBuyitnowPrice(const double &buyitnow_price);
    bool is_buyitnow_price_Set() const;
    bool is_buyitnow_price_Valid() const;

    bool isTaxable() const;
    void setTaxable(const bool &taxable);
    bool is_taxable_Set() const;
    bool is_taxable_Valid() const;

    QString getTaxClassId() const;
    void setTaxClassId(const QString &tax_class_id);
    bool is_tax_class_id_Set() const;
    bool is_tax_class_id_Valid() const;

    QString getType() const;
    void setType(const QString &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    QString getStatus() const;
    void setStatus(const QString &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QString getCondition() const;
    void setCondition(const QString &condition);
    bool is_condition_Set() const;
    bool is_condition_Valid() const;

    QString getVisible() const;
    void setVisible(const QString &visible);
    bool is_visible_Set() const;
    bool is_visible_Valid() const;

    bool isInStock() const;
    void setInStock(const bool &in_stock);
    bool is_in_stock_Set() const;
    bool is_in_stock_Valid() const;

    bool isAvail() const;
    void setAvail(const bool &avail);
    bool is_avail_Set() const;
    bool is_avail_Valid() const;

    QString getAvailFrom() const;
    void setAvailFrom(const QString &avail_from);
    bool is_avail_from_Set() const;
    bool is_avail_from_Valid() const;

    QString getProductClass() const;
    void setProductClass(const QString &product_class);
    bool is_product_class_Set() const;
    bool is_product_class_Valid() const;

    bool isAvailableForView() const;
    void setAvailableForView(const bool &available_for_view);
    bool is_available_for_view_Set() const;
    bool is_available_for_view_Valid() const;

    QString getStoresIds() const;
    void setStoresIds(const QString &stores_ids);
    bool is_stores_ids_Set() const;
    bool is_stores_ids_Valid() const;

    QString getStoreId() const;
    void setStoreId(const QString &store_id);
    bool is_store_id_Set() const;
    bool is_store_id_Valid() const;

    QString getLangId() const;
    void setLangId(const QString &lang_id);
    bool is_lang_id_Set() const;
    bool is_lang_id_Valid() const;

    double getQuantity() const;
    void setQuantity(const double &quantity);
    bool is_quantity_Set() const;
    bool is_quantity_Valid() const;

    double getReserveQuantity() const;
    void setReserveQuantity(const double &reserve_quantity);
    bool is_reserve_quantity_Set() const;
    bool is_reserve_quantity_Valid() const;

    bool isManageStock() const;
    void setManageStock(const bool &manage_stock);
    bool is_manage_stock_Set() const;
    bool is_manage_stock_Valid() const;

    QString getBackorderStatus() const;
    void setBackorderStatus(const QString &backorder_status);
    bool is_backorder_status_Set() const;
    bool is_backorder_status_Valid() const;

    double getIncreaseQuantity() const;
    void setIncreaseQuantity(const double &increase_quantity);
    bool is_increase_quantity_Set() const;
    bool is_increase_quantity_Valid() const;

    double getReduceQuantity() const;
    void setReduceQuantity(const double &reduce_quantity);
    bool is_reduce_quantity_Set() const;
    bool is_reduce_quantity_Valid() const;

    double getLowStockThreshold() const;
    void setLowStockThreshold(const double &low_stock_threshold);
    bool is_low_stock_threshold_Set() const;
    bool is_low_stock_threshold_Valid() const;

    QString getWarehouseId() const;
    void setWarehouseId(const QString &warehouse_id);
    bool is_warehouse_id_Set() const;
    bool is_warehouse_id_Valid() const;

    double getWeight() const;
    void setWeight(const double &weight);
    bool is_weight_Set() const;
    bool is_weight_Valid() const;

    QString getWeightUnit() const;
    void setWeightUnit(const QString &weight_unit);
    bool is_weight_unit_Set() const;
    bool is_weight_unit_Valid() const;

    double getHeight() const;
    void setHeight(const double &height);
    bool is_height_Set() const;
    bool is_height_Valid() const;

    double getLength() const;
    void setLength(const double &length);
    bool is_length_Set() const;
    bool is_length_Valid() const;

    double getWidth() const;
    void setWidth(const double &width);
    bool is_width_Set() const;
    bool is_width_Valid() const;

    QString getDimensionsUnit() const;
    void setDimensionsUnit(const QString &dimensions_unit);
    bool is_dimensions_unit_Set() const;
    bool is_dimensions_unit_Valid() const;

    bool isIsVirtual() const;
    void setIsVirtual(const bool &is_virtual);
    bool is_is_virtual_Set() const;
    bool is_is_virtual_Valid() const;

    bool isIsFreeShipping() const;
    void setIsFreeShipping(const bool &is_free_shipping);
    bool is_is_free_shipping_Set() const;
    bool is_is_free_shipping_Valid() const;

    QString getGtin() const;
    void setGtin(const QString &gtin);
    bool is_gtin_Set() const;
    bool is_gtin_Valid() const;

    QString getUpc() const;
    void setUpc(const QString &upc);
    bool is_upc_Set() const;
    bool is_upc_Valid() const;

    QString getMpn() const;
    void setMpn(const QString &mpn);
    bool is_mpn_Set() const;
    bool is_mpn_Valid() const;

    QString getEan() const;
    void setEan(const QString &ean);
    bool is_ean_Set() const;
    bool is_ean_Valid() const;

    QString getIsbn() const;
    void setIsbn(const QString &isbn);
    bool is_isbn_Set() const;
    bool is_isbn_Valid() const;

    QString getBarcode() const;
    void setBarcode(const QString &barcode);
    bool is_barcode_Set() const;
    bool is_barcode_Valid() const;

    QString getManufacturer() const;
    void setManufacturer(const QString &manufacturer);
    bool is_manufacturer_Set() const;
    bool is_manufacturer_Valid() const;

    QString getManufacturerId() const;
    void setManufacturerId(const QString &manufacturer_id);
    bool is_manufacturer_id_Set() const;
    bool is_manufacturer_id_Valid() const;

    QString getCategoriesIds() const;
    void setCategoriesIds(const QString &categories_ids);
    bool is_categories_ids_Set() const;
    bool is_categories_ids_Valid() const;

    QString getRelatedProductsIds() const;
    void setRelatedProductsIds(const QString &related_products_ids);
    bool is_related_products_ids_Set() const;
    bool is_related_products_ids_Valid() const;

    QString getUpSellProductsIds() const;
    void setUpSellProductsIds(const QString &up_sell_products_ids);
    bool is_up_sell_products_ids_Set() const;
    bool is_up_sell_products_ids_Valid() const;

    QString getCrossSellProductsIds() const;
    void setCrossSellProductsIds(const QString &cross_sell_products_ids);
    bool is_cross_sell_products_ids_Set() const;
    bool is_cross_sell_products_ids_Valid() const;

    QString getMetaTitle() const;
    void setMetaTitle(const QString &meta_title);
    bool is_meta_title_Set() const;
    bool is_meta_title_Valid() const;

    QString getMetaKeywords() const;
    void setMetaKeywords(const QString &meta_keywords);
    bool is_meta_keywords_Set() const;
    bool is_meta_keywords_Valid() const;

    QString getMetaDescription() const;
    void setMetaDescription(const QString &meta_description);
    bool is_meta_description_Set() const;
    bool is_meta_description_Valid() const;

    QString getSeoUrl() const;
    void setSeoUrl(const QString &seo_url);
    bool is_seo_url_Set() const;
    bool is_seo_url_Valid() const;

    QString getSearchKeywords() const;
    void setSearchKeywords(const QString &search_keywords);
    bool is_search_keywords_Set() const;
    bool is_search_keywords_Valid() const;

    QString getTags() const;
    void setTags(const QString &tags);
    bool is_tags_Set() const;
    bool is_tags_Valid() const;

    QString getDeliveryCode() const;
    void setDeliveryCode(const QString &delivery_code);
    bool is_delivery_code_Set() const;
    bool is_delivery_code_Valid() const;

    OAIProductAdd_package_details getPackageDetails() const;
    void setPackageDetails(const OAIProductAdd_package_details &package_details);
    bool is_package_details_Set() const;
    bool is_package_details_Valid() const;

    QString getCountryOfOrigin() const;
    void setCountryOfOrigin(const QString &country_of_origin);
    bool is_country_of_origin_Set() const;
    bool is_country_of_origin_Valid() const;

    QString getHarmonizedSystemCode() const;
    void setHarmonizedSystemCode(const QString &harmonized_system_code);
    bool is_harmonized_system_code_Set() const;
    bool is_harmonized_system_code_Valid() const;

    qint32 getShippingTemplateId() const;
    void setShippingTemplateId(const qint32 &shipping_template_id);
    bool is_shipping_template_id_Set() const;
    bool is_shipping_template_id_Valid() const;

    QString getWhenMade() const;
    void setWhenMade(const QString &when_made);
    bool is_when_made_Set() const;
    bool is_when_made_Valid() const;

    bool isIsSupply() const;
    void setIsSupply(const bool &is_supply);
    bool is_is_supply_Set() const;
    bool is_is_supply_Valid() const;

    bool isDownloadable() const;
    void setDownloadable(const bool &downloadable);
    bool is_downloadable_Set() const;
    bool is_downloadable_Valid() const;

    QList<QString> getMaterials() const;
    void setMaterials(const QList<QString> &materials);
    bool is_materials_Set() const;
    bool is_materials_Valid() const;

    bool isAutoRenew() const;
    void setAutoRenew(const bool &auto_renew);
    bool is_auto_renew_Set() const;
    bool is_auto_renew_Valid() const;

    bool isOnSale() const;
    void setOnSale(const bool &on_sale);
    bool is_on_sale_Set() const;
    bool is_on_sale_Valid() const;

    QString getProductionPartnerIds() const;
    void setProductionPartnerIds(const QString &production_partner_ids);
    bool is_production_partner_ids_Set() const;
    bool is_production_partner_ids_Valid() const;

    OAIProductAdd_manufacturer_info getManufacturerInfo() const;
    void setManufacturerInfo(const OAIProductAdd_manufacturer_info &manufacturer_info);
    bool is_manufacturer_info_Set() const;
    bool is_manufacturer_info_Valid() const;

    QString getReportRequestId() const;
    void setReportRequestId(const QString &report_request_id);
    bool is_report_request_id_Set() const;
    bool is_report_request_id_Valid() const;

    bool isDisableReportCache() const;
    void setDisableReportCache(const bool &disable_report_cache);
    bool is_disable_report_cache_Set() const;
    bool is_disable_report_cache_Valid() const;

    bool isReindex() const;
    void setReindex(const bool &reindex);
    bool is_reindex_Set() const;
    bool is_reindex_Valid() const;

    bool isClearCache() const;
    void setClearCache(const bool &clear_cache);
    bool is_clear_cache_Set() const;
    bool is_clear_cache_Valid() const;

    bool isCheckProcessStatus() const;
    void setCheckProcessStatus(const bool &check_process_status);
    bool is_check_process_status_Set() const;
    bool is_check_process_status_Valid() const;

    QList<OAIProductAdd_specifics_inner> getSpecifics() const;
    void setSpecifics(const QList<OAIProductAdd_specifics_inner> &specifics);
    bool is_specifics_Set() const;
    bool is_specifics_Valid() const;

    qint32 getShopSectionId() const;
    void setShopSectionId(const qint32 &shop_section_id);
    bool is_shop_section_id_Set() const;
    bool is_shop_section_id_Valid() const;

    OAIProductAdd_personalization_details getPersonalizationDetails() const;
    void setPersonalizationDetails(const OAIProductAdd_personalization_details &personalization_details);
    bool is_personalization_details_Set() const;
    bool is_personalization_details_Valid() const;

    QString getMarketplaceItemProperties() const;
    void setMarketplaceItemProperties(const QString &marketplace_item_properties);
    bool is_marketplace_item_properties_Set() const;
    bool is_marketplace_item_properties_Valid() const;

    double getMinOrderQuantity() const;
    void setMinOrderQuantity(const double &min_order_quantity);
    bool is_min_order_quantity_Set() const;
    bool is_min_order_quantity_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString m_model;
    bool m_model_isSet;
    bool m_model_isValid;

    QString m_sku;
    bool m_sku_isSet;
    bool m_sku_isValid;

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString m_description;
    bool m_description_isSet;
    bool m_description_isValid;

    QString m_short_description;
    bool m_short_description_isSet;
    bool m_short_description_isValid;

    double m_price;
    bool m_price_isSet;
    bool m_price_isValid;

    double m_old_price;
    bool m_old_price_isSet;
    bool m_old_price_isValid;

    double m_special_price;
    bool m_special_price_isSet;
    bool m_special_price_isValid;

    QString m_sprice_create;
    bool m_sprice_create_isSet;
    bool m_sprice_create_isValid;

    QString m_sprice_expire;
    bool m_sprice_expire_isSet;
    bool m_sprice_expire_isValid;

    double m_cost_price;
    bool m_cost_price_isSet;
    bool m_cost_price_isValid;

    double m_fixed_cost_shipping_price;
    bool m_fixed_cost_shipping_price_isSet;
    bool m_fixed_cost_shipping_price_isValid;

    double m_retail_price;
    bool m_retail_price_isSet;
    bool m_retail_price_isValid;

    QList<OAIProductAdd_tier_prices_inner> m_tier_prices;
    bool m_tier_prices_isSet;
    bool m_tier_prices_isValid;

    double m_reserve_price;
    bool m_reserve_price_isSet;
    bool m_reserve_price_isValid;

    double m_buyitnow_price;
    bool m_buyitnow_price_isSet;
    bool m_buyitnow_price_isValid;

    bool m_taxable;
    bool m_taxable_isSet;
    bool m_taxable_isValid;

    QString m_tax_class_id;
    bool m_tax_class_id_isSet;
    bool m_tax_class_id_isValid;

    QString m_type;
    bool m_type_isSet;
    bool m_type_isValid;

    QString m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    QString m_condition;
    bool m_condition_isSet;
    bool m_condition_isValid;

    QString m_visible;
    bool m_visible_isSet;
    bool m_visible_isValid;

    bool m_in_stock;
    bool m_in_stock_isSet;
    bool m_in_stock_isValid;

    bool m_avail;
    bool m_avail_isSet;
    bool m_avail_isValid;

    QString m_avail_from;
    bool m_avail_from_isSet;
    bool m_avail_from_isValid;

    QString m_product_class;
    bool m_product_class_isSet;
    bool m_product_class_isValid;

    bool m_available_for_view;
    bool m_available_for_view_isSet;
    bool m_available_for_view_isValid;

    QString m_stores_ids;
    bool m_stores_ids_isSet;
    bool m_stores_ids_isValid;

    QString m_store_id;
    bool m_store_id_isSet;
    bool m_store_id_isValid;

    QString m_lang_id;
    bool m_lang_id_isSet;
    bool m_lang_id_isValid;

    double m_quantity;
    bool m_quantity_isSet;
    bool m_quantity_isValid;

    double m_reserve_quantity;
    bool m_reserve_quantity_isSet;
    bool m_reserve_quantity_isValid;

    bool m_manage_stock;
    bool m_manage_stock_isSet;
    bool m_manage_stock_isValid;

    QString m_backorder_status;
    bool m_backorder_status_isSet;
    bool m_backorder_status_isValid;

    double m_increase_quantity;
    bool m_increase_quantity_isSet;
    bool m_increase_quantity_isValid;

    double m_reduce_quantity;
    bool m_reduce_quantity_isSet;
    bool m_reduce_quantity_isValid;

    double m_low_stock_threshold;
    bool m_low_stock_threshold_isSet;
    bool m_low_stock_threshold_isValid;

    QString m_warehouse_id;
    bool m_warehouse_id_isSet;
    bool m_warehouse_id_isValid;

    double m_weight;
    bool m_weight_isSet;
    bool m_weight_isValid;

    QString m_weight_unit;
    bool m_weight_unit_isSet;
    bool m_weight_unit_isValid;

    double m_height;
    bool m_height_isSet;
    bool m_height_isValid;

    double m_length;
    bool m_length_isSet;
    bool m_length_isValid;

    double m_width;
    bool m_width_isSet;
    bool m_width_isValid;

    QString m_dimensions_unit;
    bool m_dimensions_unit_isSet;
    bool m_dimensions_unit_isValid;

    bool m_is_virtual;
    bool m_is_virtual_isSet;
    bool m_is_virtual_isValid;

    bool m_is_free_shipping;
    bool m_is_free_shipping_isSet;
    bool m_is_free_shipping_isValid;

    QString m_gtin;
    bool m_gtin_isSet;
    bool m_gtin_isValid;

    QString m_upc;
    bool m_upc_isSet;
    bool m_upc_isValid;

    QString m_mpn;
    bool m_mpn_isSet;
    bool m_mpn_isValid;

    QString m_ean;
    bool m_ean_isSet;
    bool m_ean_isValid;

    QString m_isbn;
    bool m_isbn_isSet;
    bool m_isbn_isValid;

    QString m_barcode;
    bool m_barcode_isSet;
    bool m_barcode_isValid;

    QString m_manufacturer;
    bool m_manufacturer_isSet;
    bool m_manufacturer_isValid;

    QString m_manufacturer_id;
    bool m_manufacturer_id_isSet;
    bool m_manufacturer_id_isValid;

    QString m_categories_ids;
    bool m_categories_ids_isSet;
    bool m_categories_ids_isValid;

    QString m_related_products_ids;
    bool m_related_products_ids_isSet;
    bool m_related_products_ids_isValid;

    QString m_up_sell_products_ids;
    bool m_up_sell_products_ids_isSet;
    bool m_up_sell_products_ids_isValid;

    QString m_cross_sell_products_ids;
    bool m_cross_sell_products_ids_isSet;
    bool m_cross_sell_products_ids_isValid;

    QString m_meta_title;
    bool m_meta_title_isSet;
    bool m_meta_title_isValid;

    QString m_meta_keywords;
    bool m_meta_keywords_isSet;
    bool m_meta_keywords_isValid;

    QString m_meta_description;
    bool m_meta_description_isSet;
    bool m_meta_description_isValid;

    QString m_seo_url;
    bool m_seo_url_isSet;
    bool m_seo_url_isValid;

    QString m_search_keywords;
    bool m_search_keywords_isSet;
    bool m_search_keywords_isValid;

    QString m_tags;
    bool m_tags_isSet;
    bool m_tags_isValid;

    QString m_delivery_code;
    bool m_delivery_code_isSet;
    bool m_delivery_code_isValid;

    OAIProductAdd_package_details m_package_details;
    bool m_package_details_isSet;
    bool m_package_details_isValid;

    QString m_country_of_origin;
    bool m_country_of_origin_isSet;
    bool m_country_of_origin_isValid;

    QString m_harmonized_system_code;
    bool m_harmonized_system_code_isSet;
    bool m_harmonized_system_code_isValid;

    qint32 m_shipping_template_id;
    bool m_shipping_template_id_isSet;
    bool m_shipping_template_id_isValid;

    QString m_when_made;
    bool m_when_made_isSet;
    bool m_when_made_isValid;

    bool m_is_supply;
    bool m_is_supply_isSet;
    bool m_is_supply_isValid;

    bool m_downloadable;
    bool m_downloadable_isSet;
    bool m_downloadable_isValid;

    QList<QString> m_materials;
    bool m_materials_isSet;
    bool m_materials_isValid;

    bool m_auto_renew;
    bool m_auto_renew_isSet;
    bool m_auto_renew_isValid;

    bool m_on_sale;
    bool m_on_sale_isSet;
    bool m_on_sale_isValid;

    QString m_production_partner_ids;
    bool m_production_partner_ids_isSet;
    bool m_production_partner_ids_isValid;

    OAIProductAdd_manufacturer_info m_manufacturer_info;
    bool m_manufacturer_info_isSet;
    bool m_manufacturer_info_isValid;

    QString m_report_request_id;
    bool m_report_request_id_isSet;
    bool m_report_request_id_isValid;

    bool m_disable_report_cache;
    bool m_disable_report_cache_isSet;
    bool m_disable_report_cache_isValid;

    bool m_reindex;
    bool m_reindex_isSet;
    bool m_reindex_isValid;

    bool m_clear_cache;
    bool m_clear_cache_isSet;
    bool m_clear_cache_isValid;

    bool m_check_process_status;
    bool m_check_process_status_isSet;
    bool m_check_process_status_isValid;

    QList<OAIProductAdd_specifics_inner> m_specifics;
    bool m_specifics_isSet;
    bool m_specifics_isValid;

    qint32 m_shop_section_id;
    bool m_shop_section_id_isSet;
    bool m_shop_section_id_isValid;

    OAIProductAdd_personalization_details m_personalization_details;
    bool m_personalization_details_isSet;
    bool m_personalization_details_isValid;

    QString m_marketplace_item_properties;
    bool m_marketplace_item_properties_isSet;
    bool m_marketplace_item_properties_isValid;

    double m_min_order_quantity;
    bool m_min_order_quantity_isSet;
    bool m_min_order_quantity_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIProductUpdate)

#endif // OAIProductUpdate_H
