/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIProductAdd_size_chart.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIProductAdd_size_chart::OAIProductAdd_size_chart(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIProductAdd_size_chart::OAIProductAdd_size_chart() {
    this->initializeModel();
}

OAIProductAdd_size_chart::~OAIProductAdd_size_chart() {}

void OAIProductAdd_size_chart::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_url_isSet = false;
    m_url_isValid = false;
}

void OAIProductAdd_size_chart::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIProductAdd_size_chart::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_url_isValid = ::OpenAPI::fromJsonValue(m_url, json[QString("url")]);
    m_url_isSet = !json[QString("url")].isNull() && m_url_isValid;
}

QString OAIProductAdd_size_chart::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIProductAdd_size_chart::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_url_isSet) {
        obj.insert(QString("url"), ::OpenAPI::toJsonValue(m_url));
    }
    return obj;
}

QString OAIProductAdd_size_chart::getId() const {
    return m_id;
}
void OAIProductAdd_size_chart::setId(const QString &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAIProductAdd_size_chart::is_id_Set() const{
    return m_id_isSet;
}

bool OAIProductAdd_size_chart::is_id_Valid() const{
    return m_id_isValid;
}

QString OAIProductAdd_size_chart::getUrl() const {
    return m_url;
}
void OAIProductAdd_size_chart::setUrl(const QString &url) {
    m_url = url;
    m_url_isSet = true;
}

bool OAIProductAdd_size_chart::is_url_Set() const{
    return m_url_isSet;
}

bool OAIProductAdd_size_chart::is_url_Valid() const{
    return m_url_isValid;
}

bool OAIProductAdd_size_chart::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_url_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIProductAdd_size_chart::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
