/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIReturn.h
 *
 * 
 */

#ifndef OAIReturn_H
#define OAIReturn_H

#include <QJsonObject>

#include "OAIObject.h"
#include "OAIReturn_OrderProduct.h"
#include "OAIReturn_Status.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIReturn_Status;
class OAIReturn_OrderProduct;

class OAIReturn : public OAIObject {
public:
    OAIReturn();
    OAIReturn(QString json);
    ~OAIReturn() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);
    bool is_id_Set() const;
    bool is_id_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getOrderId() const;
    void setOrderId(const QString &order_id);
    bool is_order_id_Set() const;
    bool is_order_id_Valid() const;

    QString getCustomerId() const;
    void setCustomerId(const QString &customer_id);
    bool is_customer_id_Set() const;
    bool is_customer_id_Valid() const;

    QString getStoreId() const;
    void setStoreId(const QString &store_id);
    bool is_store_id_Set() const;
    bool is_store_id_Valid() const;

    QString getCreatedAt() const;
    void setCreatedAt(const QString &created_at);
    bool is_created_at_Set() const;
    bool is_created_at_Valid() const;

    QString getModifiedAt() const;
    void setModifiedAt(const QString &modified_at);
    bool is_modified_at_Set() const;
    bool is_modified_at_Valid() const;

    OAIReturn_Status getStatus() const;
    void setStatus(const OAIReturn_Status &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QList<OAIReturn_OrderProduct> getOrderProducts() const;
    void setOrderProducts(const QList<OAIReturn_OrderProduct> &order_products);
    bool is_order_products_Set() const;
    bool is_order_products_Valid() const;

    QString getComment() const;
    void setComment(const QString &comment);
    bool is_comment_Set() const;
    bool is_comment_Valid() const;

    QString getStaffNote() const;
    void setStaffNote(const QString &staff_note);
    bool is_staff_note_Set() const;
    bool is_staff_note_Valid() const;

    OAIObject getAdditionalFields() const;
    void setAdditionalFields(const OAIObject &additional_fields);
    bool is_additional_fields_Set() const;
    bool is_additional_fields_Valid() const;

    OAIObject getCustomFields() const;
    void setCustomFields(const OAIObject &custom_fields);
    bool is_custom_fields_Set() const;
    bool is_custom_fields_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_id;
    bool m_id_isSet;
    bool m_id_isValid;

    QString m_name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString m_order_id;
    bool m_order_id_isSet;
    bool m_order_id_isValid;

    QString m_customer_id;
    bool m_customer_id_isSet;
    bool m_customer_id_isValid;

    QString m_store_id;
    bool m_store_id_isSet;
    bool m_store_id_isValid;

    QString m_created_at;
    bool m_created_at_isSet;
    bool m_created_at_isValid;

    QString m_modified_at;
    bool m_modified_at_isSet;
    bool m_modified_at_isValid;

    OAIReturn_Status m_status;
    bool m_status_isSet;
    bool m_status_isValid;

    QList<OAIReturn_OrderProduct> m_order_products;
    bool m_order_products_isSet;
    bool m_order_products_isValid;

    QString m_comment;
    bool m_comment_isSet;
    bool m_comment_isValid;

    QString m_staff_note;
    bool m_staff_note_isSet;
    bool m_staff_note_isValid;

    OAIObject m_additional_fields;
    bool m_additional_fields_isSet;
    bool m_additional_fields_isValid;

    OAIObject m_custom_fields;
    bool m_custom_fields_isSet;
    bool m_custom_fields_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIReturn)

#endif // OAIReturn_H
