/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * The version of the OpenAPI document: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIShipment_Event.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIShipment_Event::OAIShipment_Event(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIShipment_Event::OAIShipment_Event() {
    this->initializeModel();
}

OAIShipment_Event::~OAIShipment_Event() {}

void OAIShipment_Event::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_status_isSet = false;
    m_status_isValid = false;

    m_created_at_isSet = false;
    m_created_at_isValid = false;

    m_estimated_delivery_at_isSet = false;
    m_estimated_delivery_at_isValid = false;

    m_message_isSet = false;
    m_message_isValid = false;

    m_address_isSet = false;
    m_address_isValid = false;

    m_additional_fields_isSet = false;
    m_additional_fields_isValid = false;

    m_custom_fields_isSet = false;
    m_custom_fields_isValid = false;
}

void OAIShipment_Event::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIShipment_Event::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_status_isValid = ::OpenAPI::fromJsonValue(m_status, json[QString("status")]);
    m_status_isSet = !json[QString("status")].isNull() && m_status_isValid;

    m_created_at_isValid = ::OpenAPI::fromJsonValue(m_created_at, json[QString("created_at")]);
    m_created_at_isSet = !json[QString("created_at")].isNull() && m_created_at_isValid;

    m_estimated_delivery_at_isValid = ::OpenAPI::fromJsonValue(m_estimated_delivery_at, json[QString("estimated_delivery_at")]);
    m_estimated_delivery_at_isSet = !json[QString("estimated_delivery_at")].isNull() && m_estimated_delivery_at_isValid;

    m_message_isValid = ::OpenAPI::fromJsonValue(m_message, json[QString("message")]);
    m_message_isSet = !json[QString("message")].isNull() && m_message_isValid;

    m_address_isValid = ::OpenAPI::fromJsonValue(m_address, json[QString("address")]);
    m_address_isSet = !json[QString("address")].isNull() && m_address_isValid;

    m_additional_fields_isValid = ::OpenAPI::fromJsonValue(m_additional_fields, json[QString("additional_fields")]);
    m_additional_fields_isSet = !json[QString("additional_fields")].isNull() && m_additional_fields_isValid;

    m_custom_fields_isValid = ::OpenAPI::fromJsonValue(m_custom_fields, json[QString("custom_fields")]);
    m_custom_fields_isSet = !json[QString("custom_fields")].isNull() && m_custom_fields_isValid;
}

QString OAIShipment_Event::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIShipment_Event::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_status_isSet) {
        obj.insert(QString("status"), ::OpenAPI::toJsonValue(m_status));
    }
    if (m_created_at.isSet()) {
        obj.insert(QString("created_at"), ::OpenAPI::toJsonValue(m_created_at));
    }
    if (m_estimated_delivery_at.isSet()) {
        obj.insert(QString("estimated_delivery_at"), ::OpenAPI::toJsonValue(m_estimated_delivery_at));
    }
    if (m_message_isSet) {
        obj.insert(QString("message"), ::OpenAPI::toJsonValue(m_message));
    }
    if (m_address.isSet()) {
        obj.insert(QString("address"), ::OpenAPI::toJsonValue(m_address));
    }
    if (m_additional_fields_isSet) {
        obj.insert(QString("additional_fields"), ::OpenAPI::toJsonValue(m_additional_fields));
    }
    if (m_custom_fields_isSet) {
        obj.insert(QString("custom_fields"), ::OpenAPI::toJsonValue(m_custom_fields));
    }
    return obj;
}

QString OAIShipment_Event::getId() const {
    return m_id;
}
void OAIShipment_Event::setId(const QString &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAIShipment_Event::is_id_Set() const{
    return m_id_isSet;
}

bool OAIShipment_Event::is_id_Valid() const{
    return m_id_isValid;
}

QString OAIShipment_Event::getStatus() const {
    return m_status;
}
void OAIShipment_Event::setStatus(const QString &status) {
    m_status = status;
    m_status_isSet = true;
}

bool OAIShipment_Event::is_status_Set() const{
    return m_status_isSet;
}

bool OAIShipment_Event::is_status_Valid() const{
    return m_status_isValid;
}

OAIA2CDateTime OAIShipment_Event::getCreatedAt() const {
    return m_created_at;
}
void OAIShipment_Event::setCreatedAt(const OAIA2CDateTime &created_at) {
    m_created_at = created_at;
    m_created_at_isSet = true;
}

bool OAIShipment_Event::is_created_at_Set() const{
    return m_created_at_isSet;
}

bool OAIShipment_Event::is_created_at_Valid() const{
    return m_created_at_isValid;
}

OAIA2CDateTime OAIShipment_Event::getEstimatedDeliveryAt() const {
    return m_estimated_delivery_at;
}
void OAIShipment_Event::setEstimatedDeliveryAt(const OAIA2CDateTime &estimated_delivery_at) {
    m_estimated_delivery_at = estimated_delivery_at;
    m_estimated_delivery_at_isSet = true;
}

bool OAIShipment_Event::is_estimated_delivery_at_Set() const{
    return m_estimated_delivery_at_isSet;
}

bool OAIShipment_Event::is_estimated_delivery_at_Valid() const{
    return m_estimated_delivery_at_isValid;
}

QString OAIShipment_Event::getMessage() const {
    return m_message;
}
void OAIShipment_Event::setMessage(const QString &message) {
    m_message = message;
    m_message_isSet = true;
}

bool OAIShipment_Event::is_message_Set() const{
    return m_message_isSet;
}

bool OAIShipment_Event::is_message_Valid() const{
    return m_message_isValid;
}

OAICustomer_Address OAIShipment_Event::getAddress() const {
    return m_address;
}
void OAIShipment_Event::setAddress(const OAICustomer_Address &address) {
    m_address = address;
    m_address_isSet = true;
}

bool OAIShipment_Event::is_address_Set() const{
    return m_address_isSet;
}

bool OAIShipment_Event::is_address_Valid() const{
    return m_address_isValid;
}

OAIObject OAIShipment_Event::getAdditionalFields() const {
    return m_additional_fields;
}
void OAIShipment_Event::setAdditionalFields(const OAIObject &additional_fields) {
    m_additional_fields = additional_fields;
    m_additional_fields_isSet = true;
}

bool OAIShipment_Event::is_additional_fields_Set() const{
    return m_additional_fields_isSet;
}

bool OAIShipment_Event::is_additional_fields_Valid() const{
    return m_additional_fields_isValid;
}

OAIObject OAIShipment_Event::getCustomFields() const {
    return m_custom_fields;
}
void OAIShipment_Event::setCustomFields(const OAIObject &custom_fields) {
    m_custom_fields = custom_fields;
    m_custom_fields_isSet = true;
}

bool OAIShipment_Event::is_custom_fields_Set() const{
    return m_custom_fields_isSet;
}

bool OAIShipment_Event::is_custom_fields_Valid() const{
    return m_custom_fields_isValid;
}

bool OAIShipment_Event::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_status_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_created_at.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_estimated_delivery_at.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_message_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_address.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_additional_fields_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_custom_fields_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIShipment_Event::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
